/**
 * @file query_optimizer.h
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.47
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=5; TODO=1, Stub=3, Unimpl=0, Mock=1, Sim=0, Debt=0, C=n/a, H=n/a, M=n/a, L=n/a
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


#pragma once

#include <string>
#include <string_view>
#include <vector>
#include <utility>
#include <map>
#include <memory>
#include <mutex>

#include "query/query_engine.h"
#include "query/adaptive_optimizer.h"
#include "query/optimizer_cost_model.h"

// Forward-declare PerQueryCostModel to avoid a hard dependency;
// callers that want to use it must include the full header.
namespace themis { namespace performance { namespace phase3 { class PerQueryCostModel; } } }

// Forward-declare StatisticsCollector and MetricsCollector to avoid hard dependencies.
namespace themis { class StatisticsCollector; }
namespace themis { namespace observability { class MetricsCollector; } }

namespace themis {
namespace query {

using SecondaryIndexManager = ::themis::SecondaryIndexManager;

class QueryOptimizer {
public:
    struct Estimation {
        PredicateEq pred;
        size_t estimatedCount = 0; // bis maxProbe gezählt
        bool capped = false;       // true, wenn abgeschnitten (>= maxProbe)
    };

    struct Plan {
        std::vector<PredicateEq> orderedPredicates; // aufsteigend nach erwarteter Selektivität
        std::vector<Estimation> details;            // für Logging/Diagnose
        
        // NLP-based metadata (PR #317)
        double nlp_complexity = 0.0;                // Query complexity estimate (0.0-1.0)
        std::vector<std::string> nlp_suggested_indexes; // Suggested index types
        std::map<std::string, std::string> nlp_hints;   // Semantic optimization hints

        // Serialization + execution-path recommendation (SerializationStrategyAdvisor)
        OptimizerCostModel::SerializationAdvice serialization_advice;
    };

    /// @param secIdx          Secondary index manager (required).
    /// @param stats_collector Optional statistics collector for cardinality/histogram estimates.
    /// @param metrics_collector Optional metrics collector for Prometheus instrumentation.
    QueryOptimizer(SecondaryIndexManager& secIdx,
                   StatisticsCollector* stats_collector = nullptr,
                   observability::MetricsCollector* metrics_collector = nullptr);

    // Schätzt Selektivitäten der Gleichheitsprädikate und liefert eine Ordnung (kleinste zuerst)
    Plan chooseOrderForAndQuery(const ConjunctiveQuery& q, size_t maxProbePerPred = 1000) const;

    // =============================
    // Serialization Advisor tuning
    // =============================

    /**
     * @brief Replace the cost constants used by the serialization-strategy advisor.
     *
     * Allows external calibration (e.g. via PerQueryCostModel::calibrate) to flow
     * into subsequent chooseOrderForAndQuery() calls.
     *
     * Thread-safety: acquires advisor_cost_model_mutex_.
     */
    void setAdvisorCostConstants(const OptimizerCostModel::CostConstants& c);

    /**
     * @brief Return a snapshot copy of the advisor's current cost constants.
     *
     * Thread-safety: acquires advisor_cost_model_mutex_ and returns by value so
     * callers never observe mutable shared state after lock release.
     */
    OptimizerCostModel::CostConstants advisorCostConstants() const;
    
    // NLP-enhanced query optimization (PR #317 Phase 1)
    // Combines traditional cost-based optimization with NLP-based semantic analysis
    Plan chooseOrderForAndQueryWithNLP(const ConjunctiveQuery& q, 
                                       const std::string& original_query_text,
                                       size_t maxProbePerPred = 1000) const;

    // Führt die Anfrage mit der geplanten Reihenfolge aus (sequenziell)
    Result<std::vector<std::string>>
    executeOptimizedKeys(QueryEngine& engine, const ConjunctiveQuery& q, const Plan& plan) const;

    Result<std::vector<BaseEntity>>
    executeOptimizedEntities(QueryEngine& engine, const ConjunctiveQuery& q, const Plan& plan) const;

    /**
     * @brief Execute optimized conjunctive query and return only match count.
     * @param engine Query engine instance used for execution
     * @param q Original conjunctive query (table context)
     * @param plan Optimized predicate order generated by chooseOrderForAndQuery()
     * @return Number of matching primary keys
     *
     * Uses the same optimized sequential predicate order as executeOptimizedKeys,
     * but avoids returning key payload to the caller.
     */
    Result<size_t>
    executeOptimizedCount(QueryEngine& engine, const ConjunctiveQuery& q, const Plan& plan) const;

    // =============================
    // Per-Query Cost Model Integration (Phase 3, Issue #2419)
    // =============================

    /**
     * @brief Attach a PerQueryCostModel for runtime cost recording and calibration.
     *
     * When attached, executeOptimizedKeys and executeOptimizedEntities will record
     * actual execution time into the model.  Pass nullptr to detach.
     */
    void attachPerQueryCostModel(
        std::shared_ptr<performance::phase3::PerQueryCostModel> cost_model);

    /** @brief Return the currently attached PerQueryCostModel (may be nullptr). */
    std::shared_ptr<performance::phase3::PerQueryCostModel> perQueryCostModel() const;

    /**
     * @brief Execute keys query and record timing in the attached PerQueryCostModel.
     *
     * Functionally identical to executeOptimizedKeys; the extra @p estimated_cost
     * value is forwarded to the cost model to compute the cost ratio.
     */
    Result<std::vector<std::string>>
    executeOptimizedKeysWithCost(QueryEngine& engine,
                                  const ConjunctiveQuery& q,
                                  const Plan& plan,
                                  double estimated_cost = 0.0) const;

    /**
     * @brief Execute entities query and record timing in the attached PerQueryCostModel.
     */
    Result<std::vector<BaseEntity>>
    executeOptimizedEntitiesWithCost(QueryEngine& engine,
                                      const ConjunctiveQuery& q,
                                      const Plan& plan,
                                      double estimated_cost = 0.0) const;

    // =============================
    // Hybrid Vector+Geo Cost Model
    // =============================
    struct VectorGeoCostInput {
        bool hasVectorIndex = false;
        bool hasSpatialIndex = false;
        double bboxRatio = 1.0;              // area(bbox)/area(total)
        size_t prefilterSize = 0;             // equality prefilter candidate universe
        size_t spatialIndexEntries = 0;       // number of spatial index entries (approx table size for spatial filter)
        size_t k = 10;                        // requested top-k
        size_t vectorDim = 0;                 // vector dimension (for scaling)
        size_t overfetch = 1;                 // overfetch multiplier
    };
    enum class VectorGeoPlan { SpatialThenVector, VectorThenSpatial };
    struct VectorGeoCostResult {
        VectorGeoPlan plan;
        double costSpatialFirst = 0.0;
        double costVectorFirst = 0.0;
    };
    static VectorGeoCostResult chooseVectorGeoPlan(const VectorGeoCostInput& in);

    // =============================
    // Content+Geo (Fulltext + Spatial) Cost Model (stub)
    // =============================
    struct ContentGeoCostInput {
        bool hasFulltextIndex = true;
        bool hasSpatialIndex = false;
        size_t fulltextHits = 0;          // estimated FT hit count
        double bboxRatio = 1.0;           // spatial selectivity
        size_t limit = 100;               // requested limit
    };
    struct ContentGeoCostResult {
        double costFulltextThenSpatial = 0.0;
        double costSpatialThenFulltext = 0.0; // for future when spatial prefilter can restrict FT search scope
        bool chooseFulltextFirst = false;       // current plan choice
    };
    static ContentGeoCostResult estimateContentGeo(const ContentGeoCostInput& in);

    // =============================
    // Graph Shortest Path Cost Model (stub)
    // =============================
    struct GraphPathCostInput {
        size_t maxDepth = 5;
        size_t branchingFactor = 4;    // estimated average outgoing edges per vertex
        bool hasSpatialConstraint = false;
        double spatialSelectivity = 1.0; // fraction of vertices passing spatial filter
    };
    struct GraphPathCostResult {
        double estimatedExpandedVertices = 0.0;
        double estimatedTimeMs = 0.0; // abstract
    };
    static GraphPathCostResult estimateGraphPath(const GraphPathCostInput& in);

    // =============================
    // Adaptive & Distributed Optimization (New)
    // =============================
    
    /**
     * @brief Enable adaptive optimization with runtime statistics
     */
    void enableAdaptiveOptimization(bool enable = true);
    
    /**
     * @brief Check if adaptive optimization is enabled
     */
    bool isAdaptiveOptimizationEnabled() const { return adaptive_enabled_; }
    
    /**
     * @brief Record query execution statistics for adaptive learning
     */
    void recordQueryExecution(
        const std::string& query_hash,
        size_t estimated_rows,
        size_t actual_rows,
        double execution_time_ms);
    
    /**
     * @brief Get adaptive adjustment factor for a query pattern
     */
    double getAdaptiveAdjustment(const std::string& query_hash) const;
    
    /**
     * @brief Optimize for distributed/sharded execution
     */
    struct DistributedPlan {
        std::vector<std::string> shard_ids;
        bool use_partition_pruning = false;
        std::string join_strategy;  // "broadcast", "repartition", "semi_join"
        size_t recommended_parallelism = 1;
        bool enable_numa_awareness = false;
        std::vector<int> preferred_cpu_affinity;
    };
    
    DistributedPlan optimizeForDistribution(
        const ConjunctiveQuery& q,
        const std::vector<std::string>& available_shards,
        bool enable_partition_pruning = true) const;
    
    /**
     * @brief Optimize for vector workload with adaptive HNSW tuning
     */
    struct VectorWorkloadPlan {
        int recommended_ef_search = 0;
        size_t recommended_k_overfetch = 0;
        bool use_prefiltering = false;
        std::string index_type;  // "hnsw", "ivf", "flat"
    };
    
    VectorWorkloadPlan optimizeVectorWorkload(
        size_t k,
        size_t dataset_size,
        size_t dimension,
        double target_recall = 0.95) const;
    
    /**
     * @brief Optimize for graph workload
     */
    struct GraphWorkloadPlan {
        size_t max_expansion_depth = 0;
        bool use_bidirectional_search = false;
        bool enable_spatial_pruning = false;
        size_t recommended_parallelism = 0;
    };
    
    GraphWorkloadPlan optimizeGraphWorkload(
        size_t max_depth,
        size_t estimated_branching_factor,
        bool has_spatial_constraint = false) const;

private:
    SecondaryIndexManager& secIdx_;
    bool adaptive_enabled_ = false;

    // Injected collectors (non-owning pointers; callers manage lifetime)
    StatisticsCollector* stats_collector_ = nullptr;
    observability::MetricsCollector* metrics_collector_ = nullptr;

    // ========================================================================
    // THREAD-SAFETY: Per-Query Cost Model (GAP-1)
    // ========================================================================
    // Protects access to per_query_cost_model_ shared_ptr.
    // All attach/detach and execute methods must hold this lock when reading.
    // Ordering: This lock is held SECOND after advisor_cost_model_mutex_.
    mutable std::mutex per_query_cost_model_mutex_;

    // Per-query cost model (Phase 3, Issue #2419)
    // THREAD-SAFE: Protected by per_query_cost_model_mutex_
    mutable std::shared_ptr<performance::phase3::PerQueryCostModel> per_query_cost_model_;

    // ========================================================================
    // THREAD-SAFETY: Cost Model Constants (GAP-2)
    // ========================================================================
    // Protects access to advisor_cost_model_ member state.
    // All reads in chooseOrderForAndQuery() and writes via setAdvisorCostConstants()
    // must hold this lock.
    // Ordering: This lock is held FIRST. If both locks are needed, acquire this
    //           lock before per_query_cost_model_mutex_.
    mutable std::mutex advisor_cost_model_mutex_;

    // Cost model instance shared across chooseOrderForAndQuery() calls so that
    // calibrated constants (via setAdvisorCostConstants / PerQueryCostModel::calibrate)
    // are preserved between calls instead of being discarded with a local instance.
    // THREAD-SAFE: Protected by advisor_cost_model_mutex_
    OptimizerCostModel advisor_cost_model_;

    // ========================================================================
    // THREAD-SAFETY: Adaptive Optimization Initialization (GAP-3)
    // ========================================================================
    // Protects initialization of adaptive_stats_ and adaptive_selector_.
    // Used with std::call_once() for double-checked initialization.
    mutable std::once_flag adaptive_init_flag_;
    mutable std::mutex adaptive_init_mutex_;

    // Adaptive query optimization components
    // Use the full implementations from adaptive_optimizer.h
    // (No using needed - both AdaptiveQueryStats and AdaptivePlanSelector are in themis::query namespace)
    // THREAD-SAFE: Initialized once via call_once, then read-only
    
    class DistributedQueryCostModel {
    public:
        explicit DistributedQueryCostModel(
            StatisticsCollector* stats = nullptr,
            observability::MetricsCollector* metrics = nullptr)
            : stats_collector_(stats), metrics_collector_(metrics) {}

        struct ShardInfo {
            std::string shard_id;
            size_t estimated_rows = 0;
            double network_latency_ms = 0.0;
            bool is_local = false;
        };
        
        /**
         * @brief Determine if a partition should be pruned based on selectivity
         * Production implementation - uses actual shard metadata
         */
        bool shouldPrunePartition(const ShardInfo& info, size_t total_shards, double selectivity) const;
        
        /**
         * @brief Get optimal parallelism for distributed query
         * Production implementation - considers shard count and hardware
         */
        size_t getOptimalParallelism(const std::vector<ShardInfo>& shards, size_t available_threads) const;
        
        /**
         * @brief Get shard metadata for row count estimation
         * Integrates with MetadataShard system (v1.5.x)
         */
        size_t getShardRowCount(const std::string& shard_id, const std::string& table) const;
        
        /**
         * @brief Measure network latency to a shard
         * Integrates with PrometheusMetrics system (v1.5.x)
         */
        double measureShardLatency(const std::string& shard_id) const;
        
        /**
         * @brief Calculate predicate selectivity from query predicates
         * Histogram-based estimation (v1.5.x)
         */
        double calculatePredicateSelectivity(
            const std::vector<PredicateEq>& predicates,
            const std::string& table) const;

    private:
        // Non-owning pointers injected at construction time
        StatisticsCollector* stats_collector_ = nullptr;
        observability::MetricsCollector* metrics_collector_ = nullptr;
    };
    
    class MultiIndexOptimizer {
    public:
        MultiIndexOptimizer() = default;
    };
    
    // These will be initialized when adaptive optimization is enabled
    mutable std::shared_ptr<AdaptiveQueryStats> adaptive_stats_;
    mutable std::shared_ptr<AdaptivePlanSelector> adaptive_selector_;
    mutable std::shared_ptr<DistributedQueryCostModel> distributed_model_;
    mutable std::shared_ptr<MultiIndexOptimizer> multi_index_optimizer_;
};

} // namespace query
} // namespace themis

