/*
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            explain_plan.h                                     ║
  Version:         0.1.0                                              ║
  Last Modified:   2026-07-01 00:00:00                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟡 INTERFACE                                    ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     100                                             ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: 🟡 Interface Header (Target: v1.5.0)                        ║
╚═════════════════════════════════════════════════════════════════════╝
 */

#pragma once

/**
 * @file explain_plan.h
 * @brief Graph query EXPLAIN plan inspection interface.
 *
 * Provides `IGraphExplainProvider` and associated data structures for
 * inspecting the query plan generated by the graph engine.  Supports both
 * EXPLAIN (estimated costs only) and EXPLAIN ANALYZE (actual execution times).
 *
 * Output formats:
 *   - `GraphExplainPlan::toDot()`  — Graphviz DOT notation for visualization.
 *   - `GraphExplainPlan::toJson()` — JSON representation for programmatic use.
 */

#include <string>
#include <vector>
#include &lt;map&gt;

namespace themis {
namespace graph {

// ---------------------------------------------------------------------------
// GraphPlanNodeType
// ---------------------------------------------------------------------------

/// @brief Node types that can appear in a graph query execution plan.
enum class GraphPlanNodeType {
    VERTEX_SCAN,
    EDGE_SCAN,
    INDEX_LOOKUP,
    BFS_TRAVERSAL,
    DFS_TRAVERSAL,
    SHORTEST_PATH,
    FILTER,
    PROJECTION,
    AGGREGATE,
    SORT,
    LIMIT,
    HASH_JOIN,
    NESTED_LOOP_JOIN,
};

// ---------------------------------------------------------------------------
// GraphPlanNode
// ---------------------------------------------------------------------------

/**
 * @brief A single node in a graph query execution plan tree.
 *
 * `actual_ms` and `actual_rows` are populated only when the plan was obtained
 * via `explainAnalyze()`.  For plain `explain()`, `actual_ms` is -1.0 and
 * `actual_rows` is 0.
 */
struct GraphPlanNode {
    std::string node_id;
    GraphPlanNodeType type;
    std::string description;
    std::vector<std::string> child_node_ids;
    std::map<std::string, std::string> properties;
    double estimated_cost = 0.0;
    double estimated_rows = 0.0;
    double actual_ms      = -1.0;  ///< -1 = not executed (EXPLAIN only)
    size_t actual_rows    = 0;
};

// ---------------------------------------------------------------------------
// GraphExplainPlan
// ---------------------------------------------------------------------------

/**
 * @brief Complete EXPLAIN plan for a graph query.
 *
 * `is_analyzed` is true when the plan was obtained via `explainAnalyze()` and
 * all `GraphPlanNode::actual_ms` fields are populated with real timings.
 */
struct GraphExplainPlan {
    std::string query;
    std::string plan_id;
    std::vector<GraphPlanNode> nodes;
    std::string root_node_id;
    double total_estimated_cost = 0.0;
    double total_actual_ms      = -1.0;
    bool is_analyzed            = false;

    /// @brief Serialize the plan to Graphviz DOT format.
    std::string toDot() const;

    /// @brief Serialize the plan to JSON.
    std::string toJson() const;
};

// ---------------------------------------------------------------------------
// IGraphExplainProvider
// ---------------------------------------------------------------------------

/**
 * @brief Interface for obtaining EXPLAIN plans from the graph query engine.
 */
class IGraphExplainProvider {
public:
    virtual ~IGraphExplainProvider() = default;

    /**
     * @brief Return the estimated execution plan without running the query.
     * @param query   AQL or graph query string.
     * @param params  Optional bind parameters.
     */
    virtual GraphExplainPlan explain(
        const std::string& query,
        const std::map<std::string, std::string>& params = {}) = 0;

    /**
     * @brief Execute the query and return the plan with actual timings.
     * @param query   AQL or graph query string.
     * @param params  Optional bind parameters.
     */
    virtual GraphExplainPlan explainAnalyze(
        const std::string& query,
        const std::map<std::string, std::string>& params = {}) = 0;
};

} // namespace graph
} // namespace themis
