/**
 * @file test_root_cause_analyzer.cpp
 * @brief Focused tests for the RootCauseAnalyzer (v1.7.0, observability module).
 *
 * Test suite: RootCauseAnalyzerFocusedTests
 *
 * Covers:
 *   TimeSeries:
 *     - change_percent with two-point series
 *     - mean with uniform values
 *
 *   SystemSnapshot:
 *     - toJSON produces correct keys
 *
 *   CausalGraph:
 *     - rootNodes returns nodes with no incoming edges
 *     - toJSON serializes nodes and edges
 *
 *   RootCauseReport:
 *     - toJSON contains all required fields
 *     - toReport contains primary cause and confidence
 *
 *   RootCauseAnalyzer:
 *     - analyzeIssue: storage amplification scenario → "High compaction rate"
 *     - analyzeIssue: cache thrashing scenario
 *     - analyzeIssue: unknown degradation fallback
 *     - analyzeIssue: metric_impacts populated from delta
 *     - analyzeIssue: contributing_factors sorted by |delta|
 *     - findCorrelations: perfect positive correlation detected
 *     - findCorrelations: perfectly anti-correlated series detected
 *     - findCorrelations: uncorrelated series excluded
 *     - findCorrelations: unknown metric returns empty vector
 *     - findCorrelations: max_correlations limit honoured
 *     - buildCausalGraph: causal edge added when lag correlation dominates
 *     - buildCausalGraph: no edge for uncorrelated series
 *     - buildCausalGraph: rootNodes from resulting graph
 *     - addTimeSeries / removeTimeSeries round-trip
 *     - getConfig / setConfig round-trip
 */

#include <gtest/gtest.h>
#include "observability/root_cause_analyzer.h"
#include "observability/performance_analyzer.h"

using namespace themis::observability;
using namespace std::chrono_literals;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

namespace {

/// Build a simple two-point TimeSeries from a pair of values.
TimeSeries makeSeries(const std::string& name, double first, double last) {
    TimeSeries ts;
    ts.name = name;
    ts.unit = "unit";
    auto now = std::chrono::system_clock::now();
    ts.points.push_back({now - 1s, first});
    ts.points.push_back({now, last});
    return ts;
}

/// Build a longer TimeSeries from a vector of values.
TimeSeries makeSeriesFromVec(const std::string& name,
                             const std::vector<double>& values) {
    TimeSeries ts;
    ts.name = name;
    ts.unit = "unit";
    auto now = std::chrono::system_clock::now();
    for (size_t i = 0; i < values.size(); ++i) {
        ts.points.push_back({now - std::chrono::seconds(values.size() - i), values[i]});
    }
    return ts;
}

/// Build a default SystemSnapshot with sensible "healthy" baseline values.
SystemSnapshot healthySnapshot() {
    SystemSnapshot s;
    s.write_amplification      = 3.2;
    s.read_amplification       = 1.5;
    s.compaction_rate_mb_s     = 10.0;
    s.memtable_flush_rate_mb_s = 5.0;
    s.sstable_count            = 100.0;
    s.block_cache_hit_rate_pct = 85.0;
    s.row_cache_hit_rate_pct   = 70.0;
    s.avg_query_latency_ms     = 5.0;
    s.p99_query_latency_ms     = 20.0;
    s.queries_per_second       = 1000.0;
    s.cpu_usage_pct            = 30.0;
    s.memory_usage_mb          = 2048.0;
    s.disk_io_utilization_pct  = 20.0;
    s.captured_at              = std::chrono::system_clock::now();
    return s;
}

/// Build a PerformanceIssue of the given category and severity.
PerformanceIssue makeIssue(IssueCategory cat, IssueSeverity sev = IssueSeverity::WARNING) {
    PerformanceIssue issue;
    issue.category    = cat;
    issue.severity    = sev;
    issue.title       = "Test issue";
    issue.description = "Generated by test";
    return issue;
}

} // anonymous namespace

// ============================================================================
// TimeSeries
// ============================================================================

TEST(TimeSeriesTest, ChangePercent_TwoPoints) {
    TimeSeries ts = makeSeries("m", 100.0, 150.0);
    EXPECT_NEAR(ts.change_percent(), 50.0, 0.01);
}

TEST(TimeSeriesTest, ChangePercent_NegativeDelta) {
    TimeSeries ts = makeSeries("m", 200.0, 100.0);
    EXPECT_NEAR(ts.change_percent(), -50.0, 0.01);
}

TEST(TimeSeriesTest, ChangePercent_SinglePoint_ReturnsZero) {
    TimeSeries ts;
    ts.name = "m";
    ts.points.push_back({std::chrono::system_clock::now(), 42.0});
    EXPECT_DOUBLE_EQ(ts.change_percent(), 0.0);
}

TEST(TimeSeriesTest, ChangePercent_ZeroStart_ReturnsZero) {
    TimeSeries ts = makeSeries("m", 0.0, 50.0);
    EXPECT_DOUBLE_EQ(ts.change_percent(), 0.0);
}

TEST(TimeSeriesTest, Mean_UniformValues) {
    TimeSeries ts = makeSeriesFromVec("m", {2.0, 2.0, 2.0, 2.0});
    EXPECT_NEAR(ts.mean(), 2.0, 1e-9);
}

TEST(TimeSeriesTest, Mean_EmptySeries_ReturnsZero) {
    TimeSeries ts;
    ts.name = "empty";
    EXPECT_DOUBLE_EQ(ts.mean(), 0.0);
}

// ============================================================================
// SystemSnapshot
// ============================================================================

TEST(SystemSnapshotTest, ToJSON_ContainsExpectedKeys) {
    auto snap = healthySnapshot();
    json j = snap.toJSON();

    ASSERT_TRUE(j.is_object());
    EXPECT_TRUE(j.contains("write_amplification"));
    EXPECT_TRUE(j.contains("block_cache_hit_rate_pct"));
    EXPECT_TRUE(j.contains("avg_query_latency_ms"));
    EXPECT_TRUE(j.contains("cpu_usage_pct"));
    EXPECT_NEAR(j["write_amplification"].get<double>(), 3.2, 0.01);
    EXPECT_NEAR(j["block_cache_hit_rate_pct"].get<double>(), 85.0, 0.01);
}

// ============================================================================
// CausalGraph
// ============================================================================

TEST(CausalGraphTest, RootNodes_NoEdges_AllAreRoots) {
    CausalGraph g;
    g.nodes = {"a", "b", "c"};
    auto roots = g.rootNodes();
    EXPECT_EQ(roots.size(), 3u);
}

TEST(CausalGraphTest, RootNodes_WithEdge_OnlySourceIsRoot) {
    CausalGraph g;
    g.nodes = {"a", "b"};
    g.edges.push_back({"a", "b", 0.9, 1.0});
    auto roots = g.rootNodes();
    ASSERT_EQ(roots.size(), 1u);
    EXPECT_EQ(roots[0], "a");
}

TEST(CausalGraphTest, ToJSON_HasNodesAndEdges) {
    CausalGraph g;
    g.nodes = {"x", "y"};
    g.edges.push_back({"x", "y", 0.8, 2.0});
    json j = g.toJSON();
    EXPECT_TRUE(j.contains("nodes"));
    EXPECT_TRUE(j.contains("edges"));
    EXPECT_EQ(j["nodes"].size(), 2u);
    EXPECT_EQ(j["edges"].size(), 1u);
    EXPECT_EQ(j["edges"][0]["from"].get<std::string>(), "x");
}

// ============================================================================
// RootCauseReport
// ============================================================================

TEST(RootCauseReportTest, ToJSON_AllFields) {
    RootCauseReport r;
    r.primary_cause       = "High compaction rate";
    r.confidence          = 0.87;
    r.contributing_factors = {"write amplification +370%"};
    r.remediation_steps   = {"Increase memtable size"};
    r.metric_impacts["write_amplification"] = 370.0;

    json j = r.toJSON();
    EXPECT_EQ(j["primary_cause"].get<std::string>(), "High compaction rate");
    EXPECT_NEAR(j["confidence"].get<double>(), 0.87, 0.001);
    EXPECT_EQ(j["contributing_factors"].size(), 1u);
    EXPECT_EQ(j["remediation_steps"].size(), 1u);
    EXPECT_TRUE(j["metric_impacts"].contains("write_amplification"));
}

TEST(RootCauseReportTest, ToReport_ContainsPrimaryCauseAndConfidence) {
    RootCauseReport r;
    r.primary_cause = "Cache thrashing";
    r.confidence    = 0.75;

    std::string text = r.toReport();
    EXPECT_NE(text.find("Cache thrashing"), std::string::npos);
    EXPECT_NE(text.find("75%"), std::string::npos);
}

TEST(RootCauseReportTest, ToReport_ContainsRemediationSteps) {
    RootCauseReport r;
    r.primary_cause     = "cause";
    r.confidence        = 0.5;
    r.remediation_steps = {"Step A", "Step B"};

    std::string text = r.toReport();
    EXPECT_NE(text.find("Step A"), std::string::npos);
    EXPECT_NE(text.find("Step B"), std::string::npos);
}

// ============================================================================
// RootCauseAnalyzer – analyzeIssue
// ============================================================================

class RootCauseAnalyzerTest : public ::testing::Test {
protected:
    RootCauseAnalyzer analyzer_;
};

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_StorageAmplification_HighCompactionRate) {
    auto before = healthySnapshot();
    auto after  = healthySnapshot();
    // Simulate write amplification jumping from 3.2 to 15.1 (+372%)
    after.write_amplification      = 15.1;
    after.compaction_rate_mb_s     = 80.0;
    after.memtable_flush_rate_mb_s = 12.0;
    after.block_cache_hit_rate_pct = 45.0;
    after.avg_query_latency_ms     = 120.0;

    auto issue  = makeIssue(IssueCategory::STORAGE_AMPLIFICATION, IssueSeverity::CRITICAL);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_EQ(report.primary_cause, "High compaction rate");
    EXPECT_GT(report.confidence, 0.80);
    EXPECT_LE(report.confidence, 1.0);
    EXPECT_FALSE(report.remediation_steps.empty());
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_CacheThrashing_CacheEfficiencyCategory) {
    auto before = healthySnapshot();
    auto after  = healthySnapshot();
    // Cache hit rate drops from 85% to 30%
    after.block_cache_hit_rate_pct = 30.0;
    after.avg_query_latency_ms     = 80.0;

    auto issue  = makeIssue(IssueCategory::CACHE_EFFICIENCY, IssueSeverity::CRITICAL);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_EQ(report.primary_cause, "Cache thrashing");
    EXPECT_GT(report.confidence, 0.70);
    EXPECT_LE(report.confidence, 1.0);
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_Unknown_FallbackCause) {
    // No significant metric changes → should fall back to generic cause
    auto before = healthySnapshot();
    auto after  = healthySnapshot(); // identical snapshots

    auto issue  = makeIssue(IssueCategory::QUERY_OPTIMIZATION);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_FALSE(report.primary_cause.empty());
    EXPECT_GT(report.confidence, 0.0);
    EXPECT_LE(report.confidence, 1.0);
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_MetricImpactsPopulated) {
    auto before = healthySnapshot();
    auto after  = healthySnapshot();
    after.write_amplification = 15.1;
    after.avg_query_latency_ms = 120.0;

    auto issue  = makeIssue(IssueCategory::STORAGE_AMPLIFICATION);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_TRUE(report.metric_impacts.count("write_amplification") > 0);
    EXPECT_TRUE(report.metric_impacts.count("avg_query_latency_ms") > 0);
    EXPECT_GT(report.metric_impacts.at("write_amplification"), 0.0);
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_ContributingFactorsNotEmpty_WhenLargeDelta) {
    auto before = healthySnapshot();
    auto after  = healthySnapshot();
    after.write_amplification = 15.1;   // +372%

    auto issue  = makeIssue(IssueCategory::STORAGE_AMPLIFICATION);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_FALSE(report.contributing_factors.empty());
    // The write_amplification entry should appear in factors
    bool found = false;
    for (const auto& f : report.contributing_factors) {
        if (f.find("write_amplification") != std::string::npos) {
            found = true;
            break;
        }
    }
    EXPECT_TRUE(found);
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_ExtraMetricsIncluded) {
    auto before = healthySnapshot();
    before.extra_metrics["custom_metric"] = 100.0;
    auto after = healthySnapshot();
    after.extra_metrics["custom_metric"] = 200.0; // +100%

    auto issue  = makeIssue(IssueCategory::RESOURCE_USAGE);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_TRUE(report.metric_impacts.count("custom_metric") > 0);
    EXPECT_NEAR(report.metric_impacts.at("custom_metric"), 100.0, 0.01);
}

TEST_F(RootCauseAnalyzerTest, AnalyzeIssue_ConfidenceAlwaysInRange) {
    auto before = healthySnapshot();
    auto after  = healthySnapshot();
    after.write_amplification = 1000.0; // extreme value

    auto issue  = makeIssue(IssueCategory::STORAGE_AMPLIFICATION);
    auto report = analyzer_.analyzeIssue(issue, before, after);

    EXPECT_GE(report.confidence, 0.0);
    EXPECT_LE(report.confidence, 1.0);
}

// ============================================================================
// RootCauseAnalyzer – findCorrelations
// ============================================================================

TEST_F(RootCauseAnalyzerTest, FindCorrelations_PerfectPositiveCorrelation) {
    // a and b are perfectly correlated
    std::vector<double> vals = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    analyzer_.addTimeSeries(makeSeriesFromVec("a", vals));
    analyzer_.addTimeSeries(makeSeriesFromVec("b", vals));

    auto correlations = analyzer_.findCorrelations("a");

    ASSERT_FALSE(correlations.empty());
    EXPECT_EQ(correlations[0].metric_name, "b");
    EXPECT_NEAR(correlations[0].correlation_coefficient, 1.0, 0.01);
}

TEST_F(RootCauseAnalyzerTest, FindCorrelations_PerfectAntiCorrelation) {
    std::vector<double> vals      = {1, 2, 3, 4, 5};
    std::vector<double> inv_vals  = {5, 4, 3, 2, 1};
    analyzer_.addTimeSeries(makeSeriesFromVec("x", vals));
    analyzer_.addTimeSeries(makeSeriesFromVec("y", inv_vals));

    auto correlations = analyzer_.findCorrelations("x");

    ASSERT_FALSE(correlations.empty());
    EXPECT_EQ(correlations[0].metric_name, "y");
    EXPECT_NEAR(correlations[0].correlation_coefficient, -1.0, 0.01);
}

TEST_F(RootCauseAnalyzerTest, FindCorrelations_UncorrelatedExcluded) {
    std::vector<double> vals      = {1, 2, 3, 4, 5};
    std::vector<double> flat_vals = {3, 3, 3, 3, 3}; // constant → zero variance
    analyzer_.addTimeSeries(makeSeriesFromVec("target", vals));
    analyzer_.addTimeSeries(makeSeriesFromVec("flat", flat_vals));

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.5;
    analyzer_.setConfig(cfg);

    auto correlations = analyzer_.findCorrelations("target");
    // "flat" should NOT appear (zero variance → r = 0)
    for (const auto& c : correlations) {
        EXPECT_NE(c.metric_name, "flat");
    }
}

TEST_F(RootCauseAnalyzerTest, FindCorrelations_UnknownMetric_ReturnsEmpty) {
    auto correlations = analyzer_.findCorrelations("nonexistent_metric");
    EXPECT_TRUE(correlations.empty());
}

TEST_F(RootCauseAnalyzerTest, FindCorrelations_MaxCorrelationsHonoured) {
    // Add 20 perfectly-correlated series
    std::vector<double> vals = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    for (int i = 0; i < 20; ++i) {
        analyzer_.addTimeSeries(makeSeriesFromVec("m" + std::to_string(i), vals));
    }

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.5;
    cfg.max_correlations      = 5;
    analyzer_.setConfig(cfg);

    auto correlations = analyzer_.findCorrelations("m0");
    EXPECT_LE(correlations.size(), 5u);
}

// ============================================================================
// RootCauseAnalyzer – buildCausalGraph
// ============================================================================

TEST_F(RootCauseAnalyzerTest, BuildCausalGraph_CausalEdgeDetected) {
    // A causes B: B is a shifted copy of A (B[i] = A[i-1]).
    // Using non-monotone values so that the instantaneous correlation is < 1
    // while the lagged correlation is exactly 1, triggering edge detection.
    std::vector<double> a_vals = {1, 3, 5, 2, 8, 4, 6, 9, 7};
    std::vector<double> b_vals = {0, 1, 3, 5, 2, 8, 4, 6, 9}; // B lags A by 1

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.5;
    analyzer_.setConfig(cfg);

    auto ts_a = makeSeriesFromVec("write_amp", a_vals);
    auto ts_b = makeSeriesFromVec("latency",   b_vals);

    auto graph = analyzer_.buildCausalGraph({ts_a, ts_b});

    EXPECT_EQ(graph.nodes.size(), 2u);
    // There should be at least one edge (write_amp → latency)
    bool found_edge = false;
    for (const auto& e : graph.edges) {
        if (e.from_metric == "write_amp" && e.to_metric == "latency") {
            found_edge = true;
        }
    }
    EXPECT_TRUE(found_edge);
}

TEST_F(RootCauseAnalyzerTest, BuildCausalGraph_NoEdge_ForUncorrelatedSeries) {
    // Constant series → no meaningful correlation
    std::vector<double> flat = {3, 3, 3, 3, 3, 3, 3, 3, 3};
    std::vector<double> linear = {1, 2, 3, 4, 5, 6, 7, 8, 9};

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.9;
    analyzer_.setConfig(cfg);

    auto graph = analyzer_.buildCausalGraph({makeSeriesFromVec("flat", flat),
                                             makeSeriesFromVec("linear", linear)});
    // flat has zero variance → correlation 0 → no edge
    bool flat_edge = false;
    for (const auto& e : graph.edges) {
        if (e.from_metric == "flat" || e.to_metric == "flat") {
            flat_edge = true;
        }
    }
    EXPECT_FALSE(flat_edge);
}

TEST_F(RootCauseAnalyzerTest, BuildCausalGraph_NoEdge_WhenInstantaneousCorrelationDominates) {
    // When the instantaneous correlation is at least as strong as the lagged
    // correlation, no causal edge should be inferred (X and Y are in sync).
    // Both series are identical (perfectly correlated instantaneously);
    // the lag-1 correlation is equally strong, so |r_lag| is NOT strictly
    // greater than |r_inst|, and no edge should be added.
    std::vector<double> x = {1, 4, 2, 8, 5, 7, 3, 9, 6};
    std::vector<double> y = x; // identical → instantaneous r = 1.0

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.5;
    analyzer_.setConfig(cfg);

    auto graph = analyzer_.buildCausalGraph({makeSeriesFromVec("x", x),
                                             makeSeriesFromVec("y", y)});
    // Instantaneous correlation is 1.0; lag-1 correlation is also high but
    // NOT strictly greater, so no causal edge should appear.
    EXPECT_TRUE(graph.edges.empty());
}

TEST_F(RootCauseAnalyzerTest, BuildCausalGraph_RootNodesFromGraph) {
    std::vector<double> a = {1, 2, 3, 4, 5, 6, 7, 8, 9};
    std::vector<double> b = {0, 1, 2, 3, 4, 5, 6, 7, 8};

    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.5;
    analyzer_.setConfig(cfg);

    auto graph = analyzer_.buildCausalGraph({makeSeriesFromVec("a", a),
                                             makeSeriesFromVec("b", b)});
    auto roots = graph.rootNodes();
    EXPECT_FALSE(roots.empty());
}

TEST_F(RootCauseAnalyzerTest, BuildCausalGraph_EmptyInput_EmptyGraph) {
    auto graph = analyzer_.buildCausalGraph({});
    EXPECT_TRUE(graph.nodes.empty());
    EXPECT_TRUE(graph.edges.empty());
}

// ============================================================================
// RootCauseAnalyzer – time series registry
// ============================================================================

TEST_F(RootCauseAnalyzerTest, AddRemoveTimeSeries_RoundTrip) {
    std::vector<double> vals = {1, 2, 3, 4, 5};
    analyzer_.addTimeSeries(makeSeriesFromVec("my_metric", vals));

    // After adding, findCorrelations should treat the metric as known
    auto correlations = analyzer_.findCorrelations("my_metric");
    // No other series → empty, but no throw
    EXPECT_NO_THROW((void)correlations.size());

    analyzer_.removeTimeSeries("my_metric");

    // After removing, the metric is unknown
    correlations = analyzer_.findCorrelations("my_metric");
    EXPECT_TRUE(correlations.empty());
}

TEST_F(RootCauseAnalyzerTest, AddTimeSeries_Replacement_SameNameOverwritten) {
    analyzer_.addTimeSeries(makeSeriesFromVec("m", {1, 2, 3}));
    analyzer_.addTimeSeries(makeSeriesFromVec("m", {4, 5, 6})); // replace
    // No crash, just a replacement
    EXPECT_NO_THROW((void)analyzer_.findCorrelations("m"));
}

// ============================================================================
// RootCauseAnalyzer – config
// ============================================================================

TEST_F(RootCauseAnalyzerTest, GetConfig_DefaultValues) {
    auto cfg = analyzer_.getConfig();
    EXPECT_GT(cfg.correlation_threshold, 0.0);
    EXPECT_LE(cfg.correlation_threshold, 1.0);
    EXPECT_GT(cfg.max_correlations, 0u);
    EXPECT_GT(cfg.history_window, 0u);
}

TEST_F(RootCauseAnalyzerTest, SetConfig_UpdatesValues) {
    RootCauseAnalyzerConfig cfg;
    cfg.correlation_threshold = 0.9;
    cfg.max_correlations      = 3;
    analyzer_.setConfig(cfg);

    auto got = analyzer_.getConfig();
    EXPECT_NEAR(got.correlation_threshold, 0.9, 1e-9);
    EXPECT_EQ(got.max_correlations, 3u);
}
