#!/usr/bin/env python3
"""Phase 4-6: Convert Ollama Results -> GitHub PRs"""

import json
import subprocess
from pathlib import Path
from typing import Dict, List
import sys

class GitHubIntegration:
    """Phase 4-6: Ollama Results -> GitHub PRs + Issues"""
    
    def __init__(self):
        self.repo = "makr-code/ThemisDB"
        self.branch_base = "develop"
        
    def get_generated_modules(self) -> List[str]:
        """Find all generated Phase 3 results"""
        results_dir = Path('ai_working')
        modules = []
        for f in results_dir.glob('phase3_*_results.json'):
            module = f.name.replace('phase3_', '').replace('_results.json', '')
            modules.append(module)
        return sorted(modules)
    
    def load_phase3_results(self, module: str) -> Dict:
        """Load Phase 3 code generation results"""
        results_file = Path(f'ai_working/phase3_{module}_results.json')
        with open(results_file) as f:
            return json.load(f)
    
    def load_phase2_plan(self, module: str) -> Dict:
        """Load Phase 2 planning data"""
        plan_file = Path('ai_working/phase2_batch_results.json')
        with open(plan_file) as f:
            batch = json.load(f)
        return batch[module]
    
    def get_issue_number(self, module: str) -> int:
        """Get GitHub issue number for module (starting from #5245)"""
        modules_ordered = sorted([
            'acceleration', 'ai', 'api', 'aql', 'auth', 'base', 'cache', 'cdc', 'chaos',
            'chimera', 'connection', 'content', 'core', 'crypto', 'datawarehouse',
            'denormalization', 'executor', 'federation', 'filtering', 'flotsam', 
            'flotsam_remote', 'frontend', 'graphql', 'graphql_cache', 'graph', 
            'hash', 'index', 'io', 'libc', 'llm', 'logging', 'lru', 'lsm', 
            'messaging', 'migration', 'ml', 'monitoring', 'network', 'notification',
            'optimizer', 'orca', 'partitioning', 'performance', 'planner', 'plugin',
            'privacy', 'query', 'raft', 'rag', 'replication', 'rest', 'retention',
            'rocks', 'search', 'security', 'server', 'sharding', 'snapshot',
            'snowflake', 'sql', 'storage', 'stream', 'sys', 'telemetry', 'test',
            'transaction', 'udf', 'utils', 'vector', 'wal', 'xds', 'zonal'
        ])
        return 5245 + modules_ordered.index(module)
    
    def create_branch_name(self, module: str) -> str:
        """Create git branch name for module"""
        return f"feature/phase3-{module}-ollama"
    
    def generate_pr_body(self, module: str, results: Dict, plan: Dict) -> str:
        """Generate PR description from Phase 3 results"""
        
        issues = ', '.join([f"#{self.get_issue_number(module)}"])
        total_gaps = plan['total_gaps']
        effort = plan['effort_estimate']['total_hours']
        tasks_gen = results['tasks_generated']
        syntax_ok = results['syntax_ok']
        
        return f"""# Phase 3: Ollama Code Generation - {module.upper()}

## Summary
AI-assisted code generation for the **{module}** module using Ollama local LLM.

- **Issues:** {issues}
- **Total Gaps:** {total_gaps:,}
- **Estimated Effort:** {effort:.0f} hours
- **Tasks Generated:** {tasks_gen}
- **Syntax Valid:** {syntax_ok}/{tasks_gen}

## What Changed
- Generated production-quality C++20 code for critical gaps
- RAII patterns, exception-safety, const-correctness
- Doxygen API documentation
- Unit test stubs included

## Model & Configuration
- **Model:** {results['model']}
- **Temperature:** 0.2 (deterministic)
- **Execution Time:** {results['execution_time']:.1f}s

## Next Steps
1. Code review (Copilot + manual)
2. Unit tests + integration tests (Phase 4)
3. Build verification: `cmake --build --preset windows-release`
4. CI/CD validation

## Quality Metrics
- Syntax Valid: {syntax_ok}/{tasks_gen} tasks
- Average Code Size: {sum(r['code_length'] for r in results['results']) / len(results['results']):.0f} chars
- Documentation Coverage: {sum(1 for r in results['results'] if r['has_comments']) / len(results['results']):.0%}

**Status:** Ready for review and testing

---
Generated by ThemisDB Phase 3 Automation (Ollama)
Date: {results.get('timestamp', 'N/A')}
"""
    
    def report_summary(self):
        """Generate summary report"""
        modules = self.get_generated_modules()
        
        print("=" * 80)
        print("PHASE 3 RESULTS READY FOR GITHUB INTEGRATION")
        print("=" * 80)
        print()
        print(f"Generated Modules: {len(modules)}")
        print()
        print("Module Summary:")
        print("-" * 80)
        
        total_tasks = 0
        total_valid = 0
        
        for module in modules:
            results = self.load_phase3_results(module)
            tasks = results['tasks_generated']
            valid = results['syntax_ok']
            total_tasks += tasks
            total_valid += valid
            print(f"  {module:20} | Tasks: {tasks:2} | Valid: {valid:2}/{tasks:2} | {results['execution_time']:6.1f}s")
        
        print("-" * 80)
        print(f"  {'TOTAL':20} | Tasks: {total_tasks:2} | Valid: {total_valid:2}/{total_tasks:2}")
        print()
        print("Next Step: Convert to GitHub PRs")
        print("Command: python phase46_github_integration.py --create-prs")
        print()

if __name__ == '__main__':
    integration = GitHubIntegration()
    integration.report_summary()
