#!/bin/bash
# Phase 3 Manual Execution Script - Start HERE

echo "=========================================================================="
echo "PHASE 3: LOCAL OLLAMA -> GITHUB PRs -> CLOSE ISSUES"
echo "=========================================================================="
echo ""
echo "Status: Ready for manual, module-by-module execution"
echo "Modules ready: INDEX, ANALYTICS, STORAGE"
echo ""
echo "=========================================================================="
echo "STEP 1: Verify gh CLI is ready"
echo "=========================================================================="
echo ""
echo "$ gh auth status"
echo ""
echo "If not logged in:"
echo "$ gh auth login"
echo ""
echo "=========================================================================="
echo "STEP 2: Choose first module (INDEX recommended)"
echo "=========================================================================="
echo ""
echo "$ python issue_tracker.py index"
echo ""
echo "Output: Shows GitHub issue #5270, Phase 3 status, manual actions"
echo ""
echo "=========================================================================="
echo "STEP 3: Display detailed workflow"
echo "=========================================================================="
echo ""
echo "$ python workflow_gh_cli.py index"
echo ""
echo "Output: All gh CLI commands needed (copy-paste ready)"
echo ""
echo "=========================================================================="
echo "STEP 4: Show quick checklist (fast reference)"
echo "=========================================================================="
echo ""
echo "$ python quick_reference.py index"
echo ""
echo "Output: Numbered checklist (easy to follow)"
echo ""
echo "=========================================================================="
echo "STEP 5: Execute commands manually"
echo "=========================================================================="
echo ""
echo "Follow either workflow_gh_cli or quick_reference output"
echo ""
echo "Key commands:"
echo "  gh issue view #5270"
echo "  git checkout -b feature/phase3-index-codegen"
echo "  git commit --allow-empty -m 'Phase 3: Index generation (#5270)'"
echo "  gh pr create --draft --title 'Phase 3: Code Generation - INDEX' \\"
echo "    --base develop --body-file ai_working/pr_body_index.md"
echo "  [Save PR_NUM from output]"
echo "  gh pr comment \$PR_NUM --body 'Closes #5270'"
echo "  gh issue comment #5270 --body 'PR created...'"
echo ""
echo "=========================================================================="
echo "STEP 6: Verify PR is linked to issue"
echo "=========================================================================="
echo ""
echo "$ gh pr view \$PR_NUM"
echo "$ gh issue view #5270"
echo ""
echo "Both should show the link between PR and issue"
echo ""
echo "=========================================================================="
echo "REPEAT for other modules"
echo "=========================================================================="
echo ""
echo "Next modules (already generated):"
echo "  python quick_reference.py analytics"
echo "  python quick_reference.py storage"
echo ""
echo "Then others as needed:"
echo "  python issue_tracker.py --list  # See all 65"
echo ""
echo "=========================================================================="
echo "Ready? Start with:"
echo "=========================================================================="
echo ""
echo "$ python quick_reference.py index"
echo ""
