/**
 * @file operator_remediation_engine.h
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.1
 * @note Maturity: 🟡 BETA (Phase 2 Observability Expansion)
 * @note Score: 0/100 (implementation in progress)
 * @note Status: Automated incident diagnostics and remediation hints
 * @note This block is auto-generated and will be overwritten.
 */

#pragma once

#include <string>
#include <vector>
#include <map>
#include <memory>
#include <chrono>
#include <cstdint>
#include <functional>

namespace themis {
namespace observability {

/**
 * @brief Severity level of a remediation hint.
 */
enum class RemediationSeverity {
    INFO,       ///< Informational hint, no action required
    WARNING,    ///< Warning condition, human review recommended
    CRITICAL,   ///< Critical issue requiring immediate action
};

/**
 * @brief Category of observability problem.
 */
enum class ProblemCategory {
    CARDINALITY_EXPLOSION,      ///< Metric cardinality exceeding limits
    EXPORTER_UNAVAILABLE,       ///< Tracing/metrics exporter unreachable
    HIGH_LATENCY,               ///< Observability operations taking excessive time
    MEMORY_PRESSURE,            ///< High memory usage in observability pipeline
    QUEUE_OVERFLOW,             ///< Telemetry queue overflow or backpressure
    SPAN_LOSS,                  ///< Traces being dropped due to overload
    METRIC_LOSS,                ///< Metrics being dropped or rejected
    CLOCK_SKEW,                 ///< Time synchronization issues detected
    BACKEND_DEGRADATION,        ///< Exporter or backend in degraded state
    CONFIGURATION_ERROR,        ///< Observability configuration issue
    UNKNOWN,                    ///< Unknown or unclassified problem
};

/**
 * @brief Remediation action suggestion.
 *
 * Represents a single actionable remediation step recommended to resolve
 * or mitigate an observability problem.
 */
struct RemediationAction {
    /// Human-readable name of the action.
    std::string action_name;

    /// Detailed description of what to do.
    std::string description;

    /// Priority level for executing this action (1 = highest).
    std::uint32_t priority{1};

    /// Estimated time to execute this action (in seconds).
    std::uint32_t estimated_duration_seconds{0};

    /// Whether this action is safe to execute automatically.
    bool is_safe_to_automate{false};

    /// Optional shell command or API call for automation.
    std::string automation_command;

    /// Expected outcome if action is successful.
    std::string expected_outcome;
};

/**
 * @brief Remediation hint containing problem diagnosis and suggestions.
 *
 * A RemediationHint is generated by the OperatorRemediationEngine when
 * it detects an observability problem. It includes:
 * - Problem category and diagnosis
 * - Severity level and confidence
 * - Actionable remediation suggestions
 * - Links to documentation and examples
 */
class RemediationHint {
public:
    /**
     * @brief Get the problem category.
     */
    ProblemCategory problemCategory() const { return category_; }

    /**
     * @brief Get human-readable problem title.
     */
    const std::string& problemTitle() const { return title_; }

    /**
     * @brief Get detailed problem description.
     */
    const std::string& problemDescription() const { return description_; }

    /**
     * @brief Get severity level.
     */
    RemediationSeverity severity() const { return severity_; }

    /**
     * @brief Get confidence in the diagnosis (0.0 - 1.0).
     */
    double confidenceScore() const { return confidence_score_; }

    /**
     * @brief Get timestamp when hint was generated.
     */
    std::chrono::system_clock::time_point generatedAt() const { return generated_at_; }

    /**
     * @brief Get the time window over which the problem was detected.
     */
    std::chrono::seconds detectionWindow() const { return detection_window_; }

    /**
     * @brief Get list of recommended remediation actions.
     */
    const std::vector<RemediationAction>& suggestedActions() const { return actions_; }

    /**
     * @brief Get reference metrics that support the diagnosis.
     */
    const std::map<std::string, double>& diagnosticMetrics() const { return metrics_; }

    /**
     * @brief Get link to documentation or runbook.
     */
    const std::string& documentationLink() const { return doc_link_; }

    /**
     * @brief Get link to example of the problem or solution.
     */
    const std::string& exampleLink() const { return example_link_; }

    /**
     * @brief Get unique hint ID for tracking and deduplication.
     */
    const std::string& hintId() const { return hint_id_; }

    /**
     * @brief Get tags for categorization and filtering.
     */
    const std::vector<std::string>& tags() const { return tags_; }

    // Internal members (used by OperatorRemediationEngine implementation)
    ProblemCategory category_;
    std::string title_;
    std::string description_;
    RemediationSeverity severity_;
    double confidence_score_{0.0};
    std::chrono::system_clock::time_point generated_at_;
    std::chrono::seconds detection_window_{0};
    std::vector<RemediationAction> actions_;
    std::map<std::string, double> metrics_;
    std::string doc_link_;
    std::string example_link_;
    std::string hint_id_;
    std::vector<std::string> tags_;
};

/**
 * @brief Listener interface for remediation hint events.
 *
 * Implementations receive notifications when the OperatorRemediationEngine
 * generates new hints or closes existing ones.
 */
class IRemediationHintListener {
public:
    /**
     * @brief Called when a new remediation hint is generated.
     * @param hint The generated hint.
     */
    virtual void onNewHint(const std::shared_ptr<RemediationHint>& hint) = 0;

    /**
     * @brief Called when a previously-issued hint is resolved.
     * @param hint_id The ID of the resolved hint.
     */
    virtual void onHintResolved(const std::string& hint_id) = 0;

    /**
     * @brief Virtual destructor for safe polymorphic deletion.
     */
    virtual ~IRemediationHintListener() = default;
};

/**
 * @brief Pattern matcher for detecting observability problems.
 *
 * Custom pattern implementations can be registered to extend the
 * remediation engine with domain-specific problem detection.
 */
class RemediationPattern {
public:
    /**
     * @brief Check if the pattern matches the current system state.
     *
     * @param metrics Current metric values and system state.
     * @return Remediation hint if pattern matches, nullptr otherwise.
     *
     * @note Implementations must be thread-safe and complete quickly
     *       (target: < 10ms).
     */
    virtual std::shared_ptr<RemediationHint> match(
        const std::map<std::string, double>& metrics) = 0;

    /**
     * @brief Get the pattern name.
     */
    virtual std::string patternName() const = 0;

    /**
     * @brief Get the problem category this pattern detects.
     */
    virtual ProblemCategory problemCategory() const = 0;

    /**
     * @brief Virtual destructor for safe polymorphic deletion.
     */
    virtual ~RemediationPattern() = default;
};

/**
 * @brief Operator remediation engine for automated incident diagnostics.
 *
 * The OperatorRemediationEngine provides utilities for:
 * - Detecting common observability problems from metric patterns
 * - Generating actionable remediation hints for operators
 * - Tracking and deduplicating hints over time
 * - Providing documentation links and runbook references
 * - Supporting custom pattern matching for domain-specific problems
 *
 * ## Built-in Patterns
 *
 * - Cardinality explosion detection and label-dropping suggestions
 * - Exporter connectivity monitoring with fallback recommendations
 * - Latency anomaly detection with batch-size/flush-interval tuning hints
 * - Memory pressure detection with retention policy adjustment suggestions
 * - Queue overflow handling with backpressure tuning recommendations
 * - Span loss monitoring with sampling rate adjustment hints
 *
 * ## Integration Pattern
 *
 * ```cpp
 * // Create remediation engine with built-in patterns
 * auto engine = std::make_unique<OperatorRemediationEngine>();
 *
 * // Register a listener for hints
 * class MyHintListener : public IRemediationHintListener {
 *     void onNewHint(const std::shared_ptr<RemediationHint>& hint) override {
 *         logger.warn("Observability issue: {}", hint->problemTitle());
 *         for (const auto& action : hint->suggestedActions()) {
 *             logger.info("  -> {}", action.description);
 *         }
 *     }
 *     void onHintResolved(const std::string& hint_id) override {
 *         logger.info("Issue resolved: {}", hint_id);
 *     }
 * };
 * auto listener = std::make_shared<MyHintListener>();
 * engine->addListener(listener);
 *
 * // Periodically analyze metrics and generate hints
 * auto metrics = collectCurrentMetrics();
 * auto hints = engine->analyzeAndGenerateHints(metrics);
 * for (const auto& hint : hints) {
 *     logger.warn("Hint [{}]: {}", hint->hintId(), hint->problemTitle());
 * }
 * ```
 *
 * ## Error Codes (Observability Phase 2 Extension)
 *
 * - ORE_PATTERN_MATCH_ERROR = 26
 * - ORE_INVALID_METRIC_DATA = 27
 * - ORE_LISTENER_NOTIFICATION_FAILED = 28
 * - ORE_DUPLICATE_PATTERN = 29
 * - ORE_INTERNAL_ERROR = 30
 */
class OperatorRemediationEngine {
public:
    /**
     * @brief Construct a remediation engine with built-in patterns.
     */
    OperatorRemediationEngine();

    /**
     * @brief Virtual destructor for safe polymorphic deletion.
     */
    virtual ~OperatorRemediationEngine() = default;

    /**
     * @brief Add a listener for remediation hint events.
     *
     * @param listener Listener implementation (takes weak reference).
     * @return true on success, false if listener is null.
     *
     * @note This function is thread-safe.
     */
    virtual bool addListener(const std::shared_ptr<IRemediationHintListener>& listener) = 0;

    /**
     * @brief Remove a listener.
     *
     * @param listener Listener to remove.
     * @return true if listener was found and removed, false otherwise.
     *
     * @note This function is thread-safe.
     */
    virtual bool removeListener(const std::shared_ptr<IRemediationHintListener>& listener) = 0;

    /**
     * @brief Register a custom remediation pattern.
     *
     * @param pattern Pattern implementation (takes ownership).
     * @return true on success, false if pattern name already exists.
     *
     * @note This function is thread-safe.
     */
    virtual bool registerPattern(std::unique_ptr<RemediationPattern> pattern) = 0;

    /**
     * @brief Unregister a pattern by name.
     *
     * @param pattern_name Name of pattern to remove.
     * @return true if pattern was found and removed, false otherwise.
     *
     * @note This function is thread-safe.
     */
    virtual bool unregisterPattern(const std::string& pattern_name) = 0;

    /**
     * @brief Analyze current system metrics and generate remediation hints.
     *
     * Runs all registered patterns against the supplied metrics and generates
     * hints for any patterns that match. Duplicate hints (same problem detected
     * multiple times) are deduplicated based on configurable time window.
     *
     * @param metrics Map of metric name -> current value.
     * @return Vector of newly-generated hints (empty if no problems detected).
     *
     * @note This function is thread-safe.
     */
    virtual std::vector<std::shared_ptr<RemediationHint>> analyzeAndGenerateHints(
        const std::map<std::string, double>& metrics) = 0;

    /**
     * @brief Get list of currently-active hints.
     *
     * @return Vector of hints that have been generated and not yet resolved.
     *
     * @note This function is thread-safe but results are snapshots and
     *       may become stale immediately after returning.
     */
    virtual std::vector<std::shared_ptr<RemediationHint>> getActiveHints() = 0;

    /**
     * @brief Get a hint by ID.
     *
     * @param hint_id Unique hint identifier.
     * @return The hint if found, nullptr otherwise.
     *
     * @note This function is thread-safe.
     */
    virtual std::shared_ptr<RemediationHint> getHintById(const std::string& hint_id) = 0;

    /**
     * @brief Mark a hint as resolved/dismissed.
     *
     * @param hint_id ID of hint to resolve.
     * @return true if hint was found and marked resolved, false otherwise.
     *
     * @note This function is thread-safe.
     */
    virtual bool resolveHint(const std::string& hint_id) = 0;

    /**
     * @brief Get hints filtered by category.
     *
     * @param category Problem category to filter by.
     * @return Vector of hints matching the category.
     *
     * @note This function is thread-safe but results are snapshots and
     *       may become stale immediately after returning.
     */
    virtual std::vector<std::shared_ptr<RemediationHint>> getHintsByCategory(
        ProblemCategory category) = 0;

    /**
     * @brief Get hints filtered by severity level.
     *
     * @param severity Minimum severity level to return.
     * @return Vector of hints at or above the specified severity.
     *
     * @note This function is thread-safe but results are snapshots and
     *       may become stale immediately after returning.
     */
    virtual std::vector<std::shared_ptr<RemediationHint>> getHintsBySeverity(
        RemediationSeverity severity) = 0;

    /**
     * @brief Enable/disable automatic hint generation.
     *
     * When disabled, analyzeAndGenerateHints() returns empty vector.
     *
     * @param enabled true to enable hint generation, false to disable.
     *
     * @note This function is thread-safe.
     */
    virtual void setHintGenerationEnabled(bool enabled) = 0;

    /**
     * @brief Check whether hint generation is enabled.
     *
     * @return true if hint generation is enabled, false otherwise.
     *
     * @note This function is thread-safe.
     */
    virtual bool isHintGenerationEnabled() = 0;

    /**
     * @brief Set the deduplication time window for hints.
     *
     * Hints with the same category and title generated within this time window
     * are considered duplicates and only the first is emitted.
     *
     * @param window Time window duration.
     *
     * @note This function is thread-safe.
     */
    virtual void setDeduplicationWindow(std::chrono::seconds window) = 0;

    /**
     * @brief Get the current deduplication time window.
     *
     * @return Current deduplication window duration.
     *
     * @note This function is thread-safe.
     */
    virtual std::chrono::seconds getDeduplicationWindow() = 0;

    /**
     * @brief Clear all hint history.
     *
     * Removes all generated hints and resets deduplication tracking.
     *
     * @note This function is thread-safe.
     */
    virtual void clearAllHints() = 0;

    /**
     * @brief Get statistics about hint generation.
     *
     * @return Map with keys: "total_hints_generated", "active_hints", "hints_by_severity_*", etc.
     *
     * @note This function is thread-safe but results are snapshots and
     *       may become stale immediately after returning.
     */
    virtual std::map<std::string, double> getStatistics() = 0;
};

} // namespace observability
} // namespace themis
