/*
 * ThemisDB Kubernetes Operator – DeepCopy methods
 *
 * DeepCopy methods implement the runtime.Object interface required by the
 * controller-runtime scheme.  In production projects these are generated by
 * controller-gen; here they are hand-written to keep the codebase
 * self-contained without the code-generator toolchain.
 *
 * Copyright (c) 2025 VCC-URN Project
 * SPDX-License-Identifier: Apache-2.0
 */

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another ThemisDB object.
func (in *ThemisDB) DeepCopyInto(out *ThemisDB) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of this ThemisDB.
func (in *ThemisDB) DeepCopy() *ThemisDB {
	if in == nil {
		return nil
	}
	out := new(ThemisDB)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ThemisDB) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another ThemisDBList object.
func (in *ThemisDBList) DeepCopyInto(out *ThemisDBList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThemisDB, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of this ThemisDBList.
func (in *ThemisDBList) DeepCopy() *ThemisDBList {
	if in == nil {
		return nil
	}
	out := new(ThemisDBList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ThemisDBList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── Spec DeepCopy ─────────────────────────────────────────────────────────

func (in *ThemisDBSpec) DeepCopyInto(out *ThemisDBSpec) {
	*out = *in
	out.Storage = in.Storage
	if in.Resources.Requests != nil {
		out.Resources.Requests = make(map[string]string, len(in.Resources.Requests))
		for k, v := range in.Resources.Requests {
			out.Resources.Requests[k] = v
		}
	}
	if in.Resources.Limits != nil {
		out.Resources.Limits = make(map[string]string, len(in.Resources.Limits))
		for k, v := range in.Resources.Limits {
			out.Resources.Limits[k] = v
		}
	}
	in.Replication.DeepCopyInto(&out.Replication)
	out.Sharding = in.Sharding
	out.Security = in.Security
	out.Monitoring = in.Monitoring
	out.Backup = in.Backup
}

func (in *ReplicationConfig) DeepCopyInto(out *ReplicationConfig) {
	*out = *in
	out.LeaderElection = in.LeaderElection
	out.Failover = in.Failover
	out.LagThresholds = in.LagThresholds
	out.WAL = in.WAL
	in.TopologyAware.DeepCopyInto(&out.TopologyAware)
}

func (in *TopologyAwareConfig) DeepCopyInto(out *TopologyAwareConfig) {
	*out = *in
	if in.PreferredDatacenters != nil {
		out.PreferredDatacenters = make([]string, len(in.PreferredDatacenters))
		copy(out.PreferredDatacenters, in.PreferredDatacenters)
	}
}

// ── Status DeepCopy ───────────────────────────────────────────────────────

func (in *ThemisDBStatus) DeepCopyInto(out *ThemisDBStatus) {
	*out = *in
	in.ReplicationTopology.DeepCopyInto(&out.ReplicationTopology)
	if in.Conditions != nil {
		out.Conditions = make([]ThemisDBCondition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *ThemisDBCondition) DeepCopyInto(out *ThemisDBCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

func (in *ReplicationTopologyStatus) DeepCopyInto(out *ReplicationTopologyStatus) {
	*out = *in
	if in.LastFailoverTime != nil {
		t := *in.LastFailoverTime
		out.LastFailoverTime = &t
	}
	if in.InSyncReplicas != nil {
		out.InSyncReplicas = make([]string, len(in.InSyncReplicas))
		copy(out.InSyncReplicas, in.InSyncReplicas)
	}
	if in.LaggingReplicas != nil {
		out.LaggingReplicas = make([]string, len(in.LaggingReplicas))
		copy(out.LaggingReplicas, in.LaggingReplicas)
	}
	if in.ReplicaHealth != nil {
		out.ReplicaHealth = make([]ReplicaHealthStatus, len(in.ReplicaHealth))
		for i := range in.ReplicaHealth {
			in.ReplicaHealth[i].DeepCopyInto(&out.ReplicaHealth[i])
		}
	}
}

func (in *ReplicaHealthStatus) DeepCopyInto(out *ReplicaHealthStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		t := *in.LastHeartbeat
		out.LastHeartbeat = &t
	}
}
