// Unit tests for the web-based import wizard HTML generated by
// buildImportWizardHtml() (served at GET /import/wizard).
//
// buildImportWizardHtml() has no external dependencies, so these tests
// compile and run without needing httplib, importer headers, or a live
// HTTP server.  The approach mirrors the self-contained pattern used in
// other importer test files.

#include <gtest/gtest.h>
#include <string>
#include "server/import_wizard_builder.h"

// ===========================================================================
// Fixture
// ===========================================================================
class ImportWizardHtmlTest : public ::testing::Test {
protected:
    std::string html_ = {};
    void SetUp() override {
        html_ = themis::server::buildImportWizardHtml();
    }
};

// ===========================================================================
// Tests
// ===========================================================================

TEST_F(ImportWizardHtmlTest, HtmlIsNonEmpty) {
    EXPECT_GT(html_.size(), 1000u);
}

TEST_F(ImportWizardHtmlTest, ContainsDoctypeDeclaration) {
    EXPECT_NE(html_.find("<!DOCTYPE html>"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsTitleWithImportWizard) {
    EXPECT_NE(html_.find("<title>"), std::string::npos);
    EXPECT_NE(html_.find("Import Wizard"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, HasValidOpenCloseHtmlBodyTags) {
    EXPECT_NE(html_.find("<html"), std::string::npos);
    EXPECT_NE(html_.find("</html>"), std::string::npos);
    EXPECT_NE(html_.find("<body"), std::string::npos);
    EXPECT_NE(html_.find("</body>"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsFiveStepperTabs) {
    size_t count = 0, pos = 0;
    while ((pos = html_.find("class=\"step", pos)) != std::string::npos) {
        ++count; pos += 10;
    }
    EXPECT_GE(count, 5u) << "Expected at least 5 stepper tab elements";
}

TEST_F(ImportWizardHtmlTest, ContainsSourceSelectionPanel) {
    EXPECT_NE(html_.find("panel-1"), std::string::npos);
    EXPECT_NE(html_.find("source-card"), std::string::npos);
    EXPECT_NE(html_.find("postgresql"), std::string::npos);
    EXPECT_NE(html_.find("s3"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsConnectionPanel) {
    EXPECT_NE(html_.find("panel-2"), std::string::npos);
    EXPECT_NE(html_.find("pg-path"), std::string::npos);
    EXPECT_NE(html_.find("s3-path"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsOptionsPanel) {
    EXPECT_NE(html_.find("panel-3"), std::string::npos);
    EXPECT_NE(html_.find("opt-namespace"), std::string::npos);
    EXPECT_NE(html_.find("opt-batch"), std::string::npos);
    EXPECT_NE(html_.find("opt-dryrun"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsConflictStrategyOptions) {
    EXPECT_NE(html_.find("opt-conflict"), std::string::npos);
    EXPECT_NE(html_.find("Overwrite"), std::string::npos);
    EXPECT_NE(html_.find("Skip"), std::string::npos);
    EXPECT_NE(html_.find("Merge"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsReviewPanel) {
    EXPECT_NE(html_.find("panel-4"), std::string::npos);
    EXPECT_NE(html_.find("review-summary"), std::string::npos);
    EXPECT_NE(html_.find("btn-start"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsProgressPanel) {
    EXPECT_NE(html_.find("panel-5"), std::string::npos);
    EXPECT_NE(html_.find("prog-bar"), std::string::npos);
    EXPECT_NE(html_.find("btn-cancel"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsJobListPanel) {
    EXPECT_NE(html_.find("jobs-list"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ReferencesImportApiEndpoints) {
    EXPECT_NE(html_.find("/api/v1/import/postgresql"), std::string::npos);
    EXPECT_NE(html_.find("/api/v1/import/s3"), std::string::npos);
    EXPECT_NE(html_.find("/api/v1/import/jobs"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsRequiredJavaScriptFunctions) {
    EXPECT_NE(html_.find("function selectSource"), std::string::npos);
    EXPECT_NE(html_.find("function goStep"), std::string::npos);
    EXPECT_NE(html_.find("function startImport"), std::string::npos);
    EXPECT_NE(html_.find("function pollProgress"), std::string::npos);
    EXPECT_NE(html_.find("function cancelImport"), std::string::npos);
    EXPECT_NE(html_.find("function resetWizard"), std::string::npos);
    EXPECT_NE(html_.find("function loadJobs"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsEscHtmlForXssPrevention) {
    // escHtml must sanitize user-supplied paths before inserting into innerHTML
    EXPECT_NE(html_.find("function escHtml"), std::string::npos);
    EXPECT_NE(html_.find("replace(/&/g"), std::string::npos);
    EXPECT_NE(html_.find("replace(/</g"), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, IsIdempotent) {
    // Multiple calls must return identical HTML (no internal state mutation)
    auto html2 = themis::server::buildImportWizardHtml();
    EXPECT_EQ(html_, html2);
}

TEST_F(ImportWizardHtmlTest, ContainsCharsetUtf8MetaTag) {
    EXPECT_NE(html_.find("charset=\"UTF-8\""), std::string::npos);
}

TEST_F(ImportWizardHtmlTest, ContainsViewportMetaTag) {
    EXPECT_NE(html_.find("viewport"), std::string::npos);
}
