/**
 * @file adapter_consistency_checker.cpp
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.47
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=4; TODO=1, Stub=2, Unimpl=0, Mock=1, Sim=0, Debt=0, C=0, H=0, M=3, L=0
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


#include "llm/lora_framework/adapter_consistency_checker.h"
#include <spdlog/spdlog.h>
#include <openssl/sha.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <iomanip>
#include <sstream>
#include <cstring>

namespace themis {
namespace llm {
namespace lora {

/**
 * @brief Implementation class
 */
class AdapterConsistencyChecker::Impl {
public:
    explicit Impl(const Config& config) : config_(config) {
        spdlog::info("AdapterConsistencyChecker initialized:");
        spdlog::info("  Checksums: {}", config_.enable_checksums);
        spdlog::info("  Signatures: {}", config_.enable_signatures);
        spdlog::info("  Strict mode: {}", config_.strict_mode);
    }
    
    std::string calculateChecksum(const std::vector<uint8_t>& data) const {
        if (!config_.enable_checksums) {
            return "";
        }
        
        unsigned char hash[SHA256_DIGEST_LENGTH];
        SHA256(data.data(), data.size(), hash);
        
        std::stringstream ss;
        for (int i = 0; i < SHA256_DIGEST_LENGTH; i++) {
            ss << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(hash[i]);
        }
        return ss.str();
    }
    
    bool verifyChecksum(const std::vector<uint8_t>& data, const std::string& expected) const {
        if (!config_.enable_checksums || expected.empty()) {
            return true;  // Skip if disabled or no expected checksum
        }
        
        std::string actual = calculateChecksum(data);
        return actual == expected;
    }
    
    std::string generateSignature(const std::vector<uint8_t>& data, const std::string& /*private_key*/) const {
        if (!config_.enable_signatures) {
            return "";
        }
        
        // For simplicity, use checksum as signature (in production, use real crypto)
        // This is a placeholder - real implementation would use Ed25519/ECDSA
        return calculateChecksum(data);
    }
    
    bool verifySignature(
        const std::vector<uint8_t>& data,
        const std::string& signature,
        const std::string& public_key
    ) const {
        if (!config_.enable_signatures || signature.empty()) {
            return true;  // Skip if disabled or no signature
        }

        // When a PEM public key is provided, use Ed25519 / RSA EVP verification.
        if (!public_key.empty()) {
            BIO* bio = BIO_new_mem_buf(public_key.data(), static_cast<int>(public_key.size()));
            if (!bio) return false;
            EVP_PKEY* pkey = PEM_read_bio_PUBKEY(bio, nullptr, nullptr, nullptr);
            BIO_free(bio);
            if (!pkey) return false;

            EVP_MD_CTX* mdctx = EVP_MD_CTX_new();
            bool ok = false;
            if (mdctx) {
                if (EVP_DigestVerifyInit(mdctx, nullptr, nullptr, nullptr, pkey) == 1) {
                    int rc = EVP_DigestVerify(
                        mdctx,
                        reinterpret_cast<const unsigned char*>(signature.data()),
                        signature.size(),
                        data.data(),
                        data.size());
                    ok = (rc == 1);
                }
                EVP_MD_CTX_free(mdctx);
            }
            EVP_PKEY_free(pkey);
            return ok;
        }

        // No public key: fall back to comparing SHA-256 checksums (internal
        // path used by checkAdapter when metadata.signature was generated by
        // generateSignature() with an empty private key).
        const std::string computed = generateSignature(data, "");
        return computed == signature;
    }
    
    ConsistencyCheckResult checkAdapter(
        const std::string& adapter_id,
        const std::vector<uint8_t>& data,
        const AdapterMetadata& metadata
    ) const {
        ConsistencyCheckResult result;
        
        // Calculate checksum
        if (config_.enable_checksums) {
            result.checksum = calculateChecksum(data);
            
            // Verify against stored checksum if available
            if (!metadata.checksum.empty()) {
                result.is_valid = verifyChecksum(data, metadata.checksum);
                if (!result.is_valid) {
                    result.error_message = "Checksum mismatch";
                    spdlog::warn("Checksum mismatch for adapter {}", adapter_id);
                }
            } else {
                result.is_valid = true;
            }
        } else {
            result.is_valid = true;
        }
        
        // Verify signature
        if (config_.enable_signatures && !metadata.signature.empty()) {
            result.signature = metadata.signature;
            result.signature_valid = verifySignature(data, metadata.signature, "");
            
            if (!result.signature_valid) {
                result.is_valid = false;
                result.error_message = "Invalid signature";
                spdlog::warn("Invalid signature for adapter {}", adapter_id);
            }
        } else {
            result.signature_valid = true;
        }
        
        // Extract version info
        result.version = metadata.version;
        result.timestamp = std::chrono::duration_cast<std::chrono::nanoseconds>(
            metadata.updated_at.time_since_epoch()
        ).count();
        
        return result;
    }
    
    int compareVersions(
        const ConsistencyCheckResult& local,
        const ConsistencyCheckResult& remote
    ) const {
        // First compare version strings lexicographically
        if (local.version < remote.version) {
            return -1;
        } else if (local.version > remote.version) {
            return 1;
        }
        
        // If versions are equal, compare timestamps
        if (local.timestamp < remote.timestamp) {
            return -1;
        } else if (local.timestamp > remote.timestamp) {
            return 1;
        }
        
        return 0;  // Identical
    }
    
    ConsistencyCheckResult resolveConflict(
        const ConsistencyCheckResult& local,
        const ConsistencyCheckResult& remote
    ) const {
        int cmp = compareVersions(local, remote);
        
        if (cmp >= 0) {
            spdlog::info("Conflict resolved: keeping local version {} (timestamp: {})",
                        local.version, local.timestamp);
            return local;
        } else {
            spdlog::info("Conflict resolved: accepting remote version {} (timestamp: {})",
                        remote.version, remote.timestamp);
            return remote;
        }
    }
    
private:
    Config config_;
};

// Constructor/Destructor
AdapterConsistencyChecker::AdapterConsistencyChecker(const Config& config)
    : impl_(std::make_unique<Impl>(config)) {}

AdapterConsistencyChecker::AdapterConsistencyChecker()
    : impl_(std::make_unique<Impl>(Config{})) {}

AdapterConsistencyChecker::~AdapterConsistencyChecker() = default;

// Public methods
std::string AdapterConsistencyChecker::calculateChecksum(const std::vector<uint8_t>& data) const {
    return impl_->calculateChecksum(data);
}

bool AdapterConsistencyChecker::verifyChecksum(
    const std::vector<uint8_t>& data,
    const std::string& expected_checksum
) const {
    return impl_->verifyChecksum(data, expected_checksum);
}

std::string AdapterConsistencyChecker::generateSignature(
    const std::vector<uint8_t>& data,
    const std::string& private_key
) const {
    return impl_->generateSignature(data, private_key);
}

bool AdapterConsistencyChecker::verifySignature(
    const std::vector<uint8_t>& data,
    const std::string& signature,
    const std::string& public_key
) const {
    return impl_->verifySignature(data, signature, public_key);
}

ConsistencyCheckResult AdapterConsistencyChecker::checkAdapter(
    const std::string& adapter_id,
    const std::vector<uint8_t>& data,
    const AdapterMetadata& metadata
) const {
    return impl_->checkAdapter(adapter_id, data, metadata);
}

int AdapterConsistencyChecker::compareVersions(
    const ConsistencyCheckResult& local_result,
    const ConsistencyCheckResult& remote_result
) const {
    return impl_->compareVersions(local_result, remote_result);
}

ConsistencyCheckResult AdapterConsistencyChecker::resolveConflict(
    const ConsistencyCheckResult& local_result,
    const ConsistencyCheckResult& remote_result
) const {
    return impl_->resolveConflict(local_result, remote_result);
}

} // namespace lora
} // namespace llm
} // namespace themis

