/**
 * @file build_verifier.cpp
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.5
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=3; TODO=1, Stub=1, Unimpl=0, Mock=1, Sim=0, Debt=0, C=0, H=0, M=2, L=0
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


#include "updates/build_verifier.h"
#include "utils/logger.h"

#define LOG_ERROR(...) SPDLOG_ERROR(__VA_ARGS__)
#define LOG_INFO(...)  SPDLOG_INFO(__VA_ARGS__)
#define LOG_WARN(...)  SPDLOG_WARN(__VA_ARGS__)
#define LOG_DEBUG(...) SPDLOG_DEBUG(__VA_ARGS__)

// Generated by cmake/BuildInfo.cmake into ${CMAKE_BINARY_DIR}/include/
#include "updates/build_info.h"

// OpenSSL Ed25519 support (EVP_PKEY_ED25519 requires OpenSSL 1.1.1+)
#if __has_include(<openssl/evp.h>)
#  include <openssl/evp.h>
#  include <openssl/err.h>
#  define THEMIS_HAVE_OPENSSL 1
#endif

#include <array>
#include <cstring>
#include <mutex>
#include <optional>
#include <string>
#include <vector>

namespace themis {
namespace updates {

// ---------------------------------------------------------------------------
// Internal Base64 decoder (RFC 4648, standard alphabet, no line wrapping)
// ---------------------------------------------------------------------------

namespace {

static const int8_t kBase64Table[256] = {
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,  // 0–15
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,  // 16–31
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,62,-1,-1,-1,63,  // 32–47  (+, /)
    52,53,54,55,56,57,58,59,60,61,-1,-1,-1, 0,-1,-1,  // 48–63  (0-9, =)
    -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,  // 64–79  (A-O)
    15,16,17,18,19,20,21,22,23,24,25,-1,-1,-1,-1,-1,  // 80–95  (P-Z)
    -1,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,  // 96–111 (a-o)
    41,42,43,44,45,46,47,48,49,50,51,-1,-1,-1,-1,-1,  // 112–127(p-z)
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,  // 128–255
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
    -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
};

/// Decode a standard Base64 string to raw bytes.
/// Returns empty vector on invalid input.
static std::vector<uint8_t> base64Decode(const std::string& encoded) {
    std::vector<uint8_t> out;
    out.reserve((encoded.size() / 4) * 3 + 3);

    int bits   = 0;
    int val    = 0;
    int pad    = 0;

    for (unsigned char c : encoded) {
        if (c == '=') { ++pad; continue; }
        if (c == '\n' || c == '\r' || c == ' ') { continue; }
        const int b = kBase64Table[c];
        if (b < 0) { return {}; }  // invalid character
        val  = (val << 6) | b;
        bits += 6;
        if (bits >= 8) {
            bits -= 8;
            out.push_back(static_cast<uint8_t>((val >> bits) & 0xFF));
        }
    }

    // Trim bytes added due to padding.
    if (pad > 0 && pad <= 2 && out.size() >= static_cast<size_t>(pad)) {
        out.resize(out.size() - static_cast<size_t>(pad - 1));
    }

    return out;
}

// ---------------------------------------------------------------------------
// Ed25519 verification via OpenSSL EVP
// ---------------------------------------------------------------------------

#ifdef THEMIS_HAVE_OPENSSL

/// Verify an Ed25519 signature.
/// @param pub_key_raw  32-byte raw Ed25519 public key.
/// @param message      Message bytes.
/// @param sig_raw      64-byte raw Ed25519 signature.
/// @return true iff signature is valid.
static bool ed25519Verify(const std::vector<uint8_t>& pub_key_raw,
                          const std::string&           message,
                          const std::vector<uint8_t>& sig_raw) {
    if (pub_key_raw.size() != 32 || sig_raw.size() != 64) {
        return false;
    }

    EVP_PKEY* pkey = EVP_PKEY_new_raw_public_key(
        EVP_PKEY_ED25519, nullptr,
        pub_key_raw.data(), pub_key_raw.size());
    if (!pkey) {
        LOG_ERROR("BuildVerifier: EVP_PKEY_new_raw_public_key failed: {}",
                  ERR_reason_error_string(ERR_get_error()));
        return false;
    }

    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    if (!ctx) {
        EVP_PKEY_free(pkey);
        return false;
    }

    bool ok = false;
    if (EVP_DigestVerifyInit(ctx, nullptr, nullptr, nullptr, pkey) == 1) {
        const int rc = EVP_DigestVerify(
            ctx,
            sig_raw.data(), sig_raw.size(),
            reinterpret_cast<const unsigned char*>(message.data()),
            message.size());
        ok = (rc == 1);
        if (rc < 0) {
            LOG_WARN("BuildVerifier: EVP_DigestVerify error: {}",
                     ERR_reason_error_string(ERR_get_error()));
        }
    }

    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(pkey);
    return ok;
}

#endif // THEMIS_HAVE_OPENSSL

// ---------------------------------------------------------------------------
// Cached verification result
// ---------------------------------------------------------------------------

static BuildVerificationResult g_cached_result;
static std::once_flag          g_once;

static BuildVerificationResult doVerify() {
    BuildVerificationResult res;
    res.channel  = THEMIS_BUILD_CHANNEL;
    res.build_id = THEMIS_BUILD_ID;

    // Community builds never have a signature – skip verification.
    const std::string sig_b64 = THEMIS_BUILD_SIG;
    if (sig_b64.empty()) {
        res.verified       = false;
        res.failure_reason = "No signature embedded (community build)";
        LOG_DEBUG("BuildVerifier: community build – no signature");
        return res;
    }

#ifndef THEMIS_HAVE_OPENSSL
    res.verified       = false;
    res.failure_reason = "OpenSSL not available at compile time";
    LOG_WARN("BuildVerifier: cannot verify signature – OpenSSL not compiled in");
    return res;
#else
    // Reconstruct the manifest string that was signed:
    //   "<channel>|<version>|<build_id>|<timestamp>"
    const std::string manifest =
        std::string(THEMIS_BUILD_CHANNEL) + "|" +
        std::string(THEMIS_VERSION_STRING) + "|" +
        std::string(THEMIS_BUILD_ID)       + "|" +
        std::string(THEMIS_BUILD_TIMESTAMP);

    LOG_DEBUG("BuildVerifier: manifest = \"{}\"", manifest);

    // Decode public key.
    const auto pub_bytes = base64Decode(THEMIS_BUILD_PUBKEY);
    if (pub_bytes.size() != 32) {
        res.verified       = false;
        res.failure_reason = "Invalid public key encoding";
        LOG_ERROR("BuildVerifier: THEMIS_BUILD_PUBKEY decodes to {} bytes (need 32)",
                  pub_bytes.size());
        return res;
    }

    // Decode signature.
    const auto sig_bytes = base64Decode(sig_b64);
    if (sig_bytes.size() != 64) {
        res.verified       = false;
        res.failure_reason = "Invalid signature encoding";
        LOG_ERROR("BuildVerifier: THEMIS_BUILD_SIG decodes to {} bytes (need 64)",
                  sig_bytes.size());
        return res;
    }

    if (ed25519Verify(pub_bytes, manifest, sig_bytes)) {
        res.verified = true;
        LOG_INFO("BuildVerifier: official build verified ✓ "
                 "(channel={}, id={}, ts={})",
                 THEMIS_BUILD_CHANNEL, THEMIS_BUILD_ID, THEMIS_BUILD_TIMESTAMP);
    } else {
        res.verified       = false;
        res.failure_reason = "Signature mismatch";
        LOG_WARN("BuildVerifier: signature verification FAILED "
                 "(channel={}, id={})",
                 THEMIS_BUILD_CHANNEL, THEMIS_BUILD_ID);
    }
    return res;
#endif // THEMIS_HAVE_OPENSSL
}

} // anonymous namespace

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

BuildVerificationResult verifyBuildSignature() {
    std::call_once(g_once, []() {
        g_cached_result = doVerify();
    });
    return g_cached_result;
}

const char* buildChannel() noexcept {
    return THEMIS_BUILD_CHANNEL;
}

const char* buildId() noexcept {
    return THEMIS_BUILD_ID;
}

} // namespace updates
} // namespace themis
