/**
 * @file compliance_reporter.h
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.47
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=3; TODO=1, Stub=1, Unimpl=0, Mock=1, Sim=0, Debt=0, C=n/a, H=n/a, M=n/a, L=n/a
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


#pragma once

#include "governance/policy_manager.h"
#include "governance/ccpa_rules.h"
#include <string>
#include <vector>
#include <unordered_map>
#include <memory>
#include <cstdint>
#include <climits>
#include <nlohmann/json.hpp>

namespace themis {
namespace governance {

/// Per-field demographic statistics for a training dataset.
/// Used by BiasAuditReport to capture representation and parity metrics.
struct BiasFieldStats {
    std::string field_name;                           ///< Name of the field (e.g., "gender", "age_group")
    std::unordered_map<std::string, size_t> group_counts; ///< Group label → document count
    size_t total_count = 0;                           ///< Total documents with this field populated

    /// Ratio of the smallest group count to the largest (0 = highly skewed; 1 = uniform).
    /// A value below 0.8 is commonly flagged as a potential bias indicator.
    double representation_ratio = 0.0;

    /// Demographic parity score (0–1): 1.0 means all groups are equally represented;
    /// lower values indicate stronger skew.
    double demographic_parity_score = 0.0;

    nlohmann::json toJson() const;
};

/// Bias audit report for a single AI/ML model training dataset.
/// Generated by ComplianceReporter::generateBiasAuditReport() and stored in
/// the audit trail.  Surfaced via GET /governance/model/{adapter_id}/bias-report.
struct BiasAuditReport {
    std::string report_id;
    std::string adapter_id;          ///< LoRA adapter / model identifier
    std::string dataset_id;          ///< Export job ID used as the dataset identifier
    int64_t generated_at = 0;        ///< Unix epoch milliseconds

    std::vector<BiasFieldStats> field_stats; ///< Per-field statistics

    /// Aggregate bias score across all audited fields (0–1; 1 = no bias detected).
    double overall_bias_score = 0.0;

    /// "PASSED" (overall_bias_score ≥ 0.8), "FLAGGED" (≥ 0.5), or "FAILED" (< 0.5).
    std::string status;

    std::vector<std::string> recommendations; ///< Actionable remediation advice

    nlohmann::json toJson() const;
};

/// Coverage analysis result
struct CoverageAnalysis {
    int total_resources_analyzed = 0;
    int resources_with_policies = 0;
    int resources_without_policies = 0;
    double coverage_percentage = 0.0;
    std::vector<std::string> uncovered_resources;
    std::vector<std::string> overlapping_rules;  // Rules that overlap
    
    nlohmann::json toJson() const;
};

/// Compliance gap
struct ComplianceGap {
    std::string gap_type;                          // "missing_encryption", "no_audit", etc.
    std::string severity;                          // "critical", "high", "medium", "low"
    std::string description;
    std::vector<std::string> affected_resources;
    std::vector<std::string> recommendations;
    
    nlohmann::json toJson() const;
};

/// Compliance report
struct ComplianceReport {
    std::string report_id;
    std::int64_t generated_at;
    std::string report_type;                       // "coverage", "compliance", "summary"
    
    // Summary statistics
    int total_rules = 0;
    int active_rules = 0;
    int inactive_rules = 0;
    
    // Compliance status
    std::vector<ComplianceGap> gaps;
    double compliance_score = 0.0;  // 0-100
    
    // Additional data
    nlohmann::json details;
    
    nlohmann::json toJson() const;
};

/// Represents a single policy rule evaluation event emitted by PolicyEngine::evaluate().
/// Callers populate this from the JSON records in the utils::AuditLogger log
/// (event_type == "policy_evaluation").
struct RuleEvaluationEntry {
    int64_t     timestamp_ms              = 0;     ///< Unix epoch milliseconds
    std::string route;                             ///< API route / resource evaluated
    std::string classification;                    ///< Classification level applied
    std::string mode;                              ///< "enforce" or "observe"
    bool        require_content_encryption = false;
    bool        ccpa_opted_out             = false;
    bool        export_allowed             = true;
    std::string user_id;                           ///< Optional requesting user

    /// Populate from a JSON audit-log record produced by PolicyEngine::evaluate().
    /// Unknown or missing fields are silently ignored.
    static RuleEvaluationEntry fromJson(const nlohmann::json& j);
};

/// Compliance summary report for a specific time window.
/// Produced by ComplianceReporter::generateTimeWindowReport().
struct TimeWindowReport {
    int64_t window_start_ms = 0;          ///< Inclusive window start (Unix ms; 0 = epoch)
    int64_t window_end_ms   = INT64_MAX;  ///< Inclusive window end (Unix ms)
    int64_t generated_at    = 0;          ///< Report generation time (Unix seconds)

    /// Optional compliance framework label (informational only, e.g. "GDPR").
    std::string framework;

    // ── Evaluation counters ──────────────────────────────────────────────────
    int total_evaluations            = 0;
    int enforce_mode_evaluations     = 0;
    int observe_mode_evaluations     = 0;
    int ccpa_opted_out_count         = 0;
    int encryption_required_count    = 0;
    int export_blocked_count         = 0;

    // ── Breakdowns ───────────────────────────────────────────────────────────
    std::unordered_map<std::string, int> evaluations_by_classification;
    std::unordered_map<std::string, int> evaluations_by_route;

    // ── Policy-level compliance ───────────────────────────────────────────────
    double compliance_score = 0.0;         ///< 0–100
    std::vector<ComplianceGap> gaps;

    nlohmann::json toJson() const;
    std::string toCSV() const;
};

/// Compliance reporter and analyzer
class ComplianceReporter {
public:
    ComplianceReporter(std::shared_ptr<PolicyManager> policy_manager);
    
    /// Analyze policy coverage
    /// @param resources List of resources to analyze
    /// @return Coverage analysis result
    CoverageAnalysis analyzeCoverage(const std::vector<std::string>& resources) const;
    
    /// Detect overlapping rules
    /// @return List of rule IDs that have overlapping conditions
    std::vector<std::pair<std::string, std::string>> detectOverlappingRules() const;
    
    /// Detect compliance gaps
    /// @return List of compliance gaps
    std::vector<ComplianceGap> detectGaps() const;
    
    /// Generate summary report
    /// @return Compliance report with summary statistics
    ComplianceReport generateSummaryReport() const;
    
    /// Generate compliance status report
    /// @param framework Optional compliance framework (e.g., "GDPR", "SOX", "CCPA")
    /// @return Compliance report with gap analysis
    ComplianceReport generateComplianceReport(const std::string& framework = "") const;
    
    /// Generate a CCPA/CPRA compliance report
    /// @param rule_set   CCPA rule set containing registered subject records
    /// @param window_start_ms  Report window start (Unix epoch milliseconds; 0 = all)
    /// @param window_end_ms    Report window end (Unix epoch milliseconds; INT64_MAX = all)
    /// @return Structured JSON summary: data categories, third-party disclosures, opt-out counts
    nlohmann::json generateCcpaReport(
        const CcpaRuleSet& rule_set,
        int64_t window_start_ms = 0,
        int64_t window_end_ms   = INT64_MAX
    ) const;

    /// Generate a bias audit report for a training dataset.
    ///
    /// Computes demographic parity and representation statistics for each field
    /// listed in @p field_stats, derives an overall bias score, assigns a
    /// PASSED / FLAGGED / FAILED status, and appends actionable recommendations
    /// for any field with representation_ratio < 0.8.
    ///
    /// @param adapter_id  The LoRA adapter / model identifier this dataset will train.
    /// @param dataset_id  Export job ID that produced the training dataset.
    /// @param field_stats Per-field group counts (key = field name; value = map of
    ///                    group label → document count).  Fields with an empty
    ///                    group_counts map are silently skipped.
    /// @return BiasAuditReport ready to be stored in the audit trail.
    BiasAuditReport generateBiasAuditReport(
        const std::string& adapter_id,
        const std::string& dataset_id,
        const std::unordered_map<std::string,
              std::unordered_map<std::string, size_t>>& field_stats
    ) const;
    
    /// Generate access control matrix
    /// @return JSON representation of access control matrix
    nlohmann::json generateAccessControlMatrix() const;
    
    /// Generate risk assessment report
    /// @return Compliance report focused on risk
    ComplianceReport generateRiskAssessmentReport() const;

    /// Generate a compliance summary for a specific time window.
    ///
    /// Aggregates the supplied @p entries (policy evaluation events produced by
    /// PolicyEngine::evaluate() and persisted via utils::AuditLogger) into a
    /// structured TimeWindowReport.  Only entries whose timestamp_ms falls in
    /// [@p window_start_ms, @p window_end_ms] are included.
    ///
    /// The report covers:
    ///  - Total evaluation count and enforce/observe split.
    ///  - Per-classification and per-route evaluation breakdowns.
    ///  - CCPA opt-out events, encryption-required counts, export-blocked counts.
    ///  - Policy-level compliance gaps (from detectGaps()) and a 0–100 score.
    ///
    /// @param entries          Policy evaluation entries to aggregate.
    /// @param window_start_ms  Inclusive window start in Unix milliseconds (0 = epoch).
    /// @param window_end_ms    Inclusive window end in Unix milliseconds (INT64_MAX = all).
    /// @param framework        Optional compliance framework label stored in the report.
    /// @return Populated TimeWindowReport.
    TimeWindowReport generateTimeWindowReport(
        const std::vector<RuleEvaluationEntry>& entries,
        int64_t window_start_ms = 0,
        int64_t window_end_ms   = INT64_MAX,
        const std::string& framework = "") const;

    /// Export report in specified format
    /// @param report Report to export
    /// @param format Export format ("json", "csv")
    /// @return Exported data as string
    std::string exportReport(const ComplianceReport& report, const std::string& format) const;
    
private:
    std::shared_ptr<PolicyManager> policy_manager_;
    
    /// Helper: Calculate compliance score
    double calculateComplianceScore(const std::vector<ComplianceGap>& gaps) const;
    
    /// Helper: Convert report to CSV
    std::string reportToCSV(const ComplianceReport& report) const;
    
    /// Helper: Check if rule has required security controls
    bool hasRequiredControls(const PolicyRule& rule) const;
};

} // namespace governance
} // namespace themis
