-- This file was generated by SQLite's .dump command.
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT,
  age INTEGER,
  score REAL,
  active INTEGER DEFAULT 1,
  bio TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO users VALUES(1,'Alice','alice@example.com',30,9.5,1,'Hello world','2024-01-01 00:00:00');
INSERT INTO users VALUES(2,'Bob','bob@example.com',25,7.2,1,'Test bio','2024-01-02 00:00:00');
INSERT INTO users VALUES(3,'Charlie',NULL,NULL,NULL,0,NULL,'2024-01-03 00:00:00');
CREATE TABLE products (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  price REAL,
  description TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO products VALUES(1,'Widget A',9.99,'A simple widget','2024-01-01 10:00:00');
INSERT INTO products VALUES(2,'Widget B',19.99,'A better widget','2024-01-02 11:00:00');
COMMIT;
