-- SQL Server Management Studio (SSMS) Export
-- Generated by: SQL Server Management Studio
-- SQL Server Version: Microsoft SQL Server 2019
-- Date: 2024-01-01
-- Database: testdb

USE [testdb]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- ============================================================
-- Table: dbo.users
-- ============================================================

CREATE TABLE [dbo].[users](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [name] [nvarchar](255) NOT NULL,
    [email] [nvarchar](255) NULL,
    [age] [int] NULL,
    [score] [float] NULL,
    [active] [bit] NULL,
    [bio] [nvarchar](max) NULL,
    [created_at] [datetime2](7) NULL,
    CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED ([id] ASC)
)
GO

-- ============================================================
-- Table: dbo.products
-- ============================================================

CREATE TABLE [dbo].[products](
    [id] [int] IDENTITY(1,1) NOT NULL,
    [name] [nvarchar](255) NOT NULL,
    [price] [decimal](10, 2) NULL,
    [stock] [int] NULL,
    [sku] [nvarchar](50) NULL,
    CONSTRAINT [PK_products] PRIMARY KEY CLUSTERED ([id] ASC)
)
GO

-- ============================================================
-- Data for table: dbo.users
-- ============================================================

SET IDENTITY_INSERT [dbo].[users] ON
GO

INSERT INTO [dbo].[users] VALUES (1, N'Alice', N'alice@example.com', 30, 9.5, 1, N'Hello world', '2024-01-01 00:00:00.0000000')
GO

INSERT INTO [dbo].[users] VALUES (2, N'Bob', N'bob@example.com', 25, 7.2, 1, N'Test bio', '2024-01-02 00:00:00.0000000')
GO

SET IDENTITY_INSERT [dbo].[users] OFF
GO

-- ============================================================
-- Data for table: dbo.products
-- ============================================================

SET IDENTITY_INSERT [dbo].[products] ON
GO

INSERT INTO [dbo].[products] VALUES (1, N'Widget', 9.99, 100, N'WID-001')
GO

INSERT INTO [dbo].[products] VALUES (2, N'Gadget', 24.99, 50, N'GAD-002')
GO

SET IDENTITY_INSERT [dbo].[products] OFF
GO
