/*
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            UsbAdminLicense.cs                                 ║
  Version:         0.0.8                                              ║
  Last Modified:   2026-04-15 04:33:14                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟢 PRODUCTION-READY                             ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     75                                             ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Revision History:                                                   ║
    • 684f1ae3bf  2026-03-24  Changes before error encountered        ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: ✅ Production Ready                                          ║
╚═════════════════════════════════════════════════════════════════════╝
 */

using System.Text.Json.Serialization;

namespace Themis.USBAdminTool.Models;

/// <summary>
/// Mirrors the JSON structure of <c>themis_admin.lic</c> written to the USB stick.
/// Must stay in sync with the C++ <c>USBAdminLicense</c> struct parsed in
/// <c>src/security/usb_admin_authenticator.cpp</c>.
/// </summary>
public sealed class UsbAdminLicense
{
    [JsonPropertyName("license_key")]
    public string LicenseKey { get; set; } = string.Empty;

    [JsonPropertyName("organization")]
    public string Organization { get; set; } = string.Empty;

    /// <summary>
    /// Hardware ID of the server host this license is bound to.
    /// On Linux this is the content of <c>/etc/machine-id</c>;
    /// on Windows the registry <c>MachineGuid</c>.
    /// </summary>
    [JsonPropertyName("hardware_id")]
    public string HardwareId { get; set; } = string.Empty;

    [JsonPropertyName("issued_date")]
    public string IssuedDate { get; set; } = string.Empty;

    [JsonPropertyName("expiry_date")]
    public string ExpiryDate { get; set; } = string.Empty;

    [JsonPropertyName("admin_scopes")]
    public List<string> AdminScopes { get; set; } = new();

    /// <summary>
    /// Base64-encoded RSA-SHA256 signature over the canonical data string
    /// (license_key|organization|hardware_id|issued_epoch|expiry_epoch|scope1|…).
    /// Generated by <see cref="Services.UsbProvisioningService"/> using the
    /// configured private key PEM file.
    /// </summary>
    [JsonPropertyName("signature")]
    public string Signature { get; set; } = string.Empty;

    // ── Derived helpers ───────────────────────────────────────────────────────

    public bool IsExpired =>
        DateTime.TryParse(ExpiryDate, out var d) && d < DateTime.UtcNow;

    public bool IsValid =>
        !string.IsNullOrWhiteSpace(LicenseKey) && !string.IsNullOrWhiteSpace(Signature);

    public string StatusLabel => IsExpired ? "Abgelaufen" : IsValid ? "Gültig" : "Ungültig";
}
