/**
 * @file postgres_importer.h
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.47
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=3; TODO=1, Stub=1, Unimpl=0, Mock=1, Sim=0, Debt=0, C=n/a, H=n/a, M=n/a, L=n/a
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


#pragma once

#include "importers/importer_interface.h"
#include "importers/conflict_resolver.h"
#include "importers/relationship_mapper.h"
#include "plugins/plugin_interface.h"
#include <regex>
#include <atomic>
#include <unordered_map>
#include <unordered_set>
#include <mutex>

namespace themis {
namespace importers {

/**
 * @brief PostgreSQL pg_dump Importer
 * 
 * Imports data from PostgreSQL pg_dump files (SQL format).
 * Supports:
 * - DDL parsing (CREATE TABLE, CREATE SCHEMA)
 * - DML parsing (INSERT, COPY)
 * - Schema mapping to ThemisDB BaseEntity
 * - Type conversion with configurable user overrides
 * - Batch processing
 * - Structured error reporting
 */
class PostgreSQLImporter : public IImporter {
public:
    PostgreSQLImporter();
    ~PostgreSQLImporter() override;
    
    // IImporter interface
    const char* getName() const override { return "PostgreSQL Importer"; }
    std::vector<std::string> getSupportedTypes() const override;
    bool initialize(const std::string& config) override;
    bool validateSource(const std::string& source_path, std::vector<std::string>& errors) override;
    ImportStats importData(
        const std::string& source_path,
        const ImportOptions& options,
        ProgressCallback progress_callback = nullptr
    ) override;
    ImportStats importDataStreaming(
        const std::string& source_path,
        const ImportOptions& options,
        RowCallback row_callback
    ) override;
    std::shared_ptr<ImportHandle> importDataAsync(
        const std::string& source_path,
        const ImportOptions& options
    ) override;
    void cancel() override;
    json getSourceSchema(const std::string& source_path) override;
    
private:
    // -------------------------------------------------------------------------
    // v2.0 data structures
    // -------------------------------------------------------------------------

    /**
     * @brief CHECK constraint metadata (v2.1).
     *
     * Covers both named `CONSTRAINT name CHECK (expr)` and unnamed
     * `CHECK (expr)` forms at table level.
     */
    struct CheckConstraint {
        std::string name;        ///< Constraint name (empty for unnamed CHECK)
        std::string expression;  ///< The expression inside CHECK (...)

        json toJson() const {
            return json{{"name", name}, {"expression", expression}};
        }
    };

    /**
     * @brief Generated column / identity column metadata (v2.1).
     *
     * Covers:
     *  - `GENERATED ALWAYS AS (expr) STORED`
     *  - `GENERATED ALWAYS AS IDENTITY`
     *  - `GENERATED BY DEFAULT AS IDENTITY`
     */
    struct GeneratedColumnInfo {
        std::string column;      ///< Column name
        std::string expression;  ///< Generation expression (empty for identity)
        std::string generation;  ///< "ALWAYS" or "BY_DEFAULT"
        bool is_identity = false; ///< True when GENERATED … AS IDENTITY
        bool stored      = false; ///< True when STORED (virtual otherwise)

        json toJson() const {
            return json{
                {"column",      column},
                {"expression",  expression},
                {"generation",  generation},
                {"is_identity", is_identity},
                {"stored",      stored}
            };
        }
    };

    /**
     * @brief EXCLUDE constraint metadata (v2.2).
     *
     * Records the constraint name, the index access method (`USING <method>`),
     * the per-column exclusion operator pairs, and the raw definition text.
     * Stored for information / export purposes; ThemisDB has no native EXCLUDE
     * enforcement, but callers that re-create the schema in PostgreSQL can use
     * the parsed fields to reconstruct the DDL exactly.
     */
    struct ExcludeConstraint {
        /// Constraint name (from `CONSTRAINT <name> EXCLUDE …`)
        std::string name;
        /// Index access method (e.g. "gist", "btree", "spgist")
        std::string index_method;
        /// Per-column exclusion pairs: {column_expression, WITH_operator}
        /// e.g. {{"room", "="}, {"period", "&&"}}
        struct Element {
            std::string column;        ///< Column or expression
            std::string with_operator; ///< Exclusion operator (e.g. "=", "&&", "<>")
        };
        std::vector<Element> elements;
        /// Raw definition text after the EXCLUDE keyword (for round-trip fidelity)
        std::string definition;

        json toJson() const {
            json elems = json::array();
            for (const auto& el : elements) {
                elems.push_back({{"column", el.column}, {"with_operator", el.with_operator}});
            }
            return json{
                {"name",         name},
                {"index_method", index_method},
                {"elements",     elems},
                {"definition",   definition}
            };
        }
    };

    /**
     * @brief Foreign Key constraint metadata (v2.0).
     *
     * Covers both inline REFERENCES and named CONSTRAINT...FOREIGN KEY forms,
     * including DEFERRABLE / INITIALLY DEFERRED / INITIALLY IMMEDIATE modifiers.
     */
    struct ForeignKeyConstraint {
        std::string name;               ///< Constraint name (empty for inline REFERENCES)
        std::string source_column;      ///< Comma-joined source columns, e.g. "user_id"
        std::string target_table;       ///< Referenced table, e.g. "users"
        std::string target_column;      ///< Comma-joined referenced columns, e.g. "id"
        std::string on_delete_action;   ///< CASCADE | SET NULL | RESTRICT | NO ACTION | SET DEFAULT
        std::string on_update_action;   ///< CASCADE | SET NULL | RESTRICT | NO ACTION | SET DEFAULT
        bool deferrable = false;        ///< DEFERRABLE keyword present
        bool initially_deferred = false; ///< INITIALLY DEFERRED (vs. INITIALLY IMMEDIATE)

        json toJson() const {
            return json{
                {"name", name},
                {"source_column", source_column},
                {"target_table", target_table},
                {"target_column", target_column},
                {"on_delete", on_delete_action},
                {"on_update", on_update_action},
                {"deferrable", deferrable},
                {"initially_deferred", initially_deferred}
            };
        }
    };

    /**
     * @brief Index metadata (v2.0).
     *
     * Parsed from both inline column constraints (UNIQUE) and standalone
     * CREATE INDEX / CREATE UNIQUE INDEX statements.
     */
    struct IndexMetadata {
        std::string name;                        ///< Index name
        std::string type;                        ///< btree | hash | gist | gin | brin (default: btree)
        std::vector<std::string> columns;        ///< Indexed columns in order
        bool unique = false;                     ///< UNIQUE index
        bool partial = false;                    ///< Has WHERE clause
        std::string where_clause;                ///< Partial index WHERE expression

        json toJson() const {
            return json{
                {"name", name},
                {"type", type.empty() ? "btree" : type},
                {"columns", columns},
                {"unique", unique},
                {"partial", partial},
                {"where_clause", where_clause}
            };
        }
    };

    struct TableSchema {
        std::string name;
        std::string schema;
        std::vector<std::string> columns;
        std::map<std::string, std::string> column_types;
        std::vector<std::string> primary_keys;

        /// v2.0: Foreign Key Preservation – extracted FK constraints.
        struct ForeignKeyConstraint {
            std::string constraint_name;        ///< e.g. "fk_orders_user"
            std::vector<std::string> columns;   ///< local column(s), e.g. {"user_id"}
            std::string ref_table;              ///< referenced table, e.g. "users"
            std::vector<std::string> ref_columns; ///< referenced columns, e.g. {"id"}
            std::string on_delete;              ///< ON DELETE action, e.g. "CASCADE" (empty = RESTRICT)
            std::string on_update;              ///< ON UPDATE action, e.g. "SET NULL" (empty = RESTRICT)

            // Compatibility aliases used by older mapper/validation paths.
            std::string name;
            std::string source_column;
            std::string target_table;
            std::string target_column;
            std::string on_delete_action;
            std::string on_update_action;

            json toJson() const {
                auto joinCols = [](const std::vector<std::string>& v) {
                    std::string out;
                    for (size_t i = 0; i < v.size(); ++i) {
                        if (i > 0) {
                          out += ",";
                        }
                        out += v[i];
                    }
                    return out;
                };
                const std::string effective_name = !constraint_name.empty() ? constraint_name : name;
                const std::string effective_src = !source_column.empty() ? source_column : joinCols(columns);
                const std::string effective_tgt_table = !target_table.empty() ? target_table : ref_table;
                const std::string effective_tgt_col = !target_column.empty() ? target_column : joinCols(ref_columns);
                const std::string effective_on_delete = !on_delete_action.empty() ? on_delete_action : on_delete;
                const std::string effective_on_update = !on_update_action.empty() ? on_update_action : on_update;
                return json{
                    {"constraint_name", effective_name},
                    {"columns",         columns},
                    {"ref_table",       effective_tgt_table},
                    {"ref_columns",     ref_columns},
                    {"on_delete",       effective_on_delete},
                    {"on_update",       effective_on_update},
                    {"name",            effective_name},
                    {"source_column",   effective_src},
                    {"target_table",    effective_tgt_table},
                    {"target_column",   effective_tgt_col},
                    {"on_delete_action", effective_on_delete},
                    {"on_update_action", effective_on_update}
                };
            }
        };
        // v2.0 extensions
        std::vector<ForeignKeyConstraint> foreign_keys;       ///< Parsed FK constraints
        std::map<std::string, std::string> column_defaults;   ///< DEFAULT expressions per column
        std::map<std::string, std::string> column_constraints; ///< NOT NULL, UNIQUE inline per column
        std::vector<IndexMetadata> indexes;                   ///< Explicit indexes on this table
        std::map<std::string, std::string> custom_types;      ///< Custom type hints per column

        // v2.1 extensions
        std::vector<CheckConstraint>     check_constraints;   ///< CHECK constraint expressions
        std::vector<GeneratedColumnInfo> generated_columns;   ///< GENERATED / IDENTITY columns
        std::vector<ExcludeConstraint>   exclude_constraints; ///< EXCLUDE constraints (metadata)

        json toJson() const {
            json fk_arr = json::array();
            for (const auto& fk : foreign_keys) {
              fk_arr.push_back(fk.toJson());
            }
            json idx_arr = json::array();
            for (const auto& idx : indexes) {
              idx_arr.push_back(idx.toJson());
            }
            json ck_arr = json::array();
            for (const auto& ck : check_constraints) {
              ck_arr.push_back(ck.toJson());
            }
            json gen_arr = json::array();
            for (const auto& g : generated_columns) {
              gen_arr.push_back(g.toJson());
            }
            json excl_arr = json::array();
            for (const auto& ex : exclude_constraints) {
              excl_arr.push_back(ex.toJson());
            }
            return json{
                {"name", name},
                {"schema", schema},
                {"columns", columns},
                {"column_types", column_types},
                {"primary_keys", primary_keys},
                {"foreign_keys", fk_arr},
                {"column_defaults", column_defaults},
                {"column_constraints", column_constraints},
                {"indexes", idx_arr},
                {"custom_types", custom_types},
                {"check_constraints", ck_arr},
                {"generated_columns", gen_arr},
                {"exclude_constraints", excl_arr}
            };
        }
    };
    
    std::atomic<bool> cancelled_{false};
        mutable std::mutex custom_type_map_mutex_;  ///< Protects custom_type_map_ concurrent access
    std::unordered_map<std::string, TableSchema> schemas_;  ///< O(1) lookup by table name
    std::unordered_map<std::string, std::string> custom_type_map_;  ///< Types from CREATE TYPE
    ImportConflictResolver conflict_resolver_;  ///< In-session conflict tracker
    
    // Parsing methods
    bool parseDumpFile(const std::string& file_path, const ImportOptions& options, ImportStats& stats,
                       ProgressCallback& callback);
    bool parseCreateTable(const std::string& sql, TableSchema& schema);
    bool parseInsert(const std::string& sql, const ImportOptions& options, ImportStats& stats,
                     size_t line_number);
    bool parseCopy(std::ifstream& file, const std::string& table_name,
                   const std::vector<std::string>& columns,
                   const ImportOptions& options, ImportStats& stats,
                   std::unordered_set<uint64_t>& delta_hashes);

    // v2.0: Foreign Key helpers
    /// Parse a single FOREIGN KEY constraint clause (table-level) and append to schema.
    /// @param constraint_def  The trimmed constraint definition, e.g.
    ///   "CONSTRAINT fk_x FOREIGN KEY (col) REFERENCES tbl(id) ON DELETE CASCADE"
    ///   or bare "FOREIGN KEY (col) REFERENCES tbl(id)"
    /// @return true if a valid FK was parsed and appended.
    bool parseForeignKeyConstraint(const std::string& constraint_def,
                                   TableSchema& schema) const;

    /// Parse an inline column-level REFERENCES clause and append a FK to schema.
    /// @param col_name   The column owning the reference.
    /// @param col_def    Full column definition string, e.g.
    ///   "user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE"
    /// @return true if a REFERENCES clause was found and a FK was appended.
    bool parseInlineReference(const std::string& col_name,
                              const std::string& col_def,
                              TableSchema& schema) const;

    /// Parse a standalone ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY statement
    /// and update the corresponding cached schema entry.
    void parseAlterTableAddFk(const std::string& sql,
                               const ImportOptions& options,
                               ImportStats& stats);
    // v2.0 parser methods
    bool parseForeignKeyConstraint(const std::string& constraint_def,
                                   ForeignKeyConstraint& fk);
    bool parseCreateIndex(const std::string& sql,
                          const std::string& table_name,
                          IndexMetadata& index);
    bool parseAlterTableForeignKey(const std::string& sql,
                                   std::string& out_table,
                                   ForeignKeyConstraint& fk);
    bool validateForeignKeyReferences(const ImportOptions& options,
                                      ImportStats& stats);

    // v2.1 parser methods
    bool parseCheckConstraint(const std::string& constraint_def, CheckConstraint& ck);
    bool parseExcludeConstraint(const std::string& constraint_def, ExcludeConstraint& excl);
    bool parseGeneratedColumn(const std::string& col_def, const std::string& col_name,
                              GeneratedColumnInfo& gen);
    
    // Schema mapping
    std::string mapPostgreSQLTypeToThemis(const std::string& pg_type,
                                          const ImportOptions& options) const;
    bool shouldImportTable(const std::string& table_name, const ImportOptions& options);
    
    // Data conversion
    json convertRowToEntity(const TableSchema& schema, const std::vector<std::string>& values);

    // COPY row helpers
    std::vector<std::string> parseCopyRow(const std::string& line) const;
    std::string unescapeCopyValue(const std::string& val) const;

    // INSERT helpers
    std::vector<std::string> parseInsertValues(const std::string& values_clause) const;
    
    // Error helpers
    void addError(ImportStats& stats, ImportErrorCode code, ImportErrorSeverity severity,
                  const std::string& message, const std::string& location = "") const;
    
    // PHASE-2-HARDENING: Standardized PostgreSQL error reporting
    /// Add a PostgreSQL-specific error with automatic error code mapping
    void addPostgreSQLError(ImportStats& stats, ImportErrorSeverity severity,
                           const std::string& pg_error_msg,
                           const std::string& location = "") const;

    // Metrics emission helper
    void emitMetric(const ImportOptions& options,
                    const std::string& metric,
                    const std::map<std::string, std::string>& labels,
                    double value) const;

    // Distributed tracing / OTel span emission helper
    void emitSpan(const ImportOptions& options,
                  const std::string& operation,
                  const std::map<std::string, std::string>& attributes,
                  double duration_seconds) const;

    // UTF-8 validation helper
    static bool isValidUtf8(const std::string& s);

    // Checkpoint helpers
    bool loadCheckpoint(const std::string& checkpoint_file, std::streampos& offset,
                        ImportStats& accumulated_stats) const;
    void saveCheckpoint(const std::string& checkpoint_file, std::streampos offset,
                        const ImportStats& stats) const;

    // Quarantine helpers
    void writeQuarantineRow(const std::string& quarantine_file,
                            const std::string& table_name,
                            const std::string& raw_row,
                            const ImportError& error) const;

    // Delta / incremental import helpers
    static uint64_t computeRowHash(const std::string& raw_row,
                                   const std::vector<std::string>& values,
                                   const std::vector<std::string>& key_columns,
                                   const std::vector<std::string>& schema_columns);
    static std::unordered_set<uint64_t> loadDeltaHashes(const std::string& delta_hash_file);
    static void saveDeltaHashes(const std::string& delta_hash_file,
                                const std::unordered_set<uint64_t>& hashes);

    // Progress reporting
    void reportProgress(ProgressCallback& callback, const std::string& stage, size_t current, size_t total);
};

/**
 * @brief PostgreSQL Importer Plugin
 * 
 * Wraps PostgreSQLImporter as a ThemisDB plugin
 */
class PostgreSQLImporterPlugin : public plugins::IThemisPlugin {
public:
    PostgreSQLImporterPlugin();
    ~PostgreSQLImporterPlugin() override = default;
    
    // IThemisPlugin interface
    const char* getName() const override { return "postgres_importer"; }
    const char* getVersion() const override { return "2.0.0"; }
    plugins::PluginType getType() const override { return plugins::PluginType::IMPORTER; }
    plugins::PluginCapabilities getCapabilities() const override;
    bool initialize(const char* config_json) override;
    void shutdown() override;
    void* getInstance() override { return importer_.get(); }
    
private:
    std::unique_ptr<PostgreSQLImporter> importer_;
};

} // namespace importers
} // namespace themis

