#pragma once

/**
 * @file layered_retrieval_orchestrator.h
 * @brief Master orchestrator for the four-layer hybrid knowledge retrieval architecture.
 *
 * This file defines the core orchestrator that chains together:
 * 1. ANN Frontdoor - fast semantic candidate retrieval
 * 2. Tensor Mid-Layer - compression, routing, and candidate refinement
 * 3. Graph Truth Layer - exact validation and evidence assembly
 * 4. LLM/LoRA Final Layer - grounded generation with domain adaptation
 *
 * The orchestrator implements the complete retrieval pipeline with
 * proper error handling, fallback strategies, and observability.
 */

#include "index/ann_frontdoor.h"
#include "tensor/tensor_mid_layer.h"
#include "rag/graph_truth_validator.h"
#include "llm/final_layer_orchestrator.h"

#include <memory>
#include <string>
#include <vector>
#include <optional>
#include <chrono>
#include <nlohmann/json.hpp>

namespace themis {
namespace search {

/**
 * @brief Configuration for layered retrieval orchestration.
 */
struct LayeredRetrievalConfig {
    /// Enable/disable each layer independently
    bool enable_ann_layer = true;
    bool enable_tensor_layer = true;
    bool enable_graph_layer = true;
    bool enable_llm_layer = true;

    /// Layer parameters
    int ann_k = 100;                    ///< ANN candidate count
    int tensor_top_k = 50;              ///< Tensor refinement count
    int graph_top_k = 20;               ///< Graph validation count

    /// Fallback and error handling
    bool allow_layer_fallback = true;   ///< Use fallback when layer fails
    bool fail_closed_on_graph_error = true;  ///< Reject rather than accept on graph error

    /// Performance and resource limits
    size_t max_candidates = 10'000;
    uint32_t timeout_ms = 5'000;        ///< Total orchestration timeout
};

/**
 * @brief Routing context for observability and governance.
 */
struct LayeredRetrievalContext {
    std::string query_text;
    std::string correlation_id;
    std::string tenant_id;
    std::string principal;              ///< User/principal for ACL
    std::string domain;

    /// Layer-specific context
    std::string base_model_id;
    std::string requested_package_id;   ///< Requested LLM package

    /// Governance
    std::string confidence_policy_version;
    std::string confidence_threshold_key;

    /// Flags
    bool shard_aware = false;
    bool trace_enabled = false;
};

/**
 * @brief Per-layer routing decision for a single retrieval.
 */
struct LayerRoutingDecision {
    std::string layer_name;             ///< "ANN", "Tensor", "Graph", "LLM"
    std::string routing_reason;
    std::string routing_reason_code;
    bool success = false;
    std::chrono::milliseconds elapsed_ms{0};
    std::vector<std::string> errors;
    std::vector<std::string> warnings;
};

/**
 * @brief Complete result from end-to-end layered retrieval.
 */
struct LayeredRetrievalResult {
    /// Final result
    bool success = false;
    std::string final_answer;           ///< Generated by LLM layer

    /// Layer-by-layer routing decisions
    std::vector<LayerRoutingDecision> layer_decisions;

    /// Provenance and evidence
    std::vector<rag::GraphTruthEvidence> evidence_bundle;
    std::vector<rag::ProvenanceRecord> provenance_trail;

    /// Metadata
    std::string correlation_id;
    std::chrono::milliseconds total_latency_ms{0};

    /// For debugging and tracing
    nlohmann::json debug_trace;
};

/**
 * @brief Master orchestrator for the four-layer retrieval architecture.
 *
 * The LayeredRetrievalOrchestrator coordinates the complete retrieval pipeline:
 *
 * ### Layer Flow
 *
 * ```
 * Query + Embedding
 *     ↓
 * [ANN Frontdoor]  → Semantic candidate retrieval (fast)
 *     ↓
 * [Tensor Mid-Layer] → Compression, routing, refinement
 *     ↓
 * [Graph Truth Layer] → Exact validation, evidence assembly, provenance
 *     ↓
 * [LLM/LoRA Final Layer] → Grounded generation with domain adaptation
 *     ↓
 * Answer + Provenance
 * ```
 *
 * ### Error Handling Strategy
 *
 * - **ANN Layer Failure**: Fall back to brute-force or skip to next layer
 * - **Tensor Layer Failure**: Pass candidates unchanged to graph layer
 * - **Graph Layer Failure**: Fail-closed (reject) if enabled, otherwise use unapproved evidence
 * - **LLM Layer Failure**: Use fallback template or error response
 *
 * ### Observability
 *
 * All layer transitions are tracked with:
 * - Routing decision metadata
 * - Correlation IDs for tracing
 * - Per-layer latency and error information
 * - Complete provenance trail
 *
 * ### Thread Safety
 *
 * The orchestrator is thread-safe for execute() calls (read-only operations).
 * Configuration changes (set*) must not be called concurrently with execute().
 */
class LayeredRetrievalOrchestrator {
public:
    LayeredRetrievalOrchestrator() = default;
    ~LayeredRetrievalOrchestrator() = default;

    // -----------------------------------------------------------------------
    // Dependency Injection
    // -----------------------------------------------------------------------

    /**
     * @brief Inject the ANN Frontdoor layer.
     */
    void setAnnFrontdoor(std::shared_ptr<index::AnnFrontdoor> frontdoor) {
        ann_frontdoor_ = frontdoor;
    }

    /**
     * @brief Inject the Tensor Mid-Layer.
     */
    void setTensorMidLayer(std::shared_ptr<tensor::TensorMidLayer> tensor_layer) {
        tensor_layer_ = tensor_layer;
    }

    /**
     * @brief Inject the Graph Truth Layer.
     */
    void setGraphTruthValidator(std::shared_ptr<rag::GraphTruthValidator> graph_validator) {
        graph_validator_ = graph_validator;
    }

    /**
     * @brief Inject the LLM/LoRA Final Layer.
     */
    void setFinalLayerOrchestrator(std::shared_ptr<llm::FinalLayerOrchestrator> final_layer) {
        final_layer_ = final_layer;
    }

    // -----------------------------------------------------------------------
    // Configuration
    // -----------------------------------------------------------------------

    /**
     * @brief Update orchestration configuration.
     */
    void setConfig(const LayeredRetrievalConfig& config) {
        config_ = config;
    }

    /**
     * @brief Get current configuration.
     */
    [[nodiscard]] const LayeredRetrievalConfig& config() const noexcept {
        return config_;
    }

    // -----------------------------------------------------------------------
    // Main Retrieval API
    // -----------------------------------------------------------------------

    /**
     * @brief Execute the complete layered retrieval pipeline.
     *
     * This is the primary entry point. It orchestrates the complete flow:
     * ANN → Tensor → Graph → LLM.
     *
     * @param query_vector      Pointer to embedding (float array)
     * @param query_dim         Embedding dimensionality
     * @param query_text        Human-readable query for context
     * @param context           Routing context (governance, observability)
     *
     * @return Complete result with evidence, provenance, and final answer.
     *
     * @note Strong exception safety: if construction fails, the result
     *       is in a valid error state with failure messages.
     *
     * @note Thread-safe: multiple threads can call this concurrently on
     *       separate orchestrator instances or with external synchronization.
     */
    [[nodiscard]] LayeredRetrievalResult execute(
        const float* query_vector,
        std::size_t query_dim,
        const std::string& query_text,
        const LayeredRetrievalContext& context = {});

    /**
     * @brief Get the current health status of all injected layers.
     *
     * Returns true only if all enabled layers are available.
     */
    [[nodiscard]] bool isHealthy() const noexcept;

    /**
     * @brief Get human-readable status of orchestrator and layers.
     */
    [[nodiscard]] std::string statusReport() const;

private:
    // -----------------------------------------------------------------------
    // Private Layer Execution
    // -----------------------------------------------------------------------

    /**
     * @brief Execute the ANN Frontdoor layer.
     */
    [[nodiscard]] index::AnnFrontdoorResult executeAnnLayer(
        const float* query_vector,
        std::size_t query_dim,
        const LayeredRetrievalContext& context,
        LayerRoutingDecision& decision);

    /**
     * @brief Execute the Tensor Mid-Layer.
     */
    [[nodiscard]] std::optional<tensor::TensorLayerSummary> executeTensorLayer(
        const index::AnnFrontdoorResult& ann_result,
        const LayeredRetrievalContext& context,
        LayerRoutingDecision& decision);

    /**
     * @brief Execute the Graph Truth Layer.
     */
    [[nodiscard]] std::optional<rag::GraphTruthValidationResult> executeGraphLayer(
        const tensor::TensorLayerSummary& tensor_summary,
        const LayeredRetrievalContext& context,
        LayerRoutingDecision& decision);

    /**
     * @brief Execute the LLM/LoRA Final Layer.
     */
    [[nodiscard]] std::optional<std::string> executeLlmLayer(
        const rag::GraphTruthValidationResult& graph_result,
        const std::string& query_text,
        const LayeredRetrievalContext& context,
        LayerRoutingDecision& decision);

    // -----------------------------------------------------------------------
    // Error Handling and Fallback
    // -----------------------------------------------------------------------

    /**
     * @brief Generate fallback answer when LLM layer fails.
     */
    [[nodiscard]] std::string generateFallbackAnswer(
        const std::string& query_text,
        const std::vector<rag::GraphTruthEvidence>& evidence);

    /**
     * @brief Build error result when orchestration fails.
     */
    [[nodiscard]] LayeredRetrievalResult buildErrorResult(
        const std::vector<LayerRoutingDecision>& decisions,
        const LayeredRetrievalContext& context);

    // -----------------------------------------------------------------------
    // Tracing and Observability
    // -----------------------------------------------------------------------

    /**
     * @brief Log a layer transition event.
     */
    void traceLayerTransition(
        const std::string& from_layer,
        const std::string& to_layer,
        const LayerRoutingDecision& decision,
        const LayeredRetrievalContext& context);

    // -----------------------------------------------------------------------
    // Member Variables
    // -----------------------------------------------------------------------

    LayeredRetrievalConfig config_;

    std::shared_ptr<index::AnnFrontdoor> ann_frontdoor_;
    std::shared_ptr<tensor::TensorMidLayer> tensor_layer_;
    std::shared_ptr<rag::GraphTruthValidator> graph_validator_;
    std::shared_ptr<llm::FinalLayerOrchestrator> final_layer_;
};

} // namespace search
} // namespace themis
