#!/usr/bin/env python3
"""
Extract supporters from Supporters.md and generate a C++ header with base64-encoded list.
This script is called during CMake build configuration.

Usage:
  python3 extract_supporters.py <input_md_file> <output_header_file>

Example:
  python3 extract_supporters.py Supporters.md include/generated/supporters_list.h
"""

import sys
import re
import base64
from pathlib import Path


def extract_supporters(md_file_path: str) -> list:
    """
    Parse Supporters.md and extract all supporter names from the compact format.
    
    Expects format: **Thank you to:** name1, org (Lead et al.), name2, ...
    Only extracts from the first "Thank you to:" line to avoid duplicates.
    
    Returns:
        List of supporter names and contributors (strings)
    """
    supporters = []
    
    try:
        with open(md_file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except FileNotFoundError:
        print(f"Error: File not found: {md_file_path}", file=sys.stderr)
        return supporters
    
    # Extract only the first-line "Thank you to:" section (compact format)
    lines = content.split('\n')
    for line in lines:
        if line.startswith('**Thank you to:**'):
            # Parse the comma-separated list
            thank_you_text = line.replace('**Thank you to:**', '').strip()
            
            # Split by comma and clean up each entry
            entries = [s.strip() for s in thank_you_text.split(',')]
            
            for entry in entries:
                if entry:
                    # Remove markdown links and formatting
                    entry = re.sub(r'\[([^\]]+)\]\([^)]+\)', r'\1', entry)
                    entry = re.sub(r'\*+([^*]+)\*+', r'\1', entry)
                    entry = entry.strip()
                    
                    if entry and entry not in ['Last Updated:', 'To add your name to this list,']:
                        supporters.append(entry)
            
            # Only use the compact "Thank you to:" line, not the detailed sections
            return supporters
    
    return supporters


def generate_header(supporters: list, output_file_path: str) -> None:
    """
    Generate a C++ header file with base64-encoded supporter list.
    
    Args:
        supporters: List of supporter names
        output_file_path: Path to output header file
    """
    # Create comma-separated list
    supporters_str = ', '.join(supporters)
    
    # Encode to base64 for compact storage
    supporters_bytes = supporters_str.encode('utf-8')
    supporters_b64 = base64.b64encode(supporters_bytes).decode('ascii')
    
    # Ensure output directory exists
    output_path = Path(output_file_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Generate header file
    header_content = f'''// Auto-generated file - do not edit manually
// Generated by scripts/extract_supporters.py
// Source: Supporters.md

#ifndef THEMIS_GENERATED_SUPPORTERS_LIST_H
#define THEMIS_GENERATED_SUPPORTERS_LIST_H

#include <string>
#include <string_view>
#include <array>

namespace themis {{

    /// Base64-encoded comma-separated supporter list
    constexpr std::string_view SUPPORTERS_ENCODED = "{supporters_b64}";

    /// Decode the base64-encoded supporter list
    /// @return Decoded comma-separated string of supporter names
    inline std::string decode_supporters() {{
        // Minimal base64 decoder for the supporter list
        static const std::array<unsigned char, 256> b64_table = {{
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,  62, 255, 255, 255,  63,
             52,  53,  54,  55,  56,  57,  58,  59,  60,  61, 255, 255, 255, 255, 255, 255,
            255,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
             15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25, 255, 255, 255, 255, 255,
            255,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
             41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
            255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255
        }};
        
        std::string result;
        const auto& encoded = SUPPORTERS_ENCODED;
        size_t i = 0;
        
        while (i < encoded.size()) {{
            unsigned char c1 = b64_table[static_cast<unsigned char>(encoded[i++])];
            if (c1 == 255) break;
            
            if (i >= encoded.size()) break;
            unsigned char c2 = b64_table[static_cast<unsigned char>(encoded[i++])];
            if (c2 == 255) break;
            
            result.push_back(static_cast<char>((c1 << 2) | (c2 >> 4)));
            
            if (i >= encoded.size() || encoded[i] == '=') break;
            unsigned char c3 = b64_table[static_cast<unsigned char>(encoded[i++])];
            if (c3 == 255) break;
            
            result.push_back(static_cast<char>(((c2 & 0x0f) << 4) | (c3 >> 2)));
            
            if (i >= encoded.size() || encoded[i] == '=') break;
            unsigned char c4 = b64_table[static_cast<unsigned char>(encoded[i++])];
            if (c4 == 255) break;
            
            result.push_back(static_cast<char>(((c3 & 0x03) << 6) | c4));
        }}
        
        return result;
    }}

}} // namespace themis

#endif // THEMIS_GENERATED_SUPPORTERS_LIST_H
'''
    
    try:
        with open(output_file_path, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"✓ Generated supporters header: {output_file_path}")
        print(f"  Encoded {len(supporters)} supporters")
        print(f"  Supporters: {supporters_str[:100]}{'...' if len(supporters_str) > 100 else ''}")
    except IOError as e:
        print(f"Error: Failed to write header file: {e}", file=sys.stderr)
        sys.exit(1)


def main():
    if len(sys.argv) != 3:
        print("Usage: python3 extract_supporters.py <input_md_file> <output_header_file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    # Extract supporters from markdown
    supporters = extract_supporters(input_file)
    
    if not supporters:
        print("Warning: No supporters found in input file", file=sys.stderr)
    
    # Generate C++ header
    generate_header(supporters, output_file)


if __name__ == '__main__':
    main()
