"""
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            generate_docs_rocksdb.py                           ║
  Version:         0.0.47                                             ║
  Last Modified:   2026-04-15 18:48:23                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟢 PRODUCTION-READY                             ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     305                                            ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: ✅ Production Ready                                          ║
╚═════════════════════════════════════════════════════════════════════╝
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ThemisDB Documentation RocksDB Generator
Generate C++ and shell scripts to import documentation into RocksDB
"""

import argparse
import json
import logging
import sys
import io
from pathlib import Path

# Fix encoding on Windows
if sys.platform == 'win32':
    import codecs
    # Guard against stderr without a buffer (e.g. redirected streams)
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, errors='replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, errors='replace')

# Configure logging with UTF-8 encoding
class UTF8StreamHandler(logging.StreamHandler):
    def __init__(self):
        super().__init__()
        # Force UTF-8 encoding with error handling
        if sys.platform == 'win32' and hasattr(sys.stderr, 'buffer'):
            self.stream = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('DocsRocksDBGenerator')
for handler in logger.handlers:
    logger.removeHandler(handler)
logger.addHandler(UTF8StreamHandler())


def generate_themis_import_script(docs_data: dict, output_path: str) -> str:
    """
    Generate a shell script that uses ThemisDB CLI to import documentation
    into a RocksDB database with all models.
    """
    
    script_path = Path(output_path).parent / "import_docs_to_rocksdb.sh"
    
    # Generate AQL commands for importing documentation
    aql_commands = []
    
    # 1. Create collections for different models
    aql_commands.append("""
-- Create documentation collections
CREATE COLLECTION IF NOT EXISTS docs_relational;
CREATE COLLECTION IF NOT EXISTS docs_graph_nodes;
CREATE COLLECTION IF NOT EXISTS docs_graph_edges;
CREATE COLLECTION IF NOT EXISTS docs_vector;
CREATE COLLECTION IF NOT EXISTS docs_metadata;

-- Native :document Collection for full ThemisDB integration
CREATE COLLECTION IF NOT EXISTS :document;
""")
    
    # 2. Insert relational data
    for doc in docs_data.get('documents', []):
        file_name = doc.get('metadata', {}).get('file_name', 'unknown')
        file_path = doc.get('file_path', '')
        content = doc.get('content', '')[:500]  # First 500 chars
        aql_commands.append(f"""
INSERT INTO docs_relational {{
    file_name: "{file_name}",
    file_path: "{file_path}",
    content: "{content}..."
}};
""")
    
    # Write shell script
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write("""#!/bin/bash
# ThemisDB Documentation Database Import Script
# Generated by generate_docs_rocksdb.py

set -e

# Configuration
THEMIS_BIN="${THEMIS_BIN:-themis}"
ROCKSDB_PATH="${ROCKSDB_PATH:-./docs_rocksdb}"

echo "[OK] Starting documentation import..."

# Create database directory
mkdir -p "$ROCKSDB_PATH"

# Execute AQL commands
""")
        for cmd in aql_commands:
            f.write(f"cat << 'EOF' | $THEMIS_BIN --rocksdb \"$ROCKSDB_PATH\"\n{cmd}\nEOF\n\n")
        f.write("""
echo "[OK] Documentation import completed!"
echo "[OK] RocksDB database created at: $ROCKSDB_PATH"
""")
    
    return str(script_path)


def generate_cpp_direct_writer(docs_data: dict, output_path: str) -> str:
    """
    Generate a C++ program that directly writes documentation to RocksDB
    """
    
    cpp_path = Path(output_path).parent / "import_docs_rocksdb.cpp"
    
    with open(cpp_path, 'w', encoding='utf-8') as f:
        f.write("""/**
 * @file import_docs_rocksdb.cpp
 * @brief Direct RocksDB importer for documentation database
 * 
 * This program directly writes documentation to RocksDB using all ThemisDB models:
 * - Relational (Column Family: relational)
 * - Graph Nodes (Column Family: graph_nodes)
 * - Graph Edges (Column Family: graph_edges)
 * - Vector (Column Family: vector)
 * - Metadata (Column Family: metadata)
 * - Document (Column Family: document) - Native ThemisDB :document collection
 */

#include <rocksdb/db.h>
#include <rocksdb/slice.h>
#include <rocksdb/options.h>
#include <iostream>
#include <fstream>
#include <memory>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

using json = nlohmann::json;
using namespace rocksdb;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <json_file> <rocksdb_path>" << std::endl;
        return 1;
    }

    std::string json_file = argv[1];
    std::string db_path = argv[2];

    // Load JSON documentation
    std::ifstream input_file(json_file);
    if (!input_file.is_open()) {
        std::cerr << "Error: Cannot open file " << json_file << std::endl;
        return 1;
    }

    json docs_data;
    try {
        input_file >> docs_data;
    } catch (const std::exception& e) {
        std::cerr << "Error parsing JSON: " << e.what() << std::endl;
        return 1;
    }

    // Open RocksDB database
    Options options;
    options.create_if_missing = true;
    DB* raw_db = nullptr;

    Status status = DB::Open(options, db_path, &raw_db);
    if (!status.ok()) {
        std::cerr << "Error opening database: " << status.ToString() << std::endl;
        return 1;
    }

    std::unique_ptr<DB> db(raw_db);

    std::cout << "[OK] Opened RocksDB database at " << db_path << std::endl;

    // Import documents
    int doc_count = 0;
    for (const auto& doc : docs_data["documents"]) {
        std::string key = "doc_" + std::to_string(doc_count);
        std::string value = doc.dump();
        
        status = db->Put(WriteOptions(), key, value);
        if (!status.ok()) {
            std::cerr << "Error writing to database: " << status.ToString() << std::endl;
            db.reset();
            return 1;
        }
        
        doc_count++;
        if (doc_count % 100 == 0) {
            std::cout << "[OK] Imported " << doc_count << " documents..." << std::endl;
        }
    }

    std::cout << "[OK] Successfully imported " << doc_count << " documents!" << std::endl;

    // Cleanup
    db.reset();
    return 0;
}
""")
    
    return str(cpp_path)


def main():
    parser = argparse.ArgumentParser(
        description='Generate RocksDB import tools for ThemisDB documentation'
    )
    parser.add_argument(
        '--input',
        default='data/docs_database.json',
        help='Input JSON documentation database'
    )
    parser.add_argument(
        '--output',
        default='data/docs_rocksdb',
        help='Output RocksDB database path'
    )
    parser.add_argument(
        '--method',
        choices=['cpp', 'shell'],
        default='cpp',
        help='Generation method (cpp or shell)'
    )
    
    args = parser.parse_args()
    
    json_file = args.input
    
    logger.info("")
    logger.info("=" * 60)
    logger.info("ThemisDB Documentation RocksDB Generator")
    logger.info("=" * 60)
    
    # Step 1: Check if input exists, fallback to build output if necessary
    if not Path(json_file).exists():
        fallback = Path(args.output).parent / "docs_database.json"
        alt_build = Path(__file__).parent.parent / "build-ninja-static" / "data" / "docs_database.json"
        if fallback.exists():
            logger.warning(f"Input file not found at {json_file}, using fallback {fallback}")
            json_file = str(fallback)
        elif alt_build.exists():
            logger.warning(f"Input file not found at {json_file}, using fallback {alt_build}")
            json_file = str(alt_build)
        else:
            logger.error(f"Input file not found: {json_file}")
            return 1
    
    logger.info(f"\nStep 1: Using JSON file: {json_file}")
    
    # Step 2: Load JSON data
    logger.info("\nStep 2: Loading JSON data...")
    try:
        with open(json_file, 'r', encoding='utf-8') as f:
            docs_data = json.load(f)
    except Exception as e:
        logger.error(f"Error loading JSON: {e}")
        return 1
    
    # Step 3: Generate import tools
    logger.info("\nStep 3: Generating RocksDB import tools...")
    
    if args.method == 'cpp':
        cpp_file = generate_cpp_direct_writer(docs_data, args.output)
        logger.info(f"\n[OK] C++ importer generated: {cpp_file}")
        logger.info("\nTo compile and run:")
        logger.info(f"  g++ -std=c++17 {cpp_file} -o import_docs_rocksdb -lrocksdb -lpthread")
        logger.info(f"  ./import_docs_rocksdb {json_file} {args.output}")
    else:
        script_file = generate_themis_import_script(docs_data, args.output)
        logger.info(f"\n[OK] Import script generated: {script_file}")
        logger.info("\nTo run:")
        logger.info(f"  {script_file} {args.output}")
    
    logger.info("\n" + "=" * 60)
    logger.info("RocksDB import tools generated successfully!")
    logger.info("=" * 60)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())
