#!/usr/bin/env python3
import os
import sys

root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
out_dir = os.path.join(root, 'logs')
os.makedirs(out_dir, exist_ok=True)
report = os.path.join(out_dir, 'add_definitions_report.txt')

matches = []
for dirpath, dirnames, filenames in os.walk(root):
    # skip build directories
    if 'build' in dirpath.split(os.sep) or '.git' in dirpath.split(os.sep):
        continue
    for fn in filenames:
        if fn.endswith('.cmake') or fn == 'CMakeLists.txt':
            path = os.path.join(dirpath, fn)
            try:
                with open(path, 'r', encoding='utf-8', errors='ignore') as f:
                    for i, line in enumerate(f, start=1):
                        if 'add_definitions' in line:
                            matches.append((path, i, line.strip()))
            except Exception as e:
                print('Warning reading', path, e, file=sys.stderr)

with open(report, 'w', encoding='utf-8') as f:
    f.write('ThemisDB - add_definitions() usage report\n')
    f.write('Generated by scripts/generate_add_definitions_report.py\n\n')
    if matches:
        for path, ln, text in matches:
            f.write(f'Found: {path}:{ln}\n')
            f.write(f'  Line: {text}\n')
            f.write("  Suggested: Replace 'add_definitions(-DFOO)' with\n    target_compile_definitions(<target> PRIVATE -DFOO)\n    or use add_compile_definitions(-DFOO) for directory/global scope (CMake >=3.12)\n\n")
    else:
        f.write('No occurrences of add_definitions() found.\n')

print('Report written to', report)
