"""
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            generate_legal_rocksdb.py                          ║
  Version:         0.0.41                                             ║
  Last Modified:   2026-04-14 11:31:28                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟢 PRODUCTION-READY                             ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     260                                            ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Revision History:                                                   ║
    • 2a1fb04231  2026-03-03  Merge branch 'develop' into copilot/audit-src-module-docu... ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: ✅ Production Ready                                          ║
╚═════════════════════════════════════════════════════════════════════╝
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ThemisDB Legal Training Data RocksDB Generator
================================================

Generiert RocksDB Importer C++ Code für Legal Training Data
Analog zu generate_docs_rocksdb.py

This script generates a C++ program that imports the legal training data
JSON into a RocksDB database for use with ThemisDB.

Supports multiple datasets:
- joelNiklaus/MultiLegalPile (German subset) - RECOMMENDED
  URL: https://huggingface.co/datasets/joelNiklaus/MultiLegalPile
- elenanereiss/german-ler
  URL: https://huggingface.co/datasets/elenanereiss/german-ler
- Custom local datasets

Usage:
    python3 scripts/generate_legal_rocksdb.py --output data/legal_training.db
    python3 scripts/generate_legal_rocksdb.py --method cpp --output data/legal_training.db
"""

import argparse
import json
import logging
import sys
import io
from pathlib import Path

# Fix encoding on Windows
if sys.platform == 'win32':
    import codecs
    if hasattr(sys.stdout, 'buffer'):
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, errors='replace')
    if hasattr(sys.stderr, 'buffer'):
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, errors='replace')

# Configure logging with UTF-8 encoding
class UTF8StreamHandler(logging.StreamHandler):
    def __init__(self):
        super().__init__()
        # Force UTF-8 encoding with error handling
        if sys.platform == 'win32' and hasattr(sys.stderr, 'buffer'):
            self.stream = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('LegalRocksDBGenerator')
for handler in logger.handlers:
    logger.removeHandler(handler)
logger.addHandler(UTF8StreamHandler())


def generate_cpp_importer(output_db: str) -> str:
    """
    Generiert C++ Code für RocksDB Import
    
    Args:
        output_db: Path to output RocksDB database
        
    Returns:
        Path to generated C++ file
    """
    
    output_cpp = Path(output_db).parent / "import_legal_rocksdb.cpp"
    
    cpp_code = '''/**
 * @file import_legal_rocksdb.cpp
 * @brief Direct RocksDB importer for legal training data
 * 
 * Auto-generated by generate_legal_rocksdb.py
 * Imports HuggingFace legal-bert-de dataset into RocksDB database
 */

#include <rocksdb/db.h>
#include <rocksdb/slice.h>
#include <rocksdb/options.h>
#include <iostream>
#include <fstream>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

using json = nlohmann::json;
using namespace rocksdb;

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input.json> <output.db>" << std::endl;
        std::cerr << "Example: " << argv[0] << " legal_training_data.json legal_training.db" << std::endl;
        return 1;
    }

    std::string json_file = argv[1];
    std::string db_path = argv[2];

    std::cout << "========================================================" << std::endl;
    std::cout << "Legal Training Data RocksDB Importer" << std::endl;
    std::cout << "========================================================" << std::endl;
    std::cout << "Input JSON: " << json_file << std::endl;
    std::cout << "Output DB: " << db_path << std::endl;
    std::cout << std::endl;

    // Load JSON file
    std::cout << "[1/3] Loading JSON file..." << std::endl;
    std::ifstream input_file(json_file);
    if (!input_file.is_open()) {
        std::cerr << "Error: Cannot open file " << json_file << std::endl;
        return 1;
    }

    json data;
    try {
        input_file >> data;
        input_file.close();
    } catch (const std::exception& e) {
        std::cerr << "Error parsing JSON: " << e.what() << std::endl;
        return 1;
    }

    int total_docs = data["metadata"]["count"];
    std::cout << "✓ Loaded " << total_docs << " documents" << std::endl;
    std::cout << std::endl;

    // Open RocksDB database
    std::cout << "[2/3] Opening RocksDB database..." << std::endl;
    Options options;
    options.create_if_missing = true;
    options.compression = rocksdb::kSnappyCompression;
    
    DB* db = nullptr;
    Status status = DB::Open(options, db_path, &db);
    if (!status.ok()) {
        std::cerr << "Error opening database: " << status.ToString() << std::endl;
        return 1;
    }
    std::cout << "✓ RocksDB database opened at " << db_path << std::endl;
    std::cout << std::endl;

    // Import documents
    std::cout << "[3/3] Importing documents to RocksDB..." << std::endl;
    int doc_count = 0;
    int error_count = 0;
    
    WriteOptions write_options;
    // Trades durability for performance during batch import; use sync=true for production writes.
    // Disabling sync improves performance but risks data loss if the process crashes.
    write_options.sync = false;  // Better performance for batch imports
    
    for (const auto& doc : data["documents"]) {
        try {
            std::string key = doc["_key"];
            std::string value = doc.dump();
            
            status = db->Put(write_options, key, value);
            if (!status.ok()) {
                std::cerr << "Error writing key " << key << ": " << status.ToString() << std::endl;
                error_count++;
            }
            
            doc_count++;
            if (doc_count % 1000 == 0) {
                std::cout << "  Imported " << doc_count << "/" << total_docs 
                         << " documents..." << std::endl;
            }
        } catch (const std::exception& e) {
            std::cerr << "Error processing document: " << e.what() << std::endl;
            error_count++;
        }
    }

    // Cleanup and report
    delete db;

    std::cout << std::endl;
    std::cout << "========================================================" << std::endl;
    std::cout << "Import Complete!" << std::endl;
    std::cout << "========================================================" << std::endl;
    std::cout << "✓ Successfully imported: " << doc_count << " documents" << std::endl;
    if (error_count > 0) {
        std::cout << "⚠ Errors encountered: " << error_count << std::endl;
    }
    std::cout << "Database location: " << db_path << std::endl;
    std::cout << "========================================================" << std::endl;

    return (error_count > 0) ? 1 : 0;
}
'''
    
    with open(output_cpp, 'w', encoding='utf-8') as f:
        f.write(cpp_code)
    
    logger.info(f"✓ Generated C++ importer: {output_cpp}")
    return str(output_cpp)


def main():
    parser = argparse.ArgumentParser(
        description='Generate RocksDB import tools for legal training data'
    )
    parser.add_argument(
        '--method',
        choices=['cpp', 'direct'],
        default='cpp',
        help='Generation method (default: cpp)'
    )
    parser.add_argument(
        '--output',
        required=True,
        help='Output RocksDB database path'
    )
    
    args = parser.parse_args()
    
    logger.info("")
    logger.info("=" * 60)
    logger.info("Legal Training Data RocksDB Generator")
    logger.info("=" * 60)
    
    if args.method == 'cpp':
        cpp_file = generate_cpp_importer(args.output)
        logger.info("")
        logger.info("C++ importer generated successfully!")
        logger.info("")
        logger.info("To compile and run:")
        logger.info(f"  g++ -std=c++17 {cpp_file} -o import_legal_rocksdb \\")
        logger.info(f"      -lrocksdb -lpthread")
        logger.info(f"  ./import_legal_rocksdb legal_training_data.json {args.output}")
    
    logger.info("")
    logger.info("=" * 60)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
