"""
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            src-include-docs-align.py                          ║
  Version:         0.0.10                                             ║
  Last Modified:   2026-04-15 18:48:29                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟢 PRODUCTION-READY                             ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     504                                            ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Revision History:                                                   ║
    • ccff4b4df2  2026-04-07  feat: add src/include ↔ docs/de alignment check script an... ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: ✅ Production Ready                                          ║
╚═════════════════════════════════════════════════════════════════════╝
"""

#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TOOL_NAME: str = "src-include-docs-align"
TOOL_VERSION: str = "1.0.0"

# Top-level code directories to enumerate modules from.
CODE_ROOTS: List[str] = ["src", "include"]

# Source artefact extensions considered "code".
SOURCE_EXTENSIONS: Tuple[str, ...] = (".h", ".hpp", ".cpp", ".cc", ".cxx", ".c")

# Markdown files that are auto-generated by module_docs_builder.py and do NOT
# count as human-authored documentation.
GENERATED_DOC_NAMES: frozenset[str] = frozenset({"PRIMARY_SOURCES.md"})

# Default docs directory relative to repo root.
DEFAULT_DOCS_DIR: str = "docs/de"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def find_repo_root() -> Path:
    """Locate repository root via ``git``, falling back to script's grandparent."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return Path(result.stdout.strip())
    except Exception:
        return Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ModuleInfo:
    """Alignment data for one logical module."""

    name: str
    # Paths relative to repo root that contribute to this module.
    code_roots_present: List[str] = field(default_factory=list)
    # Total source artefact count across all code roots.
    source_file_count: int = 0
    # docs/de/<module>/ directory exists at all?
    docs_dir_exists: bool = False
    # All .md files found in docs/de/<module>/ (recursively).
    docs_md_files: List[str] = field(default_factory=list)
    # Human-authored .md files (excludes GENERATED_DOC_NAMES).
    docs_human_md_files: List[str] = field(default_factory=list)

    @property
    def is_documented(self) -> bool:
        """True when at least one human-authored doc exists."""
        return len(self.docs_human_md_files) > 0

    @property
    def coverage_status(self) -> str:
        if not self.docs_dir_exists:
            return "MISSING"
        if not self.docs_human_md_files:
            return "GENERATED_ONLY"
        return "DOCUMENTED"

    @property
    def doc_density(self) -> float:
        """Human-authored doc count / source file count (capped at 1.0)."""
        if self.source_file_count == 0:
            return 1.0 if self.is_documented else 0.0
        ratio = len(self.docs_human_md_files) / self.source_file_count
        return min(ratio, 1.0)


@dataclass
class AlignmentReport:
    """Aggregate report returned by :func:`run_alignment`."""

    modules: Dict[str, ModuleInfo] = field(default_factory=dict)
    docs_dir: str = DEFAULT_DOCS_DIR

    @property
    def all_module_names(self) -> List[str]:
        return sorted(self.modules.keys())

    @property
    def documented_modules(self) -> List[str]:
        return sorted(m for m, info in self.modules.items() if info.is_documented)

    @property
    def undocumented_modules(self) -> List[str]:
        return sorted(m for m, info in self.modules.items() if not info.is_documented)

    @property
    def missing_docs_dir(self) -> List[str]:
        return sorted(m for m, info in self.modules.items() if not info.docs_dir_exists)

    @property
    def generated_only(self) -> List[str]:
        return sorted(
            m
            for m, info in self.modules.items()
            if info.docs_dir_exists and not info.docs_human_md_files
        )

    @property
    def total(self) -> int:
        return len(self.modules)

    @property
    def coverage_pct(self) -> float:
        if self.total == 0:
            return 100.0
        return len(self.documented_modules) / self.total * 100.0


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------


def collect_code_modules(repo_root: Path) -> Dict[str, ModuleInfo]:
    """Enumerate all top-level module directories under CODE_ROOTS.

    Returns a mapping of ``module_name`` → :class:`ModuleInfo` with source
    file counts populated.
    """
    modules: Dict[str, ModuleInfo] = {}

    for root_name in CODE_ROOTS:
        root_path = repo_root / root_name
        if not root_path.is_dir():
            continue

        for entry in sorted(root_path.iterdir()):
            if not entry.is_dir():
                continue
            name = entry.name

            if name not in modules:
                modules[name] = ModuleInfo(name=name)

            info = modules[name]
            info.code_roots_present.append(f"{root_name}/{name}")

            # Count source artefacts recursively.
            for f in entry.rglob("*"):
                if f.suffix.lower() in SOURCE_EXTENSIONS and f.is_file():
                    info.source_file_count += 1

    return modules


def populate_docs_coverage(
    modules: Dict[str, ModuleInfo],
    repo_root: Path,
    docs_dir: str,
) -> None:
    """Fill documentation fields on each :class:`ModuleInfo` in-place."""
    docs_root = repo_root / docs_dir

    for name, info in modules.items():
        module_docs_dir = docs_root / name

        if not module_docs_dir.is_dir():
            continue

        info.docs_dir_exists = True

        for md_file in sorted(module_docs_dir.rglob("*.md")):
            relative = str(md_file.relative_to(repo_root))
            info.docs_md_files.append(relative)
            if md_file.name not in GENERATED_DOC_NAMES:
                info.docs_human_md_files.append(relative)


def run_alignment(
    repo_root: Path,
    docs_dir: str = DEFAULT_DOCS_DIR,
) -> AlignmentReport:
    """Run the full alignment check and return an :class:`AlignmentReport`."""
    modules = collect_code_modules(repo_root)
    populate_docs_coverage(modules, repo_root, docs_dir)
    return AlignmentReport(modules=modules, docs_dir=docs_dir)


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

_SEP = "─" * 72


def _status_icon(status: str) -> str:
    return {"DOCUMENTED": "✅", "GENERATED_ONLY": "⚠️ ", "MISSING": "❌"}.get(status, "?")


def format_text(report: AlignmentReport) -> str:
    lines: List[str] = []

    lines.append(_SEP)
    lines.append(f"  ThemisDB  src/ + include/  ↔  {report.docs_dir}  Alignment Report")
    lines.append(f"  Tool: {TOOL_NAME} v{TOOL_VERSION}")
    lines.append(_SEP)
    lines.append("")
    lines.append(f"  Total modules  : {report.total:>4}")
    lines.append(f"  Documented     : {len(report.documented_modules):>4}  (has ≥1 human-authored .md)")
    lines.append(f"  Generated-only : {len(report.generated_only):>4}  (only PRIMARY_SOURCES.md exists)")
    lines.append(f"  Missing docs/  : {len(report.missing_docs_dir):>4}  (no {report.docs_dir}/<module>/ at all)")
    lines.append(f"  Coverage       : {report.coverage_pct:>6.1f}%")
    lines.append("")

    if report.undocumented_modules:
        lines.append(_SEP)
        lines.append("  ❌  Undocumented modules (action required)")
        lines.append(_SEP)
        for m in report.undocumented_modules:
            info = report.modules[m]
            roots = ", ".join(info.code_roots_present)
            lines.append(
                f"  {_status_icon(info.coverage_status)}  {m:<30}  "
                f"src:{info.source_file_count:>4} files  roots:[{roots}]"
            )
        lines.append("")

    lines.append(_SEP)
    lines.append("  Module Coverage Detail")
    lines.append(_SEP)
    header = f"  {'Module':<30}  {'Status':<16}  {'Src':>5}  {'DocMD':>6}  {'Human':>6}"
    lines.append(header)
    lines.append("  " + "─" * 68)
    for m in report.all_module_names:
        info = report.modules[m]
        icon = _status_icon(info.coverage_status)
        lines.append(
            f"  {icon} {m:<29}  {info.coverage_status:<16}  "
            f"{info.source_file_count:>5}  {len(info.docs_md_files):>6}  "
            f"{len(info.docs_human_md_files):>6}"
        )
    lines.append("")

    if report.undocumented_modules:
        lines.append(
            f"  ⚠️  {len(report.undocumented_modules)} module(s) require documentation in {report.docs_dir}/."
        )
    else:
        lines.append("  ✅  All modules have human-authored documentation in docs/de/.")
    lines.append("")

    return "\n".join(lines)


def format_json(report: AlignmentReport) -> str:
    payload: dict = {
        "tool": TOOL_NAME,
        "version": TOOL_VERSION,
        "docs_dir": report.docs_dir,
        "summary": {
            "total_modules": report.total,
            "documented": len(report.documented_modules),
            "generated_only": len(report.generated_only),
            "missing_docs_dir": len(report.missing_docs_dir),
            "undocumented": len(report.undocumented_modules),
            "coverage_pct": round(report.coverage_pct, 2),
        },
        "undocumented_modules": report.undocumented_modules,
        "generated_only_modules": report.generated_only,
        "missing_docs_dir_modules": report.missing_docs_dir,
        "modules": {
            m: {
                "code_roots": info.code_roots_present,
                "source_file_count": info.source_file_count,
                "coverage_status": info.coverage_status,
                "docs_dir_exists": info.docs_dir_exists,
                "docs_md_count": len(info.docs_md_files),
                "docs_human_md_count": len(info.docs_human_md_files),
                "docs_human_md_files": info.docs_human_md_files,
            }
            for m, info in sorted(report.modules.items())
        },
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# GitHub Actions step summary
# ---------------------------------------------------------------------------


def write_step_summary(report: AlignmentReport) -> None:
    """Write a Markdown summary to $GITHUB_STEP_SUMMARY if available."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return

    lines: List[str] = []
    lines.append("## 🔍 src/ + include/ ↔ docs/de Alignment Report\n")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| **Total modules** | {report.total} |")
    lines.append(f"| **Documented** ✅ | {len(report.documented_modules)} |")
    lines.append(f"| **Generated-only** ⚠️ | {len(report.generated_only)} |")
    lines.append(f"| **Missing docs/** ❌ | {len(report.missing_docs_dir)} |")
    lines.append(f"| **Coverage** | {report.coverage_pct:.1f}% |")
    lines.append("")

    if report.undocumented_modules:
        lines.append("### ❌ Undocumented Modules\n")
        lines.append("| Module | Status | Source files | Code roots |")
        lines.append("|--------|--------|-------------|-----------|")
        for m in report.undocumented_modules:
            info = report.modules[m]
            lines.append(
                f"| `{m}` | {info.coverage_status} | {info.source_file_count} | "
                f"{', '.join(f'`{r}`' for r in info.code_roots_present)} |"
            )
        lines.append("")
    else:
        lines.append("✅ **All modules have human-authored documentation in `docs/de/`.**\n")

    lines.append("### 📋 Full Module Coverage Table\n")
    lines.append("| Module | Status | Src files | Doc .md | Human .md |")
    lines.append("|--------|--------|-----------|---------|-----------|")
    for m in report.all_module_names:
        info = report.modules[m]
        icon = _status_icon(info.coverage_status)
        lines.append(
            f"| {icon} `{m}` | {info.coverage_status} | {info.source_file_count} | "
            f"{len(info.docs_md_files)} | {len(info.docs_human_md_files)} |"
        )
    lines.append("")

    try:
        with open(summary_path, "a", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
    except OSError:
        pass  # non-fatal


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="src-include-docs-align",
        description=(
            "One-step content alignment check: compares all module directories "
            "in src/ and include/ against docs/de/ (or a custom --docs-dir) and "
            "reports documentation coverage gaps."
        ),
    )
    p.add_argument(
        "--repo-root",
        metavar="DIR",
        help="Repository root (auto-detected via git if omitted).",
    )
    p.add_argument(
        "--docs-dir",
        metavar="DIR",
        default=DEFAULT_DOCS_DIR,
        help=f"Primary German docs directory relative to repo root (default: {DEFAULT_DOCS_DIR}).",
    )
    p.add_argument(
        "--format",
        choices=["text", "json"],
        default="text",
        help="Output format (default: text).",
    )
    p.add_argument(
        "--output",
        metavar="PATH",
        help="Write report to this file instead of stdout.",
    )
    p.add_argument(
        "--fail-on-gaps",
        action="store_true",
        help="Exit 1 when undocumented modules are detected.",
    )
    p.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress informational messages on stdout.",
    )
    return p


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)

    # Resolve repo root.
    if args.repo_root:
        repo_root = Path(args.repo_root).resolve()
    else:
        repo_root = find_repo_root()

    if not repo_root.is_dir():
        print(f"ERROR: repo root not found: {repo_root}", file=sys.stderr)
        return 2

    if not args.quiet:
        print(f"{TOOL_NAME} v{TOOL_VERSION}: scanning {repo_root} …", file=sys.stderr)

    # Run alignment check.
    try:
        report = run_alignment(repo_root, docs_dir=args.docs_dir)
    except Exception as exc:  # pylint: disable=broad-except
        print(f"ERROR: alignment check failed: {exc}", file=sys.stderr)
        return 2

    # Format output.
    if args.format == "json":
        output_text = format_json(report)
    else:
        output_text = format_text(report)

    # Write output.
    if args.output:
        try:
            Path(args.output).write_text(output_text, encoding="utf-8")
            if not args.quiet:
                print(f"Report written to: {args.output}", file=sys.stderr)
        except OSError as exc:
            print(f"ERROR: cannot write report to {args.output}: {exc}", file=sys.stderr)
            return 2
    else:
        print(output_text)

    # Write GitHub Actions step summary.
    write_step_summary(report)

    # Emit GITHUB_OUTPUT counts if available.
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        try:
            with open(github_output, "a", encoding="utf-8") as fh:
                fh.write(f"total_modules={report.total}\n")
                fh.write(f"documented_modules={len(report.documented_modules)}\n")
                fh.write(f"undocumented_modules={len(report.undocumented_modules)}\n")
                fh.write(f"coverage_pct={report.coverage_pct:.1f}\n")
        except OSError:
            pass

    if not args.quiet:
        print(
            f"{TOOL_NAME}: {report.total} modules scanned, "
            f"{len(report.documented_modules)} documented, "
            f"{len(report.undocumented_modules)} undocumented "
            f"({report.coverage_pct:.1f}% coverage)",
            file=sys.stderr,
        )

    if args.fail_on_gaps and report.undocumented_modules:
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
