"""
╔═════════════════════════════════════════════════════════════════════╗
║ ThemisDB - Hybrid Database System                                   ║
╠═════════════════════════════════════════════════════════════════════╣
  File:            cep_rules_engine.py                                ║
  Version:         0.0.39                                             ║
  Last Modified:   2026-04-13 20:29:19                                ║
  Author:          unknown                                            ║
╠═════════════════════════════════════════════════════════════════════╣
  Quality Metrics:                                                    ║
    • Maturity Level:  🟢 PRODUCTION-READY                             ║
    • Quality Score:   100.0/100                                      ║
    • Total Lines:     498                                            ║
    • Open Issues:     TODOs: 0, Stubs: 0                             ║
╠═════════════════════════════════════════════════════════════════════╣
  Revision History:                                                   ║
    • 2a1fb04231  2026-03-03  Merge branch 'develop' into copilot/audit-src-module-docu... ║
    • 65b6fc41ed  2026-02-24  fix: resolve remaining Python (34) and PHP (23) error-han... ║
╠═════════════════════════════════════════════════════════════════════╣
  Status: ✅ Production Ready                                          ║
╚═════════════════════════════════════════════════════════════════════╝
"""

#!/usr/bin/env python3
"""
CEP (Complex Event Processing) Rules Engine - Phase 3 Implementation

Implements real-time pattern matching and alerting for:
- Substation overload detection
- Train delay cascading
- Signal failures
- Energy consumption anomalies
- Maintenance alerts

Based on event stream from ThemisDB ChangeFeed.
"""

import json
import requests
import time
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Callable
from dataclasses import dataclass, asdict
from enum import Enum
from collections import deque, defaultdict
import threading


class AlertSeverity(Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    HIGH = "high"
    CRITICAL = "critical"


class RuleType(Enum):
    """CEP Rule types"""
    THRESHOLD = "threshold"          # Simple threshold check
    PATTERN = "pattern"              # Pattern matching over time
    AGGREGATION = "aggregation"      # Windowed aggregation
    CORRELATION = "correlation"      # Multi-event correlation


@dataclass
class Alert:
    """Alert generated by CEP rule"""
    alert_id: str
    rule_id: str
    severity: AlertSeverity
    title: str
    description: str
    entity_id: str
    timestamp: datetime
    data: Dict
    
    def to_dict(self) -> Dict:
        """Convert to dictionary"""
        d = asdict(self)
        d['severity'] = self.severity.value
        d['timestamp'] = self.timestamp.isoformat()
        return d


@dataclass
class CEPRule:
    """Complex Event Processing Rule"""
    rule_id: str
    name: str
    description: str
    rule_type: RuleType
    entity_pattern: str  # Key prefix to match (e.g., "trains:", "substations:")
    condition: Callable[[Dict], bool]
    severity: AlertSeverity
    window_seconds: int = 60  # Time window for aggregation rules
    enabled: bool = True


class CEPRulesEngine:
    """Complex Event Processing Rules Engine"""
    
    def __init__(self, themis_url: str = "http://localhost:8765"):
        """Initialize CEP Engine"""
        self.themis_url = themis_url
        self.rules: Dict[str, CEPRule] = {}
        self.alerts: List[Alert] = []
        self.event_buffer: Dict[str, deque] = defaultdict(lambda: deque(maxlen=1000))
        self.running = False
        self.alert_callbacks: List[Callable[[Alert], None]] = []
        
        # Initialize default rules
        self._register_default_rules()
    
    def _register_default_rules(self):
        """Register default CEP rules"""
        
        # Rule 1: Substation Overload Detection
        self.add_rule(CEPRule(
            rule_id="SUBSTATION_OVERLOAD",
            name="Substation Overload",
            description="Detects when substation load exceeds 90% capacity",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="substation:",
            condition=lambda data: data.get("utilization_percent", 0) > 90,
            severity=AlertSeverity.HIGH,
        ))
        
        # Rule 2: Critical Overload (>95%)
        self.add_rule(CEPRule(
            rule_id="SUBSTATION_CRITICAL",
            name="Substation Critical Overload",
            description="Critical overload - immediate action required",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="substation:",
            condition=lambda data: data.get("utilization_percent", 0) > 95,
            severity=AlertSeverity.CRITICAL,
        ))
        
        # Rule 3: Train Delay Cascading
        self.add_rule(CEPRule(
            rule_id="DELAY_CASCADE",
            name="Delay Cascading Detection",
            description="Detects when train delay exceeds 15 minutes",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="trains:",
            condition=lambda data: data.get("delay_minutes", 0) > 15,
            severity=AlertSeverity.WARNING,
        ))
        
        # Rule 4: Signal Failure
        self.add_rule(CEPRule(
            rule_id="SIGNAL_FAILURE",
            name="Signal Failure",
            description="Detects signal failures",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="signals:",
            condition=lambda data: data.get("status") == "failure",
            severity=AlertSeverity.HIGH,
        ))
        
        # Rule 5: Energy Consumption Spike
        self.add_rule(CEPRule(
            rule_id="ENERGY_SPIKE",
            name="Energy Consumption Spike",
            description="Detects sudden energy consumption increase",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="train_energy:",
            condition=lambda data: data.get("power_kw", 0) > 8000,  # ICE max ~8000 kW
            severity=AlertSeverity.WARNING,
        ))
        
        # Rule 6: Vehicle Critical Fault
        self.add_rule(CEPRule(
            rule_id="VEHICLE_CRITICAL_FAULT",
            name="Vehicle Critical Fault",
            description="Detects critical vehicle faults",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="vehicle:",
            condition=lambda data: data.get("critical_faults", 0) > 0,
            severity=AlertSeverity.HIGH,
        ))
        
        # Rule 7: Maintenance Overdue
        self.add_rule(CEPRule(
            rule_id="MAINTENANCE_OVERDUE",
            name="Maintenance Overdue",
            description="Detects vehicles with overdue maintenance",
            rule_type=RuleType.THRESHOLD,
            entity_pattern="vehicle:",
            condition=self._check_maintenance_overdue,
            severity=AlertSeverity.WARNING,
        ))
    
    def _check_maintenance_overdue(self, data: Dict) -> bool:
        """Check if maintenance is overdue"""
        try:
            next_l3_due = data.get("next_l3_due")
            if next_l3_due:
                due_date = datetime.fromisoformat(next_l3_due)
                return due_date < datetime.now()
            return False
        except Exception:
            print("[WARN] CEP rule due-date check failed; assuming not overdue")
            return False
    
    def add_rule(self, rule: CEPRule):
        """Add a CEP rule"""
        self.rules[rule.rule_id] = rule
        print(f"Registered CEP rule: {rule.rule_id} - {rule.name}")
    
    def remove_rule(self, rule_id: str):
        """Remove a CEP rule"""
        if rule_id in self.rules:
            del self.rules[rule_id]
            print(f"Removed CEP rule: {rule_id}")
    
    def add_alert_callback(self, callback: Callable[[Alert], None]):
        """Add callback for alert notifications"""
        self.alert_callbacks.append(callback)
    
    def process_event(self, key: str, data: Dict):
        """Process a single event against all rules"""
        
        # Store event in buffer for windowed rules
        self.event_buffer[key].append({
            "timestamp": datetime.now(),
            "data": data
        })
        
        # Check all rules
        for rule in self.rules.values():
            if not rule.enabled:
                continue
            
            # Check if event matches rule pattern
            if not key.startswith(rule.entity_pattern):
                continue
            
            # Evaluate rule condition
            try:
                if rule.condition(data):
                    alert = self._create_alert(rule, key, data)
                    self._trigger_alert(alert)
            except Exception as e:
                print(f"Error evaluating rule {rule.rule_id}: {e}")
    
    def _create_alert(self, rule: CEPRule, entity_id: str, data: Dict) -> Alert:
        """Create alert from rule match"""
        alert_id = f"ALERT_{rule.rule_id}_{int(time.time() * 1000)}"
        
        # Build description with data
        description = rule.description
        if rule.rule_id == "SUBSTATION_OVERLOAD":
            util = data.get("utilization_percent", 0)
            load = data.get("current_load_mw", 0)
            description = f"Substation overload: {util:.1f}% utilization ({load:.1f} MW)"
        elif rule.rule_id == "DELAY_CASCADE":
            delay = data.get("delay_minutes", 0)
            train_num = data.get("train_number", "unknown")
            description = f"Train {train_num} delayed by {delay} minutes"
        elif rule.rule_id == "VEHICLE_CRITICAL_FAULT":
            faults = data.get("critical_faults", 0)
            vehicle_num = data.get("vehicle_number", "unknown")
            description = f"Vehicle {vehicle_num} has {faults} critical fault(s)"
        
        return Alert(
            alert_id=alert_id,
            rule_id=rule.rule_id,
            severity=rule.severity,
            title=rule.name,
            description=description,
            entity_id=entity_id,
            timestamp=datetime.now(),
            data=data,
        )
    
    def _trigger_alert(self, alert: Alert):
        """Trigger alert and notify callbacks"""
        # Store alert
        self.alerts.append(alert)
        
        # Print to console
        severity_emoji = {
            AlertSeverity.INFO: "ℹ️",
            AlertSeverity.WARNING: "⚠️",
            AlertSeverity.HIGH: "🔥",
            AlertSeverity.CRITICAL: "🚨",
        }
        emoji = severity_emoji.get(alert.severity, "❗")
        
        print(f"\n{emoji} ALERT [{alert.severity.value.upper()}] {alert.title}")
        print(f"   {alert.description}")
        print(f"   Entity: {alert.entity_id}")
        print(f"   Time: {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S')}")
        
        # Store in ThemisDB
        self._store_alert(alert)
        
        # Notify callbacks
        for callback in self.alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                print(f"Error in alert callback: {e}")
    
    def _store_alert(self, alert: Alert):
        """Store alert in ThemisDB"""
        try:
            url = f"{self.themis_url}/entities/alert:{alert.alert_id}"
            response = requests.put(url, json=alert.to_dict(), timeout=5)
            response.raise_for_status()
        except Exception as e:
            print(f"Warning: Failed to store alert: {e}")
    
    def start_monitoring(self, key_prefix: str = ""):
        """Start monitoring ThemisDB changefeed"""
        print(f"Starting CEP monitoring for key_prefix='{key_prefix}'...")
        self.running = True
        
        try:
            # Use ThemisDB changefeed
            url = f"{self.themis_url}/changefeed/stream"
            if key_prefix:
                url += f"?key_prefix={key_prefix}"
            
            print(f"Connecting to: {url}")
            
            response = requests.get(url, stream=True, timeout=None)
            response.raise_for_status()
            
            for line in response.iter_lines():
                if not self.running:
                    break
                
                if not line:
                    continue
                
                # Parse SSE data
                line_str = line.decode('utf-8')
                if line_str.startswith('data: '):
                    try:
                        data_str = line_str[6:]  # Remove 'data: ' prefix
                        event = json.loads(data_str)
                        
                        # Process event
                        operation = event.get("operation")
                        key = event.get("key")
                        new_val = event.get("new_val")
                        
                        if operation == "PUT" and new_val:
                            self.process_event(key, new_val)
                    except json.JSONDecodeError:
                        continue
                    except Exception as e:
                        print(f"Error processing event: {e}")
        
        except KeyboardInterrupt:
            print("\nStopping CEP monitoring...")
        except Exception as e:
            print(f"Error in CEP monitoring: {e}")
        finally:
            self.running = False
    
    def stop_monitoring(self):
        """Stop monitoring"""
        self.running = False
    
    def get_alerts(
        self,
        severity: Optional[AlertSeverity] = None,
        rule_id: Optional[str] = None,
        since: Optional[datetime] = None,
    ) -> List[Alert]:
        """Get filtered alerts"""
        alerts = self.alerts
        
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        
        if rule_id:
            alerts = [a for a in alerts if a.rule_id == rule_id]
        
        if since:
            alerts = [a for a in alerts if a.timestamp > since]
        
        return alerts
    
    def get_alert_summary(self) -> Dict:
        """Get alert summary statistics"""
        total = len(self.alerts)
        
        by_severity = {}
        for severity in AlertSeverity:
            count = sum(1 for a in self.alerts if a.severity == severity)
            by_severity[severity.value] = count
        
        by_rule = defaultdict(int)
        for alert in self.alerts:
            by_rule[alert.rule_id] += 1
        
        # Recent alerts (last hour)
        one_hour_ago = datetime.now() - timedelta(hours=1)
        recent = sum(1 for a in self.alerts if a.timestamp > one_hour_ago)
        
        return {
            "total_alerts": total,
            "recent_alerts_1h": recent,
            "by_severity": by_severity,
            "by_rule": dict(by_rule),
            "latest_alert": self.alerts[-1].to_dict() if self.alerts else None,
        }


def print_alert_callback(alert: Alert):
    """Example alert callback - send to external system"""
    # In production, this would send to:
    # - Email
    # - SMS
    # - Slack/Teams
    # - PagerDuty
    # - Custom webhook
    pass


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(description="CEP Rules Engine - Phase 3")
    parser.add_argument("--themis-url", default="http://localhost:8765", help="ThemisDB URL")
    parser.add_argument("--key-prefix", default="", help="Monitor specific key prefix")
    parser.add_argument("--test-mode", action="store_true", help="Run in test mode (generate test events)")
    
    args = parser.parse_args()
    
    # Initialize engine
    engine = CEPRulesEngine(themis_url=args.themis_url)
    
    # Add callback
    engine.add_alert_callback(print_alert_callback)
    
    print("="*60)
    print("CEP RULES ENGINE - PHASE 3")
    print("="*60)
    print(f"Registered {len(engine.rules)} rules:")
    for rule in engine.rules.values():
        print(f"  - {rule.rule_id}: {rule.name} [{rule.severity.value}]")
    print("="*60)
    
    if args.test_mode:
        # Test mode - generate test events
        print("\nRunning in TEST MODE - generating test events...\n")
        
        # Test substation overload
        engine.process_event("substation:UW_FFM_01", {
            "substation_id": "UW_FFM_01",
            "current_load_mw": 45.2,
            "capacity_mw": 50.0,
            "utilization_percent": 92.5,
        })
        
        # Test train delay
        engine.process_event("trains:ICE508", {
            "train_number": "ICE 508",
            "delay_minutes": 18,
            "current_station": "Frankfurt Hbf",
        })
        
        # Test critical vehicle fault
        engine.process_event("vehicle:403_658_6", {
            "vehicle_number": "403 658-6",
            "critical_faults": 1,
            "operational_status": "in_repair",
        })
        
        # Print summary
        print("\n" + "="*60)
        summary = engine.get_alert_summary()
        print("ALERT SUMMARY")
        print("="*60)
        print(f"Total Alerts: {summary['total_alerts']}")
        print(f"By Severity:")
        for severity, count in summary['by_severity'].items():
            if count > 0:
                print(f"  {severity:10s}: {count}")
        print("="*60)
    else:
        # Production mode - monitor changefeed
        try:
            engine.start_monitoring(key_prefix=args.key_prefix)
        except KeyboardInterrupt:
            print("\n\nShutting down CEP engine...")
            summary = engine.get_alert_summary()
            print(f"\nTotal alerts generated: {summary['total_alerts']}")


if __name__ == "__main__":
    main()
