import re
import os
from pathlib import Path

root = Path(r"C:\Projects\ThemisDB")

cmake_files = list(root.rglob('CMakeLists.txt')) + list(root.rglob('*.cmake'))

# regex to find tokens that look like file paths ending in source extensions
path_regex = re.compile(r"(?P<prefix>\$\{(?P<var>THEMIS_ROOT_DIR|CMAKE_SOURCE_DIR|CMAKE_CURRENT_SOURCE_DIR|CMAKE_CURRENT_LIST_DIR)\}|)(?P<path>[^\s\)\"',;]+\.(?:c|cc|cpp|cxx|cu|h|hpp))", re.IGNORECASE)

# also capture simple relative references starting with src/ or tests/ etc.
rel_regex = re.compile(r"(?P<path>(?:src|tests|benchmarks|plugins|tools|external|third_party)/[^\s\)\"',;]+\.(?:c|cc|cpp|cxx|cu|h|hpp))", re.IGNORECASE)

missing = {}
all_found = set()

for cm in cmake_files:
    try:
        text = cm.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        continue
    lines = text.splitlines()
    for i, line in enumerate(lines, start=1):
        for m in path_regex.finditer(line):
            var = m.group('var')
            path_part = m.group('path')
            if '$<' in path_part or '<' in path_part:
                continue
            if var in ('THEMIS_ROOT_DIR', 'CMAKE_SOURCE_DIR'):
                candidate = root / Path(path_part)
            elif var in ('CMAKE_CURRENT_SOURCE_DIR', 'CMAKE_CURRENT_LIST_DIR'):
                candidate = cm.parent / Path(path_part)
            else:
                # no var prefix but matched (unlikely)
                candidate = root / Path(path_part)
            candidate = candidate
            all_found.add(str(candidate))
            if not candidate.exists():
                missing.setdefault(str(candidate), []).append(f"{cm}:{i}:{line.strip()}")
        for m in rel_regex.finditer(line):
            path_part = m.group('path')
            candidate = root / Path(path_part)
            all_found.add(str(candidate))
            if not candidate.exists():
                missing.setdefault(str(candidate), []).append(f"{cm}:{i}:{line.strip()}")

out_dir = root / 'build'
out_dir.mkdir(parents=True, exist_ok=True)
out_file = out_dir / 'missing_cmake_sources.txt'
with out_file.open('w', encoding='utf-8') as f:
    f.write('# Missing source files referenced from CMake lists\n')
    f.write(f'# Generated by tools/find_missing_cmake_sources.py\n')
    f.write('\n')
    for path, refs in sorted(missing.items()):
        f.write(path + '\n')
        for r in refs:
            f.write('  ' + r + '\n')
        f.write('\n')

print(f'Checked {len(cmake_files)} CMake files, found {len(all_found)} referenced paths, {len(missing)} missing.')
print(f'Output written to: {out_file}')
