#!/usr/bin/env python3
"""
Extract generated code from Phase 3 Ollama results and commit to feature branches.
"""

import json
import os
import subprocess
import sys
from pathlib import Path


def extract_code_from_markdown(code_block: str) -> str:
    """Extract C++ code from markdown code block."""
    if code_block.startswith("```c++"):
        code = code_block[6:]  # Remove ```c++
    elif code_block.startswith("```"):
        code = code_block[3:]  # Remove ```
    else:
        code = code_block
    
    if code.endswith("```"):
        code = code[:-3]  # Remove trailing ```
    
    return code.strip()


def process_module(module: str) -> bool:
    """Process a single module's Phase 3 results."""
    
    results_file = f"ai_working/phase3_{module}_results.json"
    branch_name = f"feature/phase3-{module}-codegen"
    
    print(f"\n{'='*70}")
    print(f"Processing {module.upper()} Module - Extracting Ollama Code")
    print(f"{'='*70}\n")
    
    # Check if results file exists
    if not os.path.exists(results_file):
        print(f"[SKIP] Results file not found: {results_file}")
        return False
    
    # Load results
    with open(results_file) as f:
        results = json.load(f)
    
    # Check if we have code to extract
    code_results = results.get("results", [])
    if not code_results:
        print(f"[SKIP] No code results in {results_file}")
        return False
    
    print(f"[INFO] Found {len(code_results)} code snippets")
    
    # Create output file path
    output_file = f"src/{module}/phase3_generated_implementation.cpp"
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Combine all code snippets
    combined_code = f"""// Auto-generated by Ollama Phase 3 (codellama:latest)
// Module: {module}
// Date: Generated during Phase 3 code generation
// Total tasks: {results.get('tasks_total')}
// Valid: {results.get('syntax_ok')}/{results.get('tasks_generated')}
//
// This file contains code snippets generated by Ollama for the {module} module.
// Each snippet addresses specific gaps identified in Phase 2 gap analysis.

#pragma once

"""
    
    task_count = 0
    for result in code_results:
        task_id = result.get("task_id", "unknown")
        priority = result.get("priority", "UNKNOWN")
        effort = result.get("effort_hours", 0)
        syntax_ok = result.get("syntax_ok", False)
        code = result.get("code", "")
        
        if not code:
            print(f"  [SKIP] Task {task_id}: No code content")
            continue
        
        # Extract code from markdown
        extracted = extract_code_from_markdown(code)
        
        # Add comment header
        combined_code += f"""
// ============================================================================
// Task {task_id} - Priority: {priority}, Effort: {effort}h
// Status: {'OK' if syntax_ok else 'SYNTAX ERROR'}
// ============================================================================
{extracted}

"""
        task_count += 1
    
    # Write combined file
    with open(output_file, 'w') as f:
        f.write(combined_code)
    
    print(f"[OK] Extracted {task_count} code snippets")
    print(f"[OK] Written to: {output_file}")
    print(f"[OK] File size: {len(combined_code)} bytes")
    
    # Switch to feature branch
    result = subprocess.run(
        ["git", "checkout", branch_name],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"[ERROR] Failed to checkout {branch_name}: {result.stderr}")
        return False
    
    print(f"[OK] Switched to branch: {branch_name}")
    
    # Add the generated code file
    subprocess.run(["git", "add", output_file], capture_output=True)
    print(f"[OK] Added {output_file} to staging")
    
    # Commit with message including code stats
    commit_msg = f"Phase 3: Add Ollama-generated code for {module}\n\n- Tasks: {results.get('tasks_generated')}/{results.get('tasks_total')}\n- Valid syntax: {results.get('syntax_ok')}/{results.get('tasks_total')}\n- Output file: {output_file}\n- Model: codellama:latest"
    
    result = subprocess.run(
        ["git", "commit", "-m", commit_msg],
        capture_output=True,
        text=True
    )
    
    if result.returncode == 0:
        print(f"[OK] Committed: {commit_msg.split(chr(10))[0]}")
    else:
        print(f"[WARN] Commit result: {result.stdout}")
    
    return True


def main():
    """Process all modules with Phase 3 results."""
    
    print("\n" + "="*70)
    print("PHASE 3: EXTRACT OLLAMA CODE AND COMMIT TO BRANCHES")
    print("="*70)
    
    modules = ["storage", "analytics", "index"]
    
    for module in modules:
        try:
            process_module(module)
        except Exception as e:
            print(f"[ERROR] Failed to process {module}: {e}")
    
    print("\n" + "="*70)
    print("PHASE 3: EXTRACTION COMPLETE")
    print("="*70)
    print("\nNext steps:")
    print("1. Review changes: git diff")
    print("2. Force push branches: git push -f origin feature/phase3-<module>-codegen")
    print("3. PRs will auto-update with new code")


if __name__ == "__main__":
    main()
