# CMake-Only Build System - Quick Start

option(THEMIS_ENABLE_PACKAGE_SYSTEM "Enable multi-platform package building targets" ON)
option(THEMIS_ENABLE_DOCKER_SYSTEM "Enable Docker build targets" ON)

# Include multi-platform package system (optional)
if(THEMIS_ENABLE_PACKAGE_SYSTEM)
    include(cmake/VcpkgPackageSystem.cmake OPTIONAL)
endif()

# Include Docker build system (optional)
if(THEMIS_ENABLE_DOCKER_SYSTEM)
    include(cmake/DockerBuildSystem.cmake OPTIONAL)
endif()

# ============================================================================
# Usage Instructions
# ============================================================================

if(CMAKE_SCRIPT_MODE_FILE)
    message(STATUS "==========================================")
    message(STATUS "ThemisDB CMake-Only Build System")
    message(STATUS "==========================================")
    message(STATUS "")
    message(STATUS "Available CMake Presets:")
    message(STATUS "")
    message(STATUS "Windows:")
    message(STATUS "  windows-release         - Windows Release build (MSVC)")
    message(STATUS "  windows-debug           - Windows Debug build (MSVC)")
    message(STATUS "  windows-release-prebuilt- Windows with pre-built packages")
    message(STATUS "")
    message(STATUS "Linux:")
    message(STATUS "  linux-release           - Linux Release build (GCC)")
    message(STATUS "  linux-debug             - Linux Debug build (GCC)")
    message(STATUS "  linux-release-prebuilt  - Linux with pre-built packages")
    message(STATUS "")
    message(STATUS "Editions:")
    message(STATUS "  minimal                 - MINIMAL edition (no LLM/GPU)")
    message(STATUS "  enterprise              - ENTERPRISE edition")
    message(STATUS "  hyperscaler             - HYPERSCALER edition")
    message(STATUS "")
    message(STATUS "Package Building:")
    message(STATUS "  package-builder-windows-release")
    message(STATUS "  package-builder-linux-release")
    message(STATUS "")
    message(STATUS "==========================================")
    message(STATUS "Quick Start:")
    message(STATUS "")
    message(STATUS "# 1. Configure with preset")
    message(STATUS "cmake --preset windows-release")
    message(STATUS "")
    message(STATUS "# 2. Build")
    message(STATUS "cmake --build --preset windows-release")
    message(STATUS "")
    message(STATUS "# 3. Test")
    message(STATUS "ctest --preset windows-release")
    message(STATUS "")
    message(STATUS "# Build packages (if enabled)")
    message(STATUS "cmake --build build-windows-release --target build-packages-linux-release")
    message(STATUS "")
    message(STATUS "# Build Docker image (if enabled)")
    message(STATUS "cmake --build build-windows-release --target docker-build-community-release")
    message(STATUS "")
    message(STATUS "# Full workflow")
    message(STATUS "cmake --workflow --preset windows-full-workflow")
    message(STATUS "==========================================")
endif()
