# Deprecation and style checks run at configure time.
# Currently: warn on use of `add_definitions()` which is discouraged.

# Gather only Themis-owned CMake helper files to scan.
file(GLOB_RECURSE _themis_cmake_scan_files
    "${CMAKE_SOURCE_DIR}/cmake/*.cmake"
)
list(FILTER _themis_cmake_scan_files EXCLUDE REGEX "deprecated_checks\\.cmake$")

set(_themis_add_definitions_hits "")
foreach(_themis_scan_file IN LISTS _themis_cmake_scan_files)
    if(EXISTS "${_themis_scan_file}")
        file(STRINGS "${_themis_scan_file}" _themis_scan_lines)
        set(_themis_scan_content "")
        foreach(_themis_scan_line IN LISTS _themis_scan_lines)
            string(REGEX MATCH "^[ \t]*#" _themis_is_comment "${_themis_scan_line}")
            if(_themis_is_comment)
                continue()
            endif()
            string(APPEND _themis_scan_content "${_themis_scan_line}\n")
        endforeach()

        string(TOLOWER "${_themis_scan_content}" _themis_scan_lc)
        string(FIND "${_themis_scan_lc}" "add_definitions(" _themis_found_pos)
        if(NOT _themis_found_pos EQUAL -1)
            list(APPEND _themis_add_definitions_hits "${_themis_scan_file}")
            message(WARNING "Deprecated CMake command 'add_definitions()' found in: ${_themis_scan_file}\n  Recommend: replace with target_compile_definitions(<target> PUBLIC|PRIVATE) for modern scoping.")
        endif()
    endif()
endforeach()

# Write a report file with exact locations and suggested replacement snippets
file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/logs")
set(_themis_report_file "${CMAKE_BINARY_DIR}/logs/add_definitions_report.txt")
file(WRITE "${_themis_report_file}" "ThemisDB - add_definitions() usage report\nGenerated by cmake/deprecated_checks.cmake\n\n")
if(_themis_add_definitions_hits)
    foreach(_hit IN LISTS _themis_add_definitions_hits)
        file(APPEND "${_themis_report_file}" "Found: ${_hit}\n")
        # Provide a generic replacement hint (manual target mapping required)
        file(APPEND "${_themis_report_file}" "Suggested: Replace 'add_definitions(-DFOO)' with\n  target_compile_definitions(<target> PRIVATE -DFOO)\n  or use add_compile_definitions(-DFOO) for directory/global scope (CMake >=3.12)\n\n")
    endforeach()
else()
    file(APPEND "${_themis_report_file}" "No occurrences of add_definitions() found.\n")
endif()

message(STATUS "add_definitions() report written to: ${_themis_report_file}")
