function(themis_get_edition_rank out_var edition_name)
    string(TOUPPER "${edition_name}" _edition)
    set(_rank -1)

    if(_edition STREQUAL "MINIMAL")
        set(_rank 0)
    elseif(_edition STREQUAL "COMMUNITY")
        set(_rank 1)
    elseif(_edition STREQUAL "ENTERPRISE")
        set(_rank 2)
    elseif(_edition STREQUAL "HYPERSCALER")
        set(_rank 3)
    endif()

    set(${out_var} "${_rank}" PARENT_SCOPE)
endfunction()

function(themis_is_edition_at_least out_var required_edition)
    themis_get_edition_rank(_current_rank "${THEMIS_EDITION}")
    themis_get_edition_rank(_required_rank "${required_edition}")

    if(_current_rank GREATER_EQUAL _required_rank)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(themis_any_feature_enabled out_var)
    set(_enabled FALSE)
    foreach(_feature ${ARGN})
        if(DEFINED ${_feature})
            if(${_feature})
                set(_enabled TRUE)
                break()
            endif()
        endif()
    endforeach()

    set(${out_var} ${_enabled} PARENT_SCOPE)
endfunction()

function(themis_suite_group_for_name out_var suite_name)
    string(TOLOWER "${suite_name}" _name)
    set(_group "core")

    if(_name MATCHES "voice")
        set(_group "voice")
    elseif(_name MATCHES "llm|lora|rag|prompt|embedding|extended_context|judge|speculative|kv_cache|llama|model_|nlp|fewshot|openai|inference|quantization|qlora")
        set(_group "llm")
    elseif(_name MATCHES "gpu|cuda|hip|vulkan|flash_attention|fused|mixed_precision|vram|multi_gpu|rotary")
        set(_group "gpu")
    elseif(_name MATCHES "content|image_analysis|video_processor|text_extraction|office|ocr|pdf|blob")
        set(_group "content")
    elseif(_name MATCHES "grpc|postgres|http|websocket|graphql|mqtt|mcp|sse|wire_protocol|api_endpoint|stream_protocol")
        set(_group "network")
    elseif(_name MATCHES "distributed|replication|shard|changefeed|gossip|wal_apply_grpc|service_mesh|consensus|paxos")
        set(_group "distributed")
    elseif(_name MATCHES "security|compliance|governance|hsm|audit|policy|ethics")
        set(_group "security")
    elseif(_name MATCHES "timeseries")
        set(_group "timeseries")
    elseif(_name MATCHES "graph|pagerank")
        set(_group "graph")
    elseif(_name MATCHES "geo|spatial")
        set(_group "geo")
    endif()

    set(${out_var} "${_group}" PARENT_SCOPE)
endfunction()

function(themis_suite_group_enabled out_var suite_group)
    set(_enabled TRUE)

    if(suite_group STREQUAL "llm")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_LLM)
    elseif(suite_group STREQUAL "gpu")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_GPU THEMIS_ENABLE_CUDA THEMIS_ENABLE_HIP THEMIS_ENABLE_VULKAN)
    elseif(suite_group STREQUAL "content")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_CONTENT THEMIS_ENABLE_CONTENT_PROCESSORS)
    elseif(suite_group STREQUAL "voice")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_VOICE_ASSISTANT)
    elseif(suite_group STREQUAL "network")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_GRPC THEMIS_ENABLE_HTTP_SERVER THEMIS_ENABLE_HTTP2 THEMIS_ENABLE_HTTP3 THEMIS_ENABLE_WEBSOCKET THEMIS_ENABLE_POSTGRES_WIRE THEMIS_ENABLE_MCP THEMIS_ENABLE_GRAPHQL THEMIS_ENABLE_MQTT THEMIS_ENABLE_SSE)
    elseif(suite_group STREQUAL "distributed")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_GRPC THEMIS_ENABLE_SERVICE_MESH THEMIS_ENABLE_SHARDING THEMIS_ENABLE_CHANGEFEED)
        if(NOT _enabled)
            themis_is_edition_at_least(_enabled ENTERPRISE)
        endif()
    elseif(suite_group STREQUAL "security")
        themis_any_feature_enabled(_enabled THEMIS_ENABLE_TRACING THEMIS_ENABLE_HSM_REAL THEMIS_ENABLE_S3 THEMIS_ENABLE_AZURE THEMIS_ENABLE_WEBDAV)
        if(NOT _enabled)
            themis_is_edition_at_least(_enabled ENTERPRISE)
        endif()
    endif()

    set(${out_var} ${_enabled} PARENT_SCOPE)
endfunction()

function(themis_is_suite_enabled out_var suite_name)
    themis_suite_group_for_name(_group "${suite_name}")
    themis_suite_group_enabled(_enabled "${_group}")
    set(${out_var} ${_enabled} PARENT_SCOPE)
endfunction()

function(themis_log_suite_context label)
    message(STATUS "${label} gating: edition=${THEMIS_EDITION} benchmarks=${THEMIS_BUILD_BENCHMARKS} tests=${THEMIS_BUILD_TESTS} llm=${THEMIS_ENABLE_LLM} gpu=${THEMIS_ENABLE_GPU} cuda=${THEMIS_ENABLE_CUDA} hip=${THEMIS_ENABLE_HIP} content=${THEMIS_ENABLE_CONTENT} grpc=${THEMIS_ENABLE_GRPC} http=${THEMIS_ENABLE_HTTP_SERVER} ws=${THEMIS_ENABLE_WEBSOCKET} pgwire=${THEMIS_ENABLE_POSTGRES_WIRE}")
endfunction()

function(themis_report_benchmark_coverage benchmark_dir benchmark_cmake_file)
    file(GLOB _benchmark_sources RELATIVE "${benchmark_dir}"
        "${benchmark_dir}/bench*.cpp"
        "${benchmark_dir}/llm_bench.cpp")

    # Use configured targets from this CMake directory so dynamically added
    # targets (auto-registration) are counted correctly.
    get_property(_target_matches DIRECTORY "${benchmark_dir}" PROPERTY BUILDSYSTEM_TARGETS)
    set(_registered_targets "")
    foreach(_match ${_target_matches})
        set(_target_name "${_match}")
        if(_target_name MATCHES "^bench_" OR _target_name MATCHES "^benchmark_" OR _target_name STREQUAL "llm_bench")
            list(APPEND _registered_targets "${_target_name}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _registered_targets)

    foreach(_source_file ${_benchmark_sources})
        get_filename_component(_suite_name "${_source_file}" NAME_WE)
        if(NOT _suite_name IN_LIST _registered_targets)
            themis_suite_group_for_name(_group "${_suite_name}")
            themis_suite_group_enabled(_enabled "${_group}")
            if(_enabled)
                set(_bucket "_unregistered_current_${_group}")
                list(APPEND _unregistered_current "${_suite_name}")
            else()
                set(_bucket "_unregistered_disabled_${_group}")
                list(APPEND _unregistered_disabled "${_suite_name}")
            endif()
            list(APPEND ${_bucket} "${_suite_name}")
        endif()
    endforeach()

    foreach(_registered_target ${_registered_targets})
        themis_is_suite_enabled(_enabled "${_registered_target}")
        if(NOT _enabled)
            list(APPEND _registered_but_disabled "${_registered_target}")
        endif()
    endforeach()

    list(LENGTH _benchmark_sources _benchmark_source_count)
    list(LENGTH _registered_targets _registered_target_count)
    list(LENGTH _unregistered_current _unregistered_current_count)
    list(LENGTH _unregistered_disabled _unregistered_disabled_count)
    list(LENGTH _registered_but_disabled _registered_but_disabled_count)
    message(STATUS "Benchmark coverage: ${_registered_target_count}/${_benchmark_source_count} sources registered; ${_unregistered_current_count} current-config suites still unregistered; ${_unregistered_disabled_count} gated by current edition/features; ${_registered_but_disabled_count} registered targets currently outside effective feature gates")

    foreach(_group core graph geo timeseries content network distributed security llm gpu voice)
        set(_current_var "_unregistered_current_${_group}")
        if(DEFINED ${_current_var})
            list(LENGTH ${_current_var} _group_count)
            if(_group_count GREATER 0)
                list(JOIN ${_current_var} ", " _group_items)
                message(STATUS "  Missing benchmark group [${_group}] (${_group_count}): ${_group_items}")
            endif()
        endif()
    endforeach()

    if(_registered_but_disabled_count GREATER 0)
        list(JOIN _registered_but_disabled ", " _registered_disabled_items)
        message(STATUS "  Registered-but-disabled benchmark targets: ${_registered_disabled_items}")
    endif()
endfunction()

function(themis_report_test_selection test_dir included_sources)
    file(GLOB_RECURSE _all_test_sources RELATIVE "${test_dir}" "${test_dir}/test_*.cpp")

    set(_included_names "")
    foreach(_included_source ${included_sources})
        get_filename_component(_included_name "${_included_source}" NAME_WE)
        list(APPEND _included_names "${_included_name}")
    endforeach()
    list(REMOVE_DUPLICATES _included_names)

    foreach(_test_source ${_all_test_sources})
        get_filename_component(_test_name "${_test_source}" NAME_WE)
        if(NOT _test_name IN_LIST _included_names)
            list(APPEND _excluded_names "${_test_name}")
            themis_suite_group_for_name(_group "${_test_name}")
            set(_bucket "_excluded_${_group}")
            list(APPEND ${_bucket} "${_test_name}")
            themis_is_suite_enabled(_enabled "${_test_name}")
            if(_enabled)
                list(APPEND _excluded_current "${_test_name}")
            else()
                list(APPEND _excluded_disabled "${_test_name}")
            endif()
        endif()
    endforeach()

    list(LENGTH _all_test_sources _all_test_count)
    list(LENGTH _included_names _included_count)
    list(LENGTH _excluded_names _excluded_count)
    list(LENGTH _excluded_current _excluded_current_count)
    list(LENGTH _excluded_disabled _excluded_disabled_count)
    message(STATUS "Test selection: ${_included_count}/${_all_test_count} suites included for edition=${THEMIS_EDITION}; ${_excluded_current_count} currently-eligible suites excluded by focused-target rules; ${_excluded_disabled_count} gated by current edition/features")

    foreach(_group core graph geo timeseries content network distributed security llm gpu voice)
        set(_excluded_var "_excluded_${_group}")
        if(DEFINED ${_excluded_var})
            list(LENGTH ${_excluded_var} _group_count)
            if(_group_count GREATER 0)
                message(STATUS "  Excluded test group [${_group}]: ${_group_count}")
            endif()
        endif()
    endforeach()
endfunction()