# ThemisDB Multi-Platform Package System - Modular packaging entrypoint

include_guard(GLOBAL)

set(_themis_packaging_dir "${CMAKE_CURRENT_LIST_DIR}/packaging")

if(NOT EXISTS "${_themis_packaging_dir}/PackageCommon.cmake")
    message(WARNING "Packaging modules not found at ${_themis_packaging_dir}")
    return()
endif()

include(${_themis_packaging_dir}/PackageCommon.cmake)
include(${_themis_packaging_dir}/PackageDeps.cmake)
include(${_themis_packaging_dir}/PackageZip.cmake)
include(${_themis_packaging_dir}/PackageMsi.cmake)
include(${_themis_packaging_dir}/PackageInstaller.cmake)
include(${_themis_packaging_dir}/PackageTgz.cmake)

if(NOT TARGET package-all)
    add_custom_target(package-all COMMENT "Build all available package types")
endif()

if(TARGET package-deps)
    add_dependencies(package-all package-deps)
endif()
if(TARGET package-zip)
    add_dependencies(package-all package-zip)
endif()
if(TARGET package-msi)
    add_dependencies(package-all package-msi)
endif()
if(TARGET package-installer)
    add_dependencies(package-all package-installer)
endif()
if(TARGET package-tgz)
    add_dependencies(package-all package-tgz)
endif()

message(STATUS "==========================================")
message(STATUS "Multi-Platform Package System")
message(STATUS "==========================================")
message(STATUS "Package store: ${THEMIS_PACKAGE_STORE}")
message(STATUS "Build configuration: ${THEMIS_BUILD_CONFIG}")
message(STATUS "")
message(STATUS "Available package targets:")
message(STATUS "  package-deps            - Dependency package build (vcpkg)")
message(STATUS "  package-zip             - ZIP package")
message(STATUS "  package-msi             - MSI package (Windows)")
message(STATUS "  package-installer       - Installer package (NSIS/WiX)")
message(STATUS "  package-tgz             - tar.gz package")
message(STATUS "  package-all             - Aggregate package target")
message(STATUS "  package-tools-report    - Packaging tool availability")
message(STATUS "")
message(STATUS "Compatibility aliases:")
message(STATUS "  build-all-packages")
message(STATUS "  build-packages-windows-debug")
message(STATUS "  build-packages-windows-release")
message(STATUS "  build-packages-linux-debug")
message(STATUS "  build-packages-linux-release")
message(STATUS "==========================================")
