/**
 * @file build_info.h
 * @brief Auto-generated build metadata constants.
 *
 * Contains preprocessor definitions for build channel, git SHA,
 * version string, and build signature injected by cmake/BuildInfo.cmake.
 * Do not edit manually — regenerated on every cmake configure run.
 */

// Auto-generated by cmake/BuildInfo.cmake – DO NOT EDIT MANUALLY.
// Regenerated on every cmake configure run.
#pragma once

// Build channel: "official" for signed CI releases, "community" for all other
// builds.  Operators MUST NOT set this to "official" in their own builds;
// the value is only meaningful when accompanied by a valid THEMIS_BUILD_SIG.
#define THEMIS_BUILD_CHANNEL "community"

// Short Git SHA (7 hex chars) of the source tree at configure time.
// Falls back to "unknown" when the build directory is not inside a git repo.
#define THEMIS_BUILD_ID "79b0fb32"

// UTC ISO-8601 build timestamp. Uses SOURCE_DATE_EPOCH when set; otherwise
// BuildInfo.cmake falls back to deterministic git metadata when available.
#define THEMIS_BUILD_TIMESTAMP "2026-07-19T17:27:59Z"

// Ed25519 signature over the canonical manifest string:
//   "<channel>|<version>|<build_id>|<timestamp>"
// Base64-encoded (standard alphabet).  Empty string for community builds.
#define THEMIS_BUILD_SIG ""

// Ed25519 public key used to verify THEMIS_BUILD_SIG.
// Base64-encoded (standard alphabet, 32-byte raw key → 44-char string).
// This is the ThemisDB project's official verification key and must never
// be changed without a coordinated key-rotation release.
#define THEMIS_BUILD_PUBKEY "11qYAYKxCrfVS/7TyWQHOg7hcvPapiMlrwIaaPcHURo="
