/**
 * @file schema_migration_tester.h
 * @brief Canonical Doxygen file header for ThemisDB-generated maturity metadata.
 * @version 0.0.15
 * @note Maturity: 🟢 PRODUCTION-READY
 * @note Score: 86/100
 * @note Gap Summary: total=3; TODO=1, Stub=1, Unimpl=0, Mock=1, Sim=0, Debt=0, C=n/a, H=n/a, M=n/a, L=n/a
 * @note Status: Production Ready
 * @note This block is auto-generated and will be overwritten.
 */


// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 ThemisDB Contributors

#pragma once

#include "metadata/schema_manager.h"
#include "metadata/schema_version_manager.h"
#include "storage/rocksdb_wrapper.h"
#include "index/secondary_index.h"
#include <functional>
#include <memory>
#include <string>
#include <vector>

namespace themis {
namespace updates {

/**
 * @brief Result of a single test case executed against the staging migration.
 */
struct MigrationTestCaseResult {
    std::string name;   ///< Test case name
    bool passed = false;
    std::string error_message = {};
};

/**
 * @brief Aggregate result from SchemaMigrationTester::testMigration().
 */
struct MigrationTestResult {
    bool success = false;          ///< True only if all built-in and custom tests pass
    std::string error_message;     ///< First fatal error encountered, if any
    std::string staging_db_path;   ///< Path to the staging database (for inspection)
    std::string migration_script;  ///< DDL preview generated by SchemaVersionManager

    /// Per-test results (built-in validations + user-supplied test cases).
    std::vector<MigrationTestCaseResult> test_results;

    /// Convenience: number of test cases that passed.
    size_t passedCount() const;

    /// Convenience: number of test cases that failed.
    size_t failedCount() const;
};

/**
 * @brief A user-defined test case to run against the staging database after
 *        the schema migration has been applied.
 *
 * The callback receives a read-only view of the staged SchemaManager and
 * SchemaVersionManager. It should return true on pass and false (optionally
 * populating @p error_out) on failure.
 */
struct MigrationTestCase {
    std::string name;
    std::function<bool(
        const SchemaManager& staged_schema,
        const SchemaVersionManager& staged_version_mgr,
        std::string& error_out
    )> test_fn;
};

/**
 * @brief Framework for testing schema migrations on an isolated staging
 *        environment before applying them to production.
 *
 * ### Workflow
 * ```
 * SchemaMigrationTester tester;
 * tester.addTestCase({"check_column_exists", [](auto& sm, auto&, auto& err) {
 *     auto t = sm.getTable("users");
 *     if (!t) { err = "table not found"; return false; }
 *     for (auto& p : t->properties)
 *         if (p.name == "email") return true;
 *     err = "column 'email' missing";
 *     return false;
 * }});
 *
 * auto result = tester.testMigration("users", from_schema, to_schema);
 * if (result.success) {
 *     tester.promoteToProduction(result, prod_db, prod_schema, prod_version, "users", to_schema);
 * }
 * ```
 *
 * ### Thread-safety
 * Not thread-safe. Use a single SchemaMigrationTester per migration sequence.
 *
 * ### Constraints
 * - Each testMigration() call opens a fresh staging RocksDB instance under
 *   @p Config::staging_directory.
 * - The staging directory is created automatically if it does not exist.
 * - The staging DB is cleaned up according to Config::cleanup_* flags.
 */
class SchemaMigrationTester {
public:
    /**
     * @brief Configuration for the staging tester.
     */
    struct Config {
        /// Root directory under which per-run staging databases are created.
        std::string staging_directory = "/tmp/themis_staging";

        /// Remove the staging DB after a successful test run.
        bool cleanup_staging_on_success = true;

        /// Remove the staging DB after a failed test run (default: keep for debugging).
        bool cleanup_staging_on_failure = false;
    };

    SchemaMigrationTester();
    explicit SchemaMigrationTester(const Config& config);
    ~SchemaMigrationTester() = default;

    // Non-copyable
    SchemaMigrationTester(const SchemaMigrationTester&) = delete;
    SchemaMigrationTester& operator=(const SchemaMigrationTester&) = delete;

    /**
     * @brief Register an additional test case to run against the staged migration.
     *
     * Test cases are executed in registration order after the built-in
     * validations have passed.
     *
     * @param tc  Test case descriptor (name + callback).
     */
    void addTestCase(MigrationTestCase tc);

    /**
     * @brief Apply @p to_schema on an isolated staging DB and run all tests.
     *
     * Built-in validations performed:
     *  1. No duplicate column names in @p to_schema.
     *  2. validateMigration() reports no errors.
     *  3. @p to_schema is registered with the staging SchemaManager.
     *  4. A schema version snapshot can be created.
     *  5. generateMigrationScript() produces a non-empty DDL string when
     *     @p from_schema differs from @p to_schema.
     *
     * @param table_name  Name of the table being migrated.
     * @param from_schema Current (production) schema.
     * @param to_schema   Proposed new schema.
     * @return Detailed test result including per-test pass/fail.
     */
    MigrationTestResult testMigration(
        const std::string& table_name,
        const SchemaManager::TableSchema& from_schema,
        const SchemaManager::TableSchema& to_schema
    );

    /**
     * @brief Apply @p to_schema to the production database.
     *
     * May only be called after testMigration() returned a successful result.
     * Records the change with SchemaVersionManager and updates SchemaManager.
     *
     * @param result           Successful result from testMigration().
     * @param production_db    RocksDB wrapper for the production database.
     * @param production_schema SchemaManager for the production database.
     * @param production_version SchemaVersionManager for the production database.
     * @param table_name       Name of the table being migrated.
     * @param to_schema        New schema to apply.
     * @param author           Identity of the person performing the migration.
     * @return true if the migration was applied successfully.
     */
    bool promoteToProduction(
        const MigrationTestResult& result,
        RocksDBWrapper& production_db,
        SchemaManager& production_schema,
        SchemaVersionManager& production_version,
        const std::string& table_name,
        const SchemaManager::TableSchema& to_schema,
        const std::string& author = "migration-tester"
    );

private:
    Config config_;
    std::vector<MigrationTestCase> user_test_cases_;

    /// Generate a unique staging DB path (timestamp-based).
    std::string makeStagingPath() const;

    /// Run built-in validations; appends to @p results, returns false on first fatal error.
    bool runBuiltinTests(
        const std::string& table_name,
        const SchemaManager::TableSchema& from_schema,
        const SchemaManager::TableSchema& to_schema,
        SchemaManager& staged_schema,
        SchemaVersionManager& staged_version,
        std::vector<MigrationTestCaseResult>& results,
        std::string& migration_script_out
    );
};

} // namespace updates
} // namespace themis
