apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "themisdb.fullname" . }}-config
  labels:
    {{- include "themisdb.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.themisdb.config | nindent 4 }}
